### ISSUE TITLE
Decode should let you specify an algorithm to use.

### ISSUE THREAD

**Issue by ofirgeller** [jwt-dotnet/jwt#10]
If for some reason I decide an algorithm is no longer safe. I should be able to stop treating tokens signed using that algorithm as "verified". if i understand the current code, if it is in the header and in the list of possible algorithms, it will be used. you might say it doesn't matter, as cracking the key will be super hard with no sample to work with (as they are all encoded using the algorithm I *am* using) but It is one more layer of protection, with no downsides.

suggestion:
   public static string Decode(string token, byte[] key, JwtHashAlgorithm = null)

no need for  "bool verify = true" for this overload.

**Comment by mikelehen** [comment]
Feel free to submit a PR.  Though I wonder if it'd make sense to accept a list of JwtHashAlgorithms rather than only one?  (there might be multiple algorithms you want to accept)

**Comment by ofirgeller** [comment]
A list is a good idea.
Do we need to keep the api backward compatibly? if i'm going into the code I prefer to also:
1. make they object decoding and encoding not static.
2. avoid the "bool api" by passing it a config object like.

     public class DecodeOptions
        {
            public DecodeOptions()
            {
                Verify = true;
            }

            public bool Verify { get; set; }

            public ICollection<JwtHashAlgorithm> AcceptedAlgos { get; set; }
        }

**Comment by mikelehen** [comment]
Sorry, I never replied. 

We could make a breaking change, though we'd need to bump the version to 2.x.  Honestly, I'm not sure it's worth it at this point.  I'd probably just add another optional param to decode().  But if you make a PR that adds DecodeOptions and update the docs, I'd probably be fine with that. :-)

**Comment by abatishchev** [comment]
I'd go with an overload accepting Encode/DecodeOptions and bumping the version to 2.x.

Another possible property could be `Func<string, object>` meaning the way to (de)serialize JSON.

**Comment by abatishchev** [comment]
I believe this one can be closed due https://github.com/jwt-dotnet/jwt/pull/25.
