### ISSUE TITLE
any certificate implementation ? 

### ISSUE THREAD

**Issue by RoyiNamir** [jwt-dotnet/jwt#104]
do you have in docs any example for RSA asymetric usage via certificate ?

**Comment by abatishchev** [comment]
hi, sorry, no docs yet. feel free to add some :) but here you can find some examples: http://stackoverflow.com/questions/26478694/how-to-produce-jwt-with-google-oauth2-compatible-algorithm-rsa-sha-256-using-sys

**Comment by abatishchev** [comment]
Did this answer you question?
