### ISSUE TITLE
Payload Builder

### ISSUE THREAD

**Issue by MovGP0** [jwt-dotnet/jwt#113]
there should be a static class with strings of public names and a builder to make it easier to create JWT payloads: 
```csharp
IDictionary<string, object> payload = new JwtPayloadBuilder()
// default public claims should be implemented
    .Issuer("https://issuer.example.com") // .Claim(PublicNames.Issuer, "https://issuer.example.com")
    .Subject("user@example.com") // .Claim(PublicNames.Subject, "user@example.com")
    .Audience("https://audience.example.com") // .Claim(PublicNames.Audience, "https://audience.example.com")
    .ExpirationTime(TimeSpan.FromHours(0.5)) // .Claim(PublicNames.ExpirationTime, DateTime.UtcNow + TimeSpan.FromHours(0.5))
    .NotBefore(DateTime.Now) // .Claim(PublicNames.NotBefore, DateTime.Now)
    .IssuedAt(DateTime.Now) // .Claim(PublicNames.IssuedAt, DateTime.Now)
    .Id(Guid.NewGuid()) // .Claim(PublicNames.JwtId, Guid.NewGuid())
// other public claims should be implemented
    .GivenName("John") 
    .FamilyName("Doe")
// it must be possible to provide private claims
    .Claim("key", "value") 
    .Claim("key", dictionary)
    .Claim("key", object) 
// Security Event Tokens
    .Event("http://schemas.openid.net/event/backchannel-logout", null)
// nesting another JWT token (impacts the header's Content Type field)
    .WithNestedJwt(token)
    .Build();
```
* Timestamps should work with `DateTime` (convert to UTC) and `TimeSpan` (add `DateTime.UtcNow`)
* ID should provide overloads for `long`, `Guid`, and `string`
* a list of public claims can be found here: https://www.iana.org/assignments/jwt/jwt.xhtml 
* infos for Security Event Tokens see https://self-issued.info/?p=1620

**Comment by MovGP0** [comment]
Technically we could also expand this approach to an `JwtTokenBuilder`: 
```csharp
var token = new JwtTokenBuilder()
    .WithSerializer(new JsonNetSerializer())
    .WithAlgorithm(new RSAlgorithmFactory(GetCert).Create(JwtHashAlgorithm.RS256))
    .WithUrlEncoder(new JwtBase64UrlEncoder())
    .Issuer("https://issuer.example.com")
    .Subject("user@example.com")
    .Audience("https://audience.example.com")
    .ExpirationTime(TimeSpan.FromHours(0.5))
    .NotBefore(DateTime.Now)
    .IssuedAt(DateTime.Now)
    .Id(Guid.NewGuid()) 
// ...
    .Build();
```

**Comment by abatishchev** [comment]
Hi! Actually this is a cool ideal. I'm not a big fan of that for validation (we just abandoned static API for it) but for composition such fluent API would work.

Would you be willing to get a start for such builder?

**Comment by nbarbettini** [comment]
I like this - it would make it much easier to construct a JWT

**Comment by abatishchev** [comment]
Yes, cool idea! One just needs to go ahead and start the work. Others can join later on.

**Comment by StefH** [comment]
Also add:
Timestamps should work with EPOCH unix-time

**Comment by paule96** [comment]
Has anyone started it? If not I will open a new Repo for this.

**Comment by abatishchev** [comment]
Sure, please go ahead! This contribution would be much appreciated. Will bump the version to 4.0.

**Comment by paule96** [comment]
Here you can follow the first lines of code for [JWT.JWTBuilder](https://github.com/paule96/JWT.JWTBuilder)

I start tomorrow with coding.

**Comment by MovGP0** [comment]
@paule96 why a new project? wouldn't it be easier to simply fork this one and make a pull request when finished?

**Comment by paule96** [comment]
I think it is more an Add-On to this project. 
We will see how much good we write. Like Linq to List<T>.

**Comment by abatishchev** [comment]
I don't think we need another project until it would have the dependencies that would be unwelcome in the main project. Also it would hurt the discoverability, simply less (or no) people would know about it.

**Comment by MovGP0** [comment]
LINQ is a large framework. I don't think that two classes are enough reason to justify the overhead of a separate `.dll` file.

**Comment by paule96** [comment]
Okay I have copy the code in the original package. you can see it here [113_PayloadBuilder](https://github.com/paule96/jwt/tree/issues/113_PayLoadBuilder).

Also I have created the code in the other repo. Because:
- The new code requires .NET Standard 2.0
- I'm actually not shure why my test only run in a separate project file (help me)
- It is much code and it is not all included now of the Requirements

The working code in the other Repo you can find [here](https://github.com/paule96/JWT.JWTBuilder/tree/feature/01initalProjectSetup)

Finally I can say the basics are done. 

I think I write the next lines at the weekend. I'm out for today.

**Comment by abatishchev** [comment]
Thanks for starting working on this! I'm happy to participate, too. Would you please create a new pull request in this repo to see the diff better?

**Comment by paule96** [comment]
here it is #140

**Comment by paule96** [comment]
Can we now closed this? Because the work is done.
