### ISSUE TITLE
Have a signed nuget package

### ISSUE THREAD

**Issue by franckleveque** [jwt-dotnet/jwt#115]
Currently the available nuget package can't be used with signed components as it is not signed itself.

It would be great to have a signed version of the dll available from nuget.

**Comment by abatishchev** [comment]
Hi,
Personally I'm against signing exactly due to the reason you've just mentioned: signed dlls can't reference unsigned ones. It's like plague.
But i realize there are sometimes policies that are stronger and stricter than us.
Can you please explain the reason why you sign your assemblies?

Meanwhile we can modify the build so it would produce two nuget packages, one signed and one unsigned.

**Comment by franckleveque** [comment]
Hi, 

To be honest, we used this feature since the first version of our software (2007). At the time, reasons that were given, was to allow to verify origin of our software and ensure it was not tampered. 

After your question, I tried to look at the current status of signed assemblies, it seems there's much changes in the usefullness of the signed dlls, we might need to evaluate again the benefits of such a thing.

Anyway, thanks for your qick answer.

**Comment by abatishchev** [comment]
Strong name signature works well if your software is deployed in binaries. In the age of NuGet it's almost​ not a case anymore.
Thanks for open-mindnesa and willingness to review your approach. If you conclude that you still need it then we can  produce two packages by the build and push them simultaneously, starting current version (v3).

**Comment by damianh** [comment]
> Meanwhile we can modify the build so it would produce two nuget packages, one signed and one unsigned.

When down that path - it results in a mess for upstream libs that depend on your lib.  It's a massive PITA when key is lost/changed ( i.e. log4net 1.2.11) or when there are diamond dependencies (assembly load exceptions).

Instead, @franckleveque, consider using https://github.com/dsplaisted/strongnamer.

> One of the immediate benefits we have, is the fact it ensure some validity of the installation made by our customers. 

That's not what strong naming is for. Use Authenticode instead. Many OSS libs that do strong naming put `.snk` in version control. As a vendor consuming these OSS libs, _you_ are responsible for the authenticity and safety of the binaries you ship (This is also called 'vendorizing'). Deal with this as a build time concern and not as a development one.
