### ISSUE TITLE
How ro combine an RSA openssl certificate and private key into a X509Certificate2 which can be used in JWT?

### ISSUE THREAD

**Issue by StefH** [jwt-dotnet/jwt#123]
I've a question.

I'm trying to create an `X509Certificate2` based on an **OpenSSL** certificate file and private key file.
These files are generated like:
```
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out certificate_pub.crt
```

And I'm using some code based on http://www.jensign.com/opensslkey/opensslkey.cs to get the raw bytes and generate a `X509Certificate2` object.

See https://github.com/StefH/JwtTest/tree/master/JwtTest as example project.

However , when I check the generated token in https://jwt.io/, the validation fails.

Can you please help me?

**Comment by StefH** [comment]
It seems an issue in `RS256Algorithm.cs` ?
https://github.com/jwt-dotnet/jwt/issues/124

**Comment by abatishchev** [comment]
Let's consolidate the discussion
