### ISSUE TITLE
Feature: not needed to provide a key in the encode method when using RS256

### ISSUE THREAD

**Issue by StefH** [jwt-dotnet/jwt#125]
The **Encode** method requires a key parameter, but this is not needed in case of RS256 because the RSA private key is used there.

So this code
```c#
string token = encoder.Encode(payload, "");
```
Could be like:
```c#
string token = encoder.Encode(payload);
```

Can you update your source-code to create a new method without a key, or set default to null.

**Comment by abatishchev** [comment]
But it's needed in other scenarios, correct? The built-in `JwtEncoder` can use only 1 method,
If there would be 2, how it would choose which to call since the underlying algorithm is abstracted out.
If we just remove the parameter, how other algorithms would work?

**Comment by abatishchev** [comment]
Sorry but "won't fix" from that perspective.

**Comment by StefH** [comment]
True. You are correct. No problem.
