### ISSUE TITLE
Separating Decoding and Validating functionality?

### ISSUE THREAD

**Issue by nskhara** [jwt-dotnet/jwt#126]
Hello. Thanks for a nice library for JWT.

One thing that I want to request that can you separate the functionality of decoding and validation?

My purpose is that, in my usage, I have a identifier in the payload in which to determine the secret key on the server-side (the recipient of the token), so if I try to decode and validate the token, I have to do the followings.

1. Decode without verification
`var json = decoder.Decode(token, secret: null, verify: false);`
2. Get the identifier from the json payload
`var tokenInfo = JsonConvert.DeseirializeObject<TokenInfo>(json);`
`var identifier = tokenInfo.Identifier;`
3. Get the secret key using the identifier
`var secret = secretsDicionary[identifier];`
4. Decode again, this time, with verification
`decoder.Decode(token, secret: secret, verify: true);`

In order to accomplish the above purpose, can you publicize JwtDecoder.Validate method instead of making it private?
Or maybe creating another interface for validation?

Thank you.

**Comment by abatishchev** [comment]
Hello,
Thanks for kind words!
Few thoughts:

- You can use `DecodeToObject<T>` to avoid your #2.
-  Validation logic is already extracted into `JwtValidator : IJwtValidator`
- Private method `Validate` just prepared data to conform the signature of public method `Validate`

Hope this helps. Let me know if this is not sufficient.

**Comment by nskhara** [comment]
Hello, thank you for the response.

> You can use DecodeToObject<T> to avoid your #2.

Oh yes, you're right. Thanks for pointing it out.

> Validation logic is already extracted into JwtValidator : IJwtValidator
> Private method Validate just prepared data to conform the signature of public method Validate

So, you are telling me to implement the following somewhere in my code?
For the work around that's okay, but I just thought that if I could re-use the logic for myself.

`var crypto = _urlEncoder.Decode(parts[2]);`
`var decodedCrypto = Convert.ToBase64String(crypto);`
`var header = parts[0];`
`var headerJson = Encoding.UTF8.GetString(_urlEncoder.Decode(header));`
`var headerData = _jsonSerializer.Deserialize<Dictionary<string, object>>(headerJson);`
`var bytesToSign = Encoding.UTF8.GetBytes(string.Concat(header, ".", payload));`
`var algName = (string)headerData["alg"];`
`var alg = _algFactory.Create(algName);`
`var signatureData = alg.Sign(key, bytesToSign);`
`var decodedSignature = Convert.ToBase64String(signatureData);`
`_jwtValidator.Validate(payloadJson, decodedCrypto, decodedSignature);`

**Comment by abatishchev** [comment]
I see what you're saying, it worthless to repeat of that method is already written. I can make it public. But it won't be part of any interfaces, since is a glue between Decoder and Validator. Ok?

**Comment by abatishchev** [comment]
Let's continue the discussion in the pr.
