### ISSUE TITLE
Lowest target .NET version

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#130]
Let's discuss, gather opinions and requirements on what should be the lowest target .NET Framework version, whether it's 3.5, 4.0, 4.5, 4.6.2, or 4.7.

**Comment by PureKrome** [comment]
Current min supported is 4.5.2. So maybe target that? (ref: https://support.microsoft.com/en-sg/lifecycle/search?alpha=.net%20framework%204.5.2)

What's the pro's / con's of min targeting 4.6.2 or 4.7

**Comment by abatishchev** [comment]
Indeed 4.5.2 is currently min supported version. I think that's what we need to min support as well. Thoughts?

**Comment by PureKrome** [comment]
lets do it!

**Comment by nbarbettini** [comment]
Since [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) is the future of PCLs and x-plat stuff, it might make sense to target `netstandard10` or `netstandard11`. That would mean supporting .NET 4.5. Or, in general, targeting the lowest possible netstandard number.

**Comment by PureKrome** [comment]
... which is a good target .. but at what cost? Is there a cost?

**Comment by abatishchev** [comment]
IIRC we target netstandard1.3 because of the crypto api

**Comment by nbarbettini** [comment]
Right, that makes sense. Unless someone specifically asks for a version for .NET 4 or 4.5, I think it's fine where it's at right now.

**Comment by abatishchev** [comment]
@StefH has asked for 4.0 some time back.

Can you please describe your scenario/environment/requirements? 4.5.2 is the lowest supported as of today version, all lower are out of support. From my perspective the transition from 4.0 to 4.5 is long due, and from 4.5 to 4.6/4.7 usually is seamless. But again we'd like to understand your perspective.

**Comment by StefH** [comment]
I did not ask specifically for 4.0 but its always a good design to support the lowest possible framework.

**Comment by PureKrome** [comment]
I'm assuming that version 2.4.2 is compatible with older versions. So there's always _something_ available for older frameworks.

**Comment by abatishchev** [comment]
> it's always a good design to support the lowest possible framework.

I agree but only in part. *the lowest possible* can have multiple meanings: technically feasible, maintenance reasonable, etc.
I mean that *technically* we could indeed target 4.0 or even continue with 3.5. However since 4.5.2 is the lowest supported I believe it would be the *reasonable* target.

P.S. in my personal opinion (and not as the maintainer of this project) those who still target 2.0 and 3.5 must suffer. More they suffer - faster they upgrade. Making their lifes easier only prolongs their agony :)

**Comment by StefH** [comment]
In case you need a lot of `#if` `#else` `#endif` statements or need to drop functionality, then lowering is not a good idea.

In this specific case, I would be happy if version **.NET 4.5.2** is the minimal supported version.
