### ISSUE TITLE
missing overloads for decode.

### ISSUE THREAD

**Issue by paule96** [jwt-dotnet/jwt#138]
Hey hey Developers :)

I have seen a issue in the framework to get the payload of an JWT. To get a payload of an JWT without validation we don't need a key/secret. So in the file [jwt/src/JWT/JwtDecoder.cs ](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JwtDecoder.cs) we missed a overload, for the mehtod Decode that only need a token. (for DecodeObject I will create a the same overload)

Can I create a PullRequest for this?

Best regards Paul 👍

**Comment by paule96** [comment]
Here ist the Pullreqeust #139.

**Comment by abatishchev** [comment]
hey Paul, thanks for the changes! let's continue the discussion in the pr itself.
