### ISSUE TITLE
Possibly reduce target from net462 to net46

### ISSUE THREAD

**Issue by psylenced** [jwt-dotnet/jwt#141]
Just a small follow up on your targeting. I noticed you needed to bump up the version to 4.6.x due to `RSA.SignData`, however you targeted 4.6.2 which forced my 4.6.1 project into `netstandard` which I didn't want.

Is there any reason why you need 4.6.2 specifically? If not you should target the minimum required version (being `net46`).

**Comment by abatishchev** [comment]
Closing it since the discussion has moved to the pr.
