### ISSUE TITLE
NullReferenceException in jwtEncoder.Encode()

### ISSUE THREAD

**Issue by bilal-fazlani** [jwt-dotnet/jwt#148]
Here's my code

```c#
[HttpPost]
[Route("/token/encode")]
public IActionResult EncodeToken()
{
    string body;
    
    using (StreamReader reader 
        = new StreamReader(Request.Body, Encoding.UTF8, true, 1024, true))
    {
        body = reader.ReadToEnd();
    }
    
    JObject content = JObject.Parse(body);
    
    IJwtAlgorithm algorithm = new RS256Algorithm(GetCertificate());
    
    IJwtEncoder jwtEncoder = new JwtEncoder(algorithm, new JsonNetSerializer(), new JwtBase64UrlEncoder());
    byte[] privateKey = GetPrivateKey();
    
    string encodedToken = jwtEncoder.Encode(content, privateKey);
    
    return Ok(encodedToken);
}
private X509Certificate2 GetCertificate()
{
    return new X509Certificate2(System.IO.File.ReadAllBytes(LOCAL_SECRET_DIR+"certificate.cer"));
}
private byte[] GetPrivateKey()
{
    return System.IO.File.ReadAllBytes(LOCAL_SECRET_DIR+"private.pem");
}
```

The exception occurs at `string encodedToken = jwtEncoder.Encode(content, privateKey);`

Here's the stack trace : 

```
onnection id "0HLAD40HUG621", Request id "0HLAD40HUG621:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at JWT.Algorithms.RS256Algorithm.Sign(Byte[] key, Byte[] bytesToSign)
   at JWT.JwtEncoder.Encode(IDictionary`2 extraHeaders, Object payload, Byte[] key)
   at JWT.JwtEncoder.Encode(Object payload, Byte[] key)
```

**Comment by bilal-fazlani** [comment]
<img width="977" alt="screen shot 2017-12-27 at 5 33 06 pm" src="https://user-images.githubusercontent.com/3396271/34381476-b27f3784-eb2e-11e7-8ee9-c03262f163eb.png">

Nothing seems to be null on my side when I debug..

**Comment by abatishchev** [comment]
Hi, what version are you using? We've added many guard checks later.

P.S. All classes are thread-safe, I'd recommend to share (make static) all instance of JWT classes.

**Comment by bilal-fazlani** [comment]
@abatishchev 
I was using latest stable version. Now I have upgraded to latest beta 3.2.0-beta.

I have narrowed down the issue more. When I create instance of `X509Certificate2` from a cer file, and inspect the instance, it has only public key and not the private key.
This is when it throws null reference exception.

When I create instance of `X509Certificate2` from a pfx file, the instance has both private and public keys and then it works fine. 

A couple of things, 

1. if what I am saying is correct, then I think we should make the error a bit more easy understand.
2. I can get why private key is required for encoding a token, but I don't understand it requires private key to decrypt the token too.

**Comment by bilal-fazlani** [comment]
I have one more observation.

this is how I am generating my token:

```c#
string token = new JwtBuilder()
    .SetAlgorithm(GetRS256Algorithm())
    .SetSecret("WILL_NOT_BE USED")
    .AddClaim("token", content)
    .Build();
```

and this is how I am decoding it:

```c#
IJsonSerializer serializer = new JsonNetSerializer();
IDateTimeProvider provider = new UtcDateTimeProvider();
IJwtValidator validator = new JwtValidator(serializer, provider);
IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
IJwtDecoder decoder = new JwtDecoder(serializer, validator, urlEncoder, new RSAlgorithmFactory(GetPfxCertificate)
string json = decoder.Decode(token, "DUMMY_SECRET", verify: true);
```

As you see, I am passing a different secret at the time of encoding and I am decoding with a different secret (with `verify` flag set to true). I am using an asymmetric algorithm and I think it is using the public key for verification instead of the secret (which I think is correct)

What I find weird is the library seems to have made it mandatory to `SetSecret` even in case when it is not being used... for instance - my above case.

Is this understanding correct ?

**Comment by abatishchev** [comment]
Yes, we need to check whether private key is present rather than relying it does and getting NRE if it's not. Or if you'd like can you please submit this change?

The Fluent Builder API is fresh and brand new. It's initial design made secret mandatory. I tried to relax that but looks like still missed some places. Need to change that too. Again, if you'd like, please submit this change. Or I'll do it slightly later.

**Comment by abatishchev** [comment]
Let me close this and address the discovered issues in respective pull requests.

**Comment by abatishchev** [comment]
Answering your questions:

1. This is addressed by #150, please take a look
2. Decode() requires secret if verify=true. Pass either false or use an overload without it.

**Comment by abatishchev** [comment]
@bilal-fazlani please take a look at #151

**Comment by MohmdAzhar** [comment]
Even i'm Facing the same issue

**Comment by abatishchev** [comment]
@MohmdAzhar hi! Happy to investigate the issue you're facing together.

Please open a new issue. Provide the version you're using (and make sure it's the latest), weather it's stable or preview (try 10.0.0-preview latest), error message and full exception stack trace.
