### ISSUE TITLE
JwtBuilder expects secret to be mandatory even for RS256

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#149]
As per #148.

**Comment by abatishchev** [comment]
@ bilal-fazlani can you please provide quick sample how to repro this issue? As far as I can see from the code, it won't be an issue until verify=true.

**Comment by bilal-fazlani** [comment]
Yes, I was wondering do we really need the private key for verification ? I thought private keys are supposed to be only with the sender and receivers  are supposed to verify the message with a public key. 

Please correct me if I am wrong @abatishchev , I am new to all this security stuff.

**Comment by bilal-fazlani** [comment]
As far are just reading of the message is concerned, it shouldn't require any key. It's only the verification that should require a _public key_.

If this library requires private key for verification, it it will require sharing of private key which I believe is breaks the entire security ...

**Comment by abatishchev** [comment]
I'm frankly quite new too! :)

The initial/default scenario is when the library is used to decrypt a token and verify its signature simultaneously at the destination server. The async encryption algorithms family was added later. And its specific verification methods are about to be added now. What also include verification by 3rd party (the one who don't have private key), again to my understanding.

**Comment by abatishchev** [comment]
The flow (almost literally) looks like this:
```csharp
var payload = Decode(token);

if (verify)
    Verify(token, signature);

return payload;
```

What means that verification (so signature generation) is performed only if verify=true. Otherwise the library isn't concerned at all about the signature.

**Comment by bilal-fazlani** [comment]
Makes sense.

**Comment by abatishchev** [comment]
Please try 4.0.0-beta2 and let know whether all issues you were facing are resolved now.

**Comment by bilal-fazlani** [comment]
I am not sure @abatishchev 
Here's my code

```c#
IJwtAlgorithm algorithm = new RS256Algorithm(new X509Certificate2(File.ReadAllBytes("certificate.pfx"), "pfxpass"));

IJsonSerializer serializer = new JsonNetSerializer();
IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);

var token = encoder.Encode(payload, ??????);
```

What is the 2nd parameter of Encode method expecting? the IJwtAlgorithm already has private key (certificate.pfx).

**Comment by abatishchev** [comment]
Pass `(null, payload)`. See https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/RS256Algorithm.cs#L29, it ignores first parameter.

**Comment by bkwdesign** [comment]
Maybe add a unit test for this or a code sample on the readme.md page - I'm stumbling on this, too

**Comment by abatishchev** [comment]
Sure, please feel free to start a PR, I'll help to get it through.
