### ISSUE TITLE
RS256Algorithm expects private key to be present, throws NRE if it's not

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#150]
As per #148.

**Comment by bilal-fazlani** [comment]
- [ ] Ensure that library does not throw any exception if private key in not present **when decoding or verifying a token**
- [ ] Ensure that library throws a more specific exception instead of NRE when private key is no present **when encoding a payload**

**Comment by abatishchev** [comment]
The former is not an issue since Sign() is called only if verify=true. The latter has been addressed.

**Comment by MohsenneChaverdie** [comment]
`var key = RSA.Create(privateKey);
                IJwtAlgorithm algorithm = new RS256Algorithm(null, key);
                IJsonSerializer serializer = new JsonNetSerializer();
                IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();

                IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);

                signedJwt = encoder.Encode(extraHeaders, payload, privateKey);`

that returns NullReferenceError for me!

**Comment by abatishchev** [comment]
@MohsenneChaverdie in what line of what class and what's the version of the library?

**Comment by MohsenneChaverdie** [comment]
Class Name: RS256Algorithm
Lib: JWT 5.2.0 (Published Date: June 13th, 2019)

**Comment by abatishchev** [comment]
Since you're getting an exception in the latest version, please open a new issue and post its full stack trace (you can omit/obfuscate your app's part). I'll take a look and fix it asap (if possible).
