### ISSUE TITLE
The NuGet package is out of date :(

### ISSUE THREAD

**Issue by cmatskas** [jwt-dotnet/jwt#16]
Could you please update the NuGet package as there are things missing, such as token expiry validation etc.
Thanks!

**Comment by mikelehen** [comment]
Oops, sorry.  I'll see if I can get it updated in the next few days.

**Comment by cmatskas** [comment]
Hi @mikelehen, thanks for the update. Could you fire off a message when the latest package is available on NuGet? thanks :)

**Comment by devinrader** [comment]
@mikelehen are ytou ready to get a new version pushed to NuGet?  I beleive I can do that if you don't have time.  Plus I need to get #20 pushed out as well :)

**Comment by devinrader** [comment]
Hey @mikelehen I'm going to go ahead and take whats in master and publish a new build to NuGet tonight.  I'll leave it to you for now to look at the remaining pull requests and merge as you see fit.

**Comment by mikelehen** [comment]
Thanks @devinrader!  I've been swamped lately and doing a poor job of maintaining this. :-(  Publishing a new version to Nuget would be great.

**Comment by devinrader** [comment]
1.3.3 pushed to NuGet
