### ISSUE TITLE
Serious design issue wrt the RS256 implementation...

### ISSUE THREAD

**Issue by larsw** [jwt-dotnet/jwt#166]
Hi,

 I'm currently looking into stripping down and reusing parts of this library, and while doing so,
 I've found a serious design flaw that affects the RS256 implementation, and possibly the implementation
 of other asymmetric signature schemes (ES* etc.). It boils down to two things:

 * Having to pass a symmetric byte[] key into the JwtDecoder.Validate() overloads.
 * JwtDecoder.Validate(JwtParts jwt, byte[] key): does an alg.Sign(key, bytesToSign) ! e.g. it expects the verifier to re-sign the header+payload before comparing it to the attached signature, instead of doing a proper signature verification with the public key.

Another issue, while smaller, is that the Validate() decodes the signatures to a byte array and re-codes it as base64, before passing it downstream to the validator.Validate() that again decodes them to byte arrays.

The naming is also ambigous; JwtDecoder.Validate() calls -> JwtValidator.Validate() - the interface doesn't really reveal the intended purpose...

I would suggest a refactoring that will split the symmetric HMAC algorithms from asymmetric signature algorithms, and rework how key material are passed through the moving parts of the library.

**Comment by abatishchev** [comment]
Ping

**Comment by abatishchev** [comment]
Ping?
