### ISSUE TITLE
String reference not set to an instance of a String. Parameter name: s

### ISSUE THREAD

**Issue by flyingdutchy** [jwt-dotnet/jwt#168]
This does not seems to work for me as I get the following exception:

> String reference not set to an instance of a String.Parameter name: s
>    at System.Text.Encoding.GetBytes(String s)
>    at JWT.JwtDecoder.DecodeToObject[T](String token, String key, Boolean verify)
>    at JWT.Builder.JwtBuilder.Decode[T](String token)

Using the following code

```C#
void Main()
{
	var certificateText = 
		"-----BEGIN CERTIFICATE-----\n" +
		"MIIBljCCAUACCQCIDMpqK7WfWDANBgkqhkiG9w0BAQsFADBSMQswCQYDVQQGEwJV\n" +
		"UzETMBEGA1UECAwKU29tZS1TdGF0ZTESMBAGA1UECgwJTHV4b3R0aWNhMRowGAYD\n" +
		"VQQLDBFMdXhvdHRpY2EgZXllY2FyZTAeFw0xODA1MjMxNTE1MjdaFw0yODA1MjAx\n" +
		"NTE1MjdaMFIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApTb21lLVN0YXRlMRIwEAYD\n" +
		"VQQKDAlMdXhvdHRpY2ExGjAYBgNVBAsMEUx1eG90dGljYSBleWVjYXJlMFwwDQYJ\n" +
		"KoZIhvcNAQEBBQADSwAwSAJBAKuMYcirPj81WBtMituJJenF0CG/HYLcAUOtWKl1\n" +
		"HchC0dM8VRRBI/HV+nZcweXzpjhX8ySa9s7kJneP0cuJiU8CAwEAATANBgkqhkiG\n" +
		"9w0BAQsFAANBAKEM8wQwlqKgkfqnNFcbsZM0RUxS+eWR9LvycGuMN7aL9M6GOmfp\n" +
		"QmF4MH4uvkaiZenqCkhDkyi4Cy81tz453tQ=\n" +
		"-----END CERTIFICATE-----";

	var token = @"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuLmNoaWVmZm8iLCJleHAiOjE1MjcyMzg4ODEsImlzcyI6Imx1eCJ9.BAaYzLwokmdKqLi6zKjGIpDXd__dZxi5PUWWHS3PSLPDYAInzPbEK8o4WxunoGD7eA0qtQNaxNpzeOc3BHrd4w";

	var certificate = new X509Certificate2(Encoding.ASCII.GetBytes(certificateText));
		
	var json = new JwtBuilder()
		.WithAlgorithm(new JWT.Algorithms.RS256Algorithm(certificate))
		.WithVerifySignature(verify: true)
		.Decode<IDictionary<String, String>>(token);
		
	Console.WriteLine(json);
}
```

**Comment by abatishchev** [comment]
Hi, what version are you using?

**Comment by flyingdutchy** [comment]
Latest: 4.0.0

**Comment by abatishchev** [comment]
Your certificate doesn't contain private key:

```c#
var certificate = new X509Certificate2(Encoding.ASCII.GetBytes(certificateText));
Debug.Assert(certificate.HasPrivateKey);
```

**Comment by flyingdutchy** [comment]
I would expect a private key to be required to create a JWT, but to validate a JWT, only a public key is required.

**Comment by abatishchev** [comment]
Right. The remove `WithVerifySignature(verify: true)` and it will work. Is it something you'll looking for? Or not?

**Comment by flyingdutchy** [comment]
Thanks for your quick responses! However for me to trust the JWT would I not need to verify the signature? I am expecting to verify the signature using the public key contained in the certificate. Would removing `WithVerifySignature(verify: true)` not be defeating the whole purpose of validating the JWT? If all I needed to do was decoding payload of the JWT to get the claims, I could simply do that with a call to 'Convert.FromBase64String(payload)'. But I need to validate the signature. Are you saying that validation is done with the PrivateKey? If so how would one validate the origin of the token?

**Comment by abatishchev** [comment]
Ok, so in your code you're calling `Decode()` which needs a secret, i.e. the private key.

Just to verify using the public key, `RS5256Algorithm` has method `Verify`:

```c#
var jwt = new JwtParts(token);
var res = new RS256Algorithm(certificate)
                .Verify(
                    Encoding.UTF8.GetBytes(String.Concat(jwt.Header, ".", jwt.Payload)),
                    Encoding.UTF8.GetBytes(jwt.Signature));
```

(Ugly API, I agree, need improvement)

Does it make more sense? However it returns `false` for the input you've provided.

**Comment by flyingdutchy** [comment]
That is very helpful, thank you! Is the same possible with just a public key PEM, rather than a certificate? I.e. : with the following which does verify the JWT on the JWT.io site.

> -----BEGIN CERTIFICATE-----
MIIBljCCAUACCQCIDMpqK7WfWDANBgkqhkiG9w0BAQsFADBSMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKU29tZS1TdGF0ZTESMBAGA1UECgwJTHV4b3R0aWNhMRowGAYD
VQQLDBFMdXhvdHRpY2EgZXllY2FyZTAeFw0xODA1MjMxNTE1MjdaFw0yODA1MjAx
NTE1MjdaMFIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApTb21lLVN0YXRlMRIwEAYD
VQQKDAlMdXhvdHRpY2ExGjAYBgNVBAsMEUx1eG90dGljYSBleWVjYXJlMFwwDQYJ
KoZIhvcNAQEBBQADSwAwSAJBAKuMYcirPj81WBtMituJJenF0CG/HYLcAUOtWKl1
HchC0dM8VRRBI/HV+nZcweXzpjhX8ySa9s7kJneP0cuJiU8CAwEAATANBgkqhkiG
9w0BAQsFAANBAKEM8wQwlqKgkfqnNFcbsZM0RUxS+eWR9LvycGuMN7aL9M6GOmfp
QmF4MH4uvkaiZenqCkhDkyi4Cy81tz453tQ=
-----END CERTIFICATE-----

**Comment by abatishchev** [comment]
This idea was already mentioned in #164. Would it be something you could pick up and submit a pull request? Even a draft, I'll refactor and finish up if would be needed.

And meanwhile, how the code calling the existing API looks like? I'd like to copy/paste it to an overload to simplify its usage.

**Comment by flyingdutchy** [comment]
Thank you!!

**Comment by abatishchev** [comment]
You're welcome! Please post some of your code to improve the existing validation API.
