### ISSUE TITLE
Decode to ClaimsPrincipal

### ISSUE THREAD

**Issue by vincentparrett** [jwt-dotnet/jwt#169]
It would be nice to see a Decode to ClaimsPrincipal method on IJwtDecoder - would save a alot of work for users of the library.

**Comment by abatishchev** [comment]
Do you already have the code to do that? I (or you) can submit a pull request, happy to review/accept.

**Comment by vincentparrett** [comment]
I don't right now, but looking into it. At the moment I'm just pulling the usern name from the token and going to the db to get the rest of the data, which defeats the object of using jwt. I will need to figure out how to convert the payload to claims... since the payload may or may not be claims... perhaps we need both ends, take a claimsprincipal as a payload.

**Comment by vincentparrett** [comment]
After further consideration, this is just too specific and probably best left to the consumer. I created a simple method to do what I needed, where I decode the payload to a dictionary, this does what I need (including here in case others look to do the same). 
```c#
private ClaimsPrincipal CreateClaimsPrincipal(IDictionary<string, string> jwtProperties, Predicate<string> filter, string authType = "Jwt")
{
  List<Claim> claims = new List<Claim>();
  foreach (var pair in jwtProperties)
  {
    if (filter != null && !filter(pair.Key))
    {
      continue;
    }
    var claim = new Claim(pair.Key, pair.Value);
    claims.Add(claim);
  }

  var identity = new ClaimsIdentity(claims, authType); //authType is needed, otherwise identity.IsAuthenticated will be false.
  return new ClaimsPrincipal(identity);
}

//calling above
string[] ignores = new string[] { "iss", "exp", "iat" };
Predicate<string> filter = (x) =>
{
  return !ignores.Contains(x);
};

principal = CreateClaimsPrincipal(jwtProperties, filter);
```
