### ISSUE TITLE
Jwt returns same token everytime

### ISSUE THREAD

**Issue by watoo** [jwt-dotnet/jwt#170]
**Encryption:**
```
IJwtAlgorithm algorithm = new HMACSHA256Algorithm();
            IJsonSerializer serializer = new JsonNetSerializer();
            IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
            IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);
            var secret = WebConfigurationManager.AppSettings["Secret"];
var data = new ApiToken(user.Id,ip,userApplication.id,group.id);
encryptedData = encoder.Encode(data, secret);
```

**Decryption:**

```
ApiToken token = new JwtBuilder()
                        .WithSecret(secret)
                        .MustVerifySignature()
                        .Decode<ApiToken>(encryptedToken);
```

The encrypted token is same for each request (for one user). How to generate a new token every time.

**Comment by abatishchev** [comment]
Hi, this the right and expected behavior. The resulting token is deterministic/same.
To generate every time new - add a salt, like a timestamp or its hash or something similar.
However, I'm not a security expert and can't judge how secure this would be.
Makes sense?

**Comment by watoo** [comment]
Can you please guide me where to add timestamp in above code?

**Comment by watoo** [comment]
Just append a salt field with other data.
`
Salt = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds()`
