### ISSUE TITLE
Secret key is only B64URL - How about HEX?

### ISSUE THREAD

**Issue by PtkFerraro** [jwt-dotnet/jwt#172]
Should it have more options about the secret key, like HEX, UUID, B64, UTF8

**Comment by abatishchev** [comment]
Hi, can yous share your usage scenario? I believe base64 is prescribed by the JWT spec/RFC.

**Comment by abatishchev** [comment]
Can you share an example of they key in hex?

**Comment by PtkFerraro** [comment]
Looks like a normal key:

3a69fae790106a9858ef3bf8a84e12849f2369a858332466d1cbd04e62f12653347e0a26f095ecb7c7b8a4a76038b3e689207bd85e65a733ee253bfbbe13bf86

This key encoded in hex would be:

3361363966616537393031303661393835386566336266386138346531323834396632333639613835383333323436366431636264303465363266313236353333343765306132366630393565636237633762386134613736303338623365363839323037626438356536356137333365653235336266626265313362663836

In Base64:

M2E2OWZhZTc5MDEwNmE5ODU4ZWYzYmY4YTg0ZTEyODQ5ZjIzNjlhODU4MzMyNDY2ZDFjYmQwNGU2MmYxMjY1MzM0N2UwYTI2ZjA5NWVjYjdjN2I4YTRhNzYwMzhiM2U2ODkyMDdiZDg1ZTY1YTczM2VlMjUzYmZiYmUxM2JmODY=

Em sex, 20 de jul de 2018 às 14:39, Alexander Batishchev <
notifications@github.com> escreveu:
