### ISSUE TITLE
List of features

### ISSUE THREAD

**Issue by monsdar** [jwt-dotnet/jwt#178]
When searching for a JWT library I first stumbled upon [jwt.io](https://jwt.io/). It contains a list of libraries that support JWT, but JWT.Net is not on it.

* Is it possible to get a list of features as they are shown on jwt.io? What are the supported features?
* Should JWT.Net be added to that list?

I already reached out via their forum: https://community.auth0.com/t/jwt-net-not-in-the-list/17047

**Comment by abatishchev** [comment]
Hi, thanks for raising this issue! Let's add this project to the list, sure.

Here's supported features:

```json
support": {
        "sign": true,
        "verify": true,
        "iss": true,
        "sub": true,
        "aud": true,
        "exp": true,
        "nbf": true,
        "iat": true,
        "jti": true,
        "hs256": true,
        "hs384": true,
        "hs512": true,
        "rs256": true,
        "rs384": false,
        "rs512": false,
        "es256": false,
        "es384": false,
        "es512": false
```

**Comment by abatishchev** [comment]
Do you know what  `sub`, `iat`, `jti` stand for? I marked as false as I don't know but just want to make sure.

**Comment by monsdar** [comment]
Thanks a lot for that input! I do not know about the details of those features as well, but added an issue in the [jwt.io bugtracker](https://github.com/jsonwebtoken/jsonwebtoken.github.io/issues/361). Hope everything can get cleared up shortly.

**Comment by abatishchev** [comment]
Hi, do you know if they've added this library to their list?

**Comment by fredericDelaporte** [comment]
> Do you know what `sub`, `iat`, `jti` stand for? I marked as false as I don't know but just want to make sure.

Here is my understanding, based on [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1):
- `sub`: subject claim.
- `iat: "issued at" claim.
- `jti`: "JWT ID" claim.

 I hope they are actually supported by this library. I have not tried it out yet (I am currently investigating which library I should use), but I would expect all registered claims to have some direct support. Anyway they should be specifiable as custom claims otherwise. I have not checked out what jwt.io expect for them to be considered supported.

**Comment by abatishchev** [comment]
Actually they are. Both Encoder and Builder allow to specify any payload/claimset.

**Comment by qazs10015** [comment]
I have a problem
the new version is 5.0.1 and it only support .net Framework 4.6
my project is .net Framework 4.0, so can i use lower version (ex: jwt.Net 3.0.1) 
 between different version have any question?

**Comment by abatishchev** [comment]
Please open another issue and we can discuss.
