### ISSUE TITLE
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "JWT.JwtEncoder".

### ISSUE THREAD

**Issue by stefanstranger** [jwt-dotnet/jwt#179]
I'm trying the use the jwt class in PowerShell but I get an error when trying to encode a payload.

```
$foo = New-Object "System.Collections.Generic.Dictionary[System.String,System.Object]"
$foo.Add('FirstName', 'Stefan')
$foo.Add('LastName', 'Stranger')
$foo.Add('Demo', 'Encode Access Token')
$foo.Add('exp', '1393286893')
$foo.Add('iat', '1393266893')

$foo

$foo.GetType()
```

Foo Object is of type:

    $foo.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Dictionary`2                             System.Object

Error message:

>Cannot convert the "System.Object[]" value of type "System.Object[]" to type "JWT.JwtEncoder".

I initialized the Encoding Object as follows:
```
#region initialize Encoder Object
$Algorithm = [JWT.Algorithms.HMACSHA256Algorithm]::new()
$Serializer = [JWT.Serializers.JsonNetSerializer]::new()
$UrlEncoder = [JWT.JwtBase64UrlEncoder]::new()

 $Encoder = [JWT.JwtEncoder]($Algorithm, $Serializer, $UrlEncoder)
#endregion
```
How should I create the payload?

/Stefan

**Comment by stefanstranger** [comment]
Never mind I made a mistake.
```
#region initialize Encoder Object
        $Algorithm = [JWT.Algorithms.HMACSHA256Algorithm]::new()
        $Serializer = [JWT.Serializers.JsonNetSerializer]::new()
        $UrlEncoder = [JWT.JwtBase64UrlEncoder]::new()

        $Encoder = [JWT.JwtEncoder]::new($Algorithm, $Serializer, $UrlEncoder)
        #endregion
```

**Comment by abatishchev** [comment]
So it eventually it worked? Great! Feel free to ask more questions, if any. Cheers!
