### ISSUE TITLE
Exception-less validation

### ISSUE THREAD

**Issue by fredericDelaporte** [jwt-dotnet/jwt#183]
Maybe I am wrong, but it seems there are no way to validate a JWT token without having exceptions thrown in case of invalid or expired token.

For a web server, this is a pattern which scales badly. Exceptions are costly. Exception-less methods for checking well-formness of token, validity of signature and expiration of the token should be available.

**Comment by abatishchev** [comment]
Hi, yes, you're right. Currently all methods, e.g. [JwtValidator](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JwtValidator.cs), throw exception.

Would you be willing to create a PR to change that?

The only caveat I foresee that it would be impossible to differentiate the reason why a token is invalid if `TryValidate()` would just return true or false.

**Comment by fredericDelaporte** [comment]
Having looked at Microsoft own library code, it seems it gives the option of getting a result object with the JWT data if valid, otherwise with an exception property filled with the exception, not thrown but ready for being thrown if wished. So that could be one way of doing it.
I am considering giving at try with that library, so I may not create a PR here.

Another way of handling the subject here may be to have different validation methods, like one for globally telling if it is valid or not, another one to just tell if it is well-formed, another one for checking the signature, another one for expiry...

Or else a single method, but yielding a result object with properties set to tell what is wrong (or whether all is good).

**Comment by abatishchev** [comment]
You can create a PR regardless. Giving back to the community, you know :)

**Comment by fredericDelaporte** [comment]
I happily give back to the community on software I have used. I do not tend to do it on software I have not yet used.

**Comment by abatishchev** [comment]
The pitfall of OSS. Software isn't good until someone helps to make it good. Isn't it?
And welcome to the OSS maintainer world. Tend to help people who don't tend to help you back.

**Comment by fredericDelaporte** [comment]
I have posted that issue to help contributors of this software make it better by suggesting a potential improvement, although it was already seeming likely to me I would not use it.

If instead you consider that I was unhelpful, do not worry, I have no intend to come back here any more, due to the way you react.

> welcome to the OSS maintainer world

I am far from being new to this world. I also allow me to suggest to people to contribute on issue they raise, but never I have allowed me to be insistent to the point of rudeness.

**Comment by abatishchev** [comment]
Just a reminder what was the point this discussion has escalated at:

>I am considering giving at try with that library, so I may not create a PR here

I personally contribute to OSS regardless. Especially as a courtesy to people who helped me or/and  asked me to help.

Comparing to you who was explicitly shopping around like I owe you a service. That what I found to be rude.

>do not worry, I have no intend to come back here any more, due to the way you react.

Again, being rude was not my intend. I just was explicit as a reaction to you being explicit.

Regardless, thank you for the idea of exception-less validation, I have implemented it yesterday (and linked the PR with this issue).

**Comment by fredericDelaporte** [comment]
This part of the conversation is going nowhere and add no value for anyone. We are not understanding each other, to say the less.

I am going to delete my part of this thread (including this message), in order to let only what make sense here.

**Comment by abatishchev** [comment]
>This part of the conversation is going nowhere and add no value for anyone. We are not understanding each other, to say the less.

This is quit unfortunately because I pointed you to where it started.

> I am going to delete my part of this thread (including this message), in order to let only what make sense here.

It's your right to delete and my right to preserve.

Whatever. Cheers!
