### ISSUE TITLE
Fluent Builder - byte[] key

### ISSUE THREAD

**Issue by Noxor** [jwt-dotnet/jwt#187]
I like the possibility to create token using fluent builder feature. It is however missing the possibility to add the key as byte[] or base64 string, which makes it impossible to use it with randomly generated keys.
(In my case while using HMACSHA256Algorithm)

**Comment by abatishchev** [comment]
Hi, did you manage to get it working using regular set of classes (encoder, decoder, validator)? If yes, then can you provide a sample? If not, do you have an idea where to make the necessary changes in [JwtBuilder](jwt-dotnet/jwt/blob/master/src/JWT/Builder/JwtBuilder.cs)?

**Comment by abatishchev** [comment]
Would #189 work for you?

**Comment by Noxor** [comment]
It looks like it would.

**Comment by abatishchev** [comment]
Please try version of 5.0.1 and let me know how it works for you. Feel free to open another issue or submit a pull request with a change

**Comment by Noxor** [comment]
Thanks for quick change. Version 5.0.1 works with my byte[] secret.
