### ISSUE TITLE
Token is not encrypted when an Expire Time is not provided

### ISSUE THREAD

**Issue by HolyOne** [jwt-dotnet/jwt#190]
```c#
AuthToken tkn = new AuthToken() { MemberId = MemberId, Role = Role, Username = Username   };

if (TokenLifeSpan != null)  //if this variable is null and exp not given
{
    tkn.exp = AuthToken.DateTimeToJWTDouble(DateTime.UtcNow.Add(TokenLifeSpan.Value));
}
string token = TokenEncoder.Encode(tkn, TokenSecret);

//the token is fully decrypted providing any TokenSecret
tkn = TokenDecoder.DecodeToObject<AuthToken>(securedTokenString, TokenSecret, true );
```

Looks like a serious security issue to me.

**Comment by abatishchev** [comment]
What  version you're using?

Can you provide outputs (variable values). From your sample that's not clear.

**Comment by HolyOne** [comment]
I am using the latest version.

This is the full code I am running

`
        public class AuthToken
        {
            //int MemberId, string Username, int Role, string Email
            public int MemberId { get; set; }
            public string Username { get; set; }
            public int Role { get; set; } 
            public double exp { get; set; }
            public static double DateTimeToJWTDouble(DateTime dt)
            {
                return dt.Subtract(JWT.UnixEpoch.Value).TotalSeconds;
            }
            public static DateTime JWTDoubleToDateTime(double d)
            {
                return JWT.UnixEpoch.Value.AddSeconds(d);
            }

 
        }



        static JWT.IDateTimeProvider provider = new JWT.UtcDateTimeProvider();
        public static JWT.IJwtEncoder TokenEncoder = new JWT.JwtEncoder(new JWT.Algorithms.HMACSHA256Algorithm(), new JsonNetSerializer(), new JWT.JwtBase64UrlEncoder());

        static JsonNetSerializer tokenSerializer = new JsonNetSerializer();

        public static JWT.IJwtDecoder TokenDecoder =
            new JWT.JwtDecoder(
            new JsonNetSerializer(),
           new JWT.JwtValidator(tokenSerializer, provider),
            new JWT.JwtBase64UrlEncoder()
          );

        public static string  TokenSecret="TBT-JwtSecret2017*";
        public static string CreateToken(int MemberId, string Username, int Role , TimeSpan? TokenLifeSpan = null)
        {

            TokenLifeSpan = (TimeSpan?)TimeSpan.FromDays(30); //Without this life span, I am able to fully decrypt the token with any password I provide on the line with "TokenDecoder.DecodeToObject"


            AuthToken tkn = new AuthToken() { MemberId = MemberId, Role = Role, Username = Username   };
            if (TokenLifeSpan != null)
            {
                tkn.exp = AuthToken.DateTimeToJWTDouble(DateTime.UtcNow.Add(TokenLifeSpan.Value));


            }
           
            string token = TokenEncoder.Encode(tkn, TokenSecret);
             
            return token; 
        }


   public static AuthToken RebuildToken(string securedTokenString, bool ValidateExpire = false)
        { 
            AuthToken tkn = null;

            try
            {
              tkn = TokenDecoder.DecodeToObject<AuthToken>(securedTokenString, TokenSecret, true );
         //I can decode with any password if no Expiry is given to token at the upper lines
            }
            catch (JWT.TokenExpiredException)
            {
                Console.WriteLine("Token has expired");
            }
            catch (JWT.SignatureVerificationException)
            {
                Console.WriteLine("Token has invalid signature");
            }
            return tkn;
        }
`

**Comment by abatishchev** [comment]
I'm not sure full code is needed. Can you provide token values to illustrate the issue?

**Comment by abatishchev** [comment]
Ping.

**Comment by HolyOne** [comment]
I gave the verify signature parameter as false.
my bad :(
