### ISSUE TITLE
Target lower version of .NET

### ISSUE THREAD

**Issue by qazs10015** [jwt-dotnet/jwt#191]
I have a problem
the new version is 5.0.1 and it only support .net Framework 4.6
my project is .net Framework 4.0, so i can use lower version (ex: jwt.Net 3.0.1)
between different version have any question?

**Comment by abatishchev** [comment]
Why your project targets 4.0? This is

**Comment by qazs10015** [comment]
well...just customer’s requirements .....

**Comment by abatishchev** [comment]
If they decide to stick with ancient version of the platform framework (in most cases - baseless), they'll have to stick with ancient version of all libraries (unfortunately).
