### ISSUE TITLE
Not seeing any releases

### ISSUE THREAD

**Issue by jaydeept** [jwt-dotnet/jwt#193]
I am not seeing any version in Release field(next to Branches). Actually Release field is required as per our organization norms if we want to use any NuGet package.

**Comment by abatishchev** [comment]
This is a small project and I'm the only active maintainer so never filled out the Releases tab.

However, here we have fully automated CI/CD pipeline using VSTS (aka Azure DevOps) which builds, runs tests and pushes packages to NuGet.org:

- Build: https://dev.azure.com/abatishchev/Jwt.Net/_build?definitionId=1
- Release: https://dev.azure.com/abatishchev/Jwt.Net/_release?definitionId=1

Would this work for you?

**Comment by jaydeept** [comment]
So actually in Releases tab, we get the release version for which we need to raise a request and zip of source code through which our organization scan through to make sure nothing has been mentioned that can stop us from using the package or license clearance.

**Comment by abatishchev** [comment]
Is this the only project from your dependencies who doesn't have proper releases? Can you provide an example what project does have, does what you want?

**Comment by jaydeept** [comment]
Mostly all the standard packages have the Releases tab. You can check any of Microsoft, for example: https://github.com/aspnet/AspNetCore . Another example for Eureka: https://github.com/xmartlabs/Eureka

**Comment by jaydeept** [comment]
I think this is the good link to refer: https://github.blog/2013-07-02-release-your-software/

**Comment by abatishchev** [comment]
Are you consuming nuget or source code? I believe 99.98% of the users or the library consume it from nuget.

So with all due respect I don't see much value in posting a zip with its source code under releases.

However, if there is a way to do that programmatically, from VSTS task or PowerShell script, and you volunteer to explore the options, I'd more than happy to add this to the release pipeline I'm using to publish nuget currently.

Like zip and push to GitHub. Should be trivial. Thoughts?

**Comment by jaydeept** [comment]
Personally I too believe it shouldn't be required if package is there but this is how our organization works and norm wise they need to scan through the code to make sure nothing hidden is there.
I think there is a way to automate Release stuff: https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by abatishchev** [comment]
The question is then how to plug it into the existing pipeline nicely.

**Comment by jaydeept** [comment]
I think as your current version is stable one, you can just publish one release rather than going through CI route as mentioned here: https://help.github.com/en/articles/creating-releases

**Comment by abatishchev** [comment]
It's relatively new and a bug can be found any time and a fix can be released any time. So I'd not discount that possibility. Repetitively doing manually what can be automated is not my motto :)
I'll take a look how VSTS integrates with GitHub. So can you and guide me on it.

**Comment by glennawatson** [comment]
If your using Azure DevOps to release, there is a task to generate release notes for a release.

It will just generate it from the commit history.

**Comment by abatishchev** [comment]
IF I'll grant you the permissions, would you be willing to reconfig it accordingly? Need help with both CI (see #196) and CD (this issue). Please!

**Comment by glennawatson** [comment]
Sure, I could do it similar to how we do it on the ReactiveUI project.

We tend to use a YAML based config.

**Comment by abatishchev** [comment]
Sure! Currently it uses PowerShell, as an artifact from the AppVeyor times. But we definitely should use YAML.
Please feel free to add ore changes to that PR. Or open another one, probably. Not sure how to grant you the permissions to the existing one.

**Comment by abatishchev** [comment]
Or ping me at abatishchev at gmail and I'll add you to the project on VSTS and you'll make the necessary changes from there. Either way works for me.

**Comment by abatishchev** [comment]
Here's [the release definition](https://abatishchev.visualstudio.com/Jwt.Net/_release?definitionId=1) currently used to push packages to NuGet.org. I already added another task to create GutHub releases. But I need help to make it working properly. Currently it does nothing other than outputs a warning:

>##[warning]Release will not be created as no tags could be found for the target commit. For more details check out the ‘Tag Source’ section in documentation: https://aka.ms/AA4f03a.

**Comment by glennawatson** [comment]
I can look tomorrow, my weekend.

**Comment by abatishchev** [comment]
Hey Glenn, any chance to help me on creating GitHub releases, please?

**Comment by talanc** [comment]
Hi @abatishchev 
I had a similar problem with Release Pipelines and the GitHub Release task. I kept on getting that same warning you had.
I solved it by setting 'Tag source' to 'User specified tag', and then 'Tag' to '$(Build.BuildNumber)'.

Here's the 'View YAML' output:
```
steps:
- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'github connection 1'
    tagSource: manual
    tag: '$(Build.BuildNumber)'
    title: 'Release $(Build.BuildNumber)'
    assets: '**/vlisp-profiler-installer.exe'
```

And here's how it looks in Releases: https://github.com/talanc/vlisp-profiler/releases

**Comment by abatishchev** [comment]
Thanks a lot, @talanc! I think I got it working, see https://github.com/jwt-dotnet/jwt/releases

**Comment by abatishchev** [comment]
The only issue a release is getting its name from ADO release what is current date, basically. I don't know how to extract the version from JWT.csproj. Any ideas?

**Comment by abatishchev** [comment]
Another issue is that I can't locate the nupkg file so doesn't attach it to the release.

**Comment by glennawatson** [comment]
A lot of projects I know use https://github.com/AArnott/Nerdbank.GitVersioning

Basically it injects the version information into the assembly, includes the git commit id, and automatically generates the version number from the last time the version configuration file was changed (the git height).

So in my azure-pipelines.yml I have before any build steps (see 

```yml
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  env:
    COREHOST_TRACE: 0
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1    

- script: nbgv cloud
  displayName: Set Version
  env:
    COREHOST_TRACE: 0
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1 
```

I also have a `version.json` file with the following contents, where version number you will increment for new major/minor versions and the patch number will be generated by the git height. Eg in the sample below, it will be 1.2.{number of commits since last change to the version json file}

```json
{
  "version": "1.2",
  "publicReleaseRefSpec": [
    "^refs/heads/master$", // we release out of master
    "^refs/heads/develop$", // we release out of develop
    "^refs/heads/rel/\\d+\\.\\d+\\.\\d+" // we also release branches starting with rel/N.N.N
  ],
  "nugetPackageVersion":{
    "semVer": 2
  },
  "cloudBuild": {
    "setVersionVariables": true,
    "buildNumber": {
      "enabled": false
    }
  }
}
```

The last step is you'll have to include the nuget package into your project I have in my Directory.build.props file:

```xml
  <ItemGroup>	
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.0.25" PrivateAssets="all" />	
  </ItemGroup>
```

see https://github.com/glennawatson/gitsmimesign for  sample.
```

**Comment by glennawatson** [comment]
In terms of showing the build number it will be under `azure devops -> pipelines -> release` edit your release pipeline, then go to `options` and enter the following in the "Release Format"

`v$(Build.BuildNumber).$(rev:r)`

**Comment by glennawatson** [comment]
For your last problem with the nupkg not being attached to the release.

In the GitHub Release Pipeline [here](https://abatishchev.visualstudio.com/OpenSource/_releaseDefinition?definitionId=2&_a=definition-tasks&environmentId=2) change the `GitHub Release` -> `Asset`s to `$(System.ArtifactsDirectory)\**\*.nupkg` the same as you do in your Nuget Push command.
