### ISSUE TITLE
Difference to Microsoft.AspNetCore.Authentication.JwtBearer

### ISSUE THREAD

**Issue by lonix1** [jwt-dotnet/jwt#194]
The ASP.NET Core templates use [Microsoft.AspNetCore.Authentication.JwtBearer](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer).

I was wondering how this library differs from it? Any extra features, etc.?

**Comment by abatishchev** [comment]
I'd rather try Microsoft's library first, since it's backed by the whole corporation that supports it. And for this library - it's just me alone.

**Comment by lonix1** [comment]
@abatishchev Haha that is the most straightforward honest answer, didn't expect it :laughing:

But you should have mentioned that you have a cool fluent interface, a nicer api in general, and over 2mil nuget downloads. So pretty cool. :+1:
