### ISSUE TITLE
Is it possible not to sign token but to fully encrypt?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [jwt-dotnet/jwt#201]
Hi!
I am searching a way to fully encode/decode tokens, not to sign.
Is it possible?

**Comment by abatishchev** [comment]
Hi! Can you please provide a code sample what you'd like to achieve?
P.S.
I speak Russian so if you know a place where we can chat live - we can do so.

**Comment by Dmitrij-Polyanin** [comment]
У меня есть Телеграм: @Okeanij

**Comment by Dmitrij-Polyanin** [comment]
Я имел ввиду не подписать токен, а вообще зашифровать, так что его не прочитать без расшифровки.
Как я знаю это называется JWE.
Для меня полезная функция, по причине большей защищённости.

**Comment by Dmitrij-Polyanin** [comment]
Я у себя уже так делаю через RijndaelManaged, но если есть хорошая библиотека, то перешёл бы на неё, так как родная .Net какая-то замороченная.
