### ISSUE TITLE
How to generate a secret?

### ISSUE THREAD

**Issue by weizhangxiaohan** [jwt-dotnet/jwt#215]
How to generate a secret? 

Is the length of the secret fixed?

**Comment by weizhangxiaohan** [comment]
In the examples there is a secret key like:
var secret = "GQDstcKsx0NHjPOuXOYg5MbeJ1XT0uFiwDVvVBrk";

Looks like this secret is in base64 format.
Can I use Guid.NewGuid() instead?

I don't know how I can get a secret like the secret in the example.

**Comment by abatishchev** [comment]
I don't think it's in bas64. I'm not sure where it's coming from, it was added in the 4th commit to this repo more than 5 years ago by prior maintainer. Maybe it's just a random string, maybe something else.
It *must be* a random string, GUID also work. I'm not an expert in cryptography, I would suggest additional reading.
And overall I would suggest using the asymmetric algorithm with a certificate aka PKI.

**Comment by weizhangxiaohan** [comment]
Thank you for your reply. It's very helpful.

**Comment by abatishchev** [comment]
You're welcome!
