### ISSUE TITLE
JWT gets decoded without secret key.

### ISSUE THREAD

**Issue by yogendra3236** [jwt-dotnet/jwt#216]
I am using Node JS with JWT to authenticate my protected end-points using secret-key. But, I was shocked when I came to know about http://calebb.net/ . Here, you can decode your JWT token, or you can also use npm dependency at https://www.npmjs.com/package/jwt-decode to decode it.

Why is it being decrypted without secret-key?

**Comment by abatishchev** [comment]
Any online JWT tool can decode JWT as it's just base64. What really gets _encoded_ is the signature. Which either tool won't be able to decode until you specify the _secret_.

**Comment by abatishchev** [comment]
Server, knowing the secret, can encode the JWT and then [compare (validate) the signature](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JwtDecoder.cs#L110), they must match. Otherwise server won't trust the client and the claims it provides within the token.

**Comment by yogendra3236** [comment]
I have been generating JWT token using secret key in Nodejs, but still when I'm using any such tool, it does easily decode my token. Moreover, you can also decode it manually via terminal with npm-decode. There is no need of any secret key to decode it.

**Comment by abatishchev** [comment]
What matter is the algorithm. Is it symmetrical asymmetrically?
And again what matters the most is the signature. Neither tool won't able to temper it. What server just do first is to verify the signature. If it doesn't math then the token is invalid.
