### ISSUE TITLE
Consider exposing JwtParts claims?

### ISSUE THREAD

**Issue by cdwiegand** [jwt-dotnet/jwt#236]
In order to allow apps to check the `sub ` and `iss` claims, as specified in [https://tools.ietf.org/html/draft-ietf-oauth-jwt-bcp-07#section-3.8](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bcp-07#section-3.8), I would encourage exposing variants of Decode() exposing the Payload as an IDictionary<string,object> so apps that call it can verify the claims as desired.

If 6.0 doesn't include it, I can probably write the code and submit a pull request, just haven't had time and wanted to make sure the idea got out there.

Alternatively, we could expose an Interface for validating claims, and allow setting that on the Decoder, which may be cleaner and keep with the architecture of the project.

Edited for clarity, used the wrong name for a part.

**Comment by cdwiegand** [comment]
Ugh, never mind, if I **think** sometimes, I realize I can already do this. It's been a long day, probably shouldn't be commenting on OS projects late at night.

**Comment by abatishchev** [comment]
No worries! Please come back with more ideas, I'm happy to accept contributions. Whatever would be useful for the users, I'm happy to see the libraries is being used.
