### ISSUE TITLE
Support for RSA512?

### ISSUE THREAD

**Issue by SuddenGunter** [jwt-dotnet/jwt#238]
One of my project requires jwt token signed with RSA512. 
AFAIK this library only supports RSA256. Is there are any info what should I do to implement RSA512?
I'll add a PR if it would work

**Comment by abatishchev** [comment]
Hi,
[RS256Algorithm](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/RS256Algorithm.cs) just accepts `X509Certificate2` which can have whatever strength of encryption. Correct if I'm wrong and please feel free to submit any changes that would this library suiting your need better.
