### ISSUE TITLE
Stuck trying to create an RS256 bearer token : unable to create an RS256Algorithm

### ISSUE THREAD

**Issue by PureKrome** [jwt-dotnet/jwt#239]
👋 G'Day!

Ok, I'm trying to create an RS256 token. When I do this, the `var algorithm = new RS256Algorithm(certificate);` throw an exception:

```
   System.ArgumentNullException : Value cannot be null.
   Parameter name: privateKey
```

This is because (I think) the [certificate doesn't have a private key](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/RS256Algorithm.cs#L44)?

This is the code I'm using to generate a my "encode" logic:

```
var certificateText = File.ReadAllText("Data\\PublicCertificateFromAuth0.txt");
var publicCertificate = Encoding.ASCII.GetBytes(certificateText);
var certificate = new X509Certificate2(publicCertificate);
 
var algorithm = new RS256Algorithm(certificate);
<the rest is snipped>
```

and the certificate text is taken from Auth0 .. here ..

![image](https://user-images.githubusercontent.com/899878/71576277-3da1b600-2b44-11ea-89c4-e732ff1e1dc0.png)

So then I thought "Ok, just add the client secret, for this Auth0 account. Surely that's the password for this certificate, right?"

```
var password = "auth0 client secret";
var certificate = new X509Certificate2(publicCertificate, password);
```

(and this is where I got the "client secret" from)...

![image](https://user-images.githubusercontent.com/899878/71576351-7b9eda00-2b44-11ea-9d21-7b119dc7487b.png)

But when I try that (above), the instance of the certificate has the private key as `null`, still.

![image](https://user-images.githubusercontent.com/899878/71576416-be60b200-2b44-11ea-930f-774e7618487f.png)

So .. I'm not really sure what's going on or what to do here.

SIDE NOTE: I'll try and submit some PR for some notes/readme update because it looks like RS256 is becoming the norm for these things these days. That said, it's mostly for decoding, not encoding.

**Comment by abatishchev** [comment]
If you don't have private key then construct RSA and pass it to the algorithm directly, don't attempt to construct a certificate first and then pass it to the algorithm.

Yes, I agree, asymmetric encryption is widely used while almost no one these days needs hashing.

**Comment by abatishchev** [comment]
See [RS256Algorithm.cs](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/RS256Algorithm.cs) for available ctors.

Would be great if it could submit a PR to add support for a certificate without private key.

**Comment by PureKrome** [comment]
NP - i'll get onto a PR right now. I'm still not 100% understanding what's going so lets see what I come up with 😊

**Comment by PureKrome** [comment]
> 

isn't this [already occurring, here](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/RS256Algorithm.cs#L33):

```
public RS256Algorithm(RSA publicKey)
        {
            _publicKey = publicKey ?? throw new ArgumentNullException(nameof(publicKey));
            _privateKey = null;
        }
```

**Comment by abatishchev** [comment]
Right now you can pass either public key only, or public and private, or certificate which must contain both.
If you're passing only public key and it's null then you're surely get the said exception.

**Comment by PureKrome** [comment]
(emphasis mine)
> If you're passing only **public key** and it's null then you're surely get the said exception.

I'm passing the certificate (which is not null) but it has no _private key_. That is throwing the exception .. that the certificate has no private key.

So are you saying that it should be possible that I could pass in a certificate without a private key?

( Again, I'm not even sure if this is correct though. )

**Comment by abatishchev** [comment]
Yes, construct RSA from public key. Don't construct "intermediate" certificate. Pass public key to algorithm directly.

And/or submit a PR that won't throw exception when certificate doesn't contain private key. Continue constructing certificate.

I would start with the former ;)

**Comment by abatishchev** [comment]
(no worries, happy to help, my understanding in this area came much later than first lines of codes that were doing _something_)

**Comment by PureKrome** [comment]
Okay ... i _THINK_ I understand what you are suggesting now. I was slightly confused but maybe I understand what you are saying now.

> Yes, construct RSA from public key. Don't construct "intermediate" certificate. Pass public key to algorithm directly.

Okay ... this suggestion means I can do this right now, with NO PR required.

e.g.

```
[TestMethod]
public void Ctor_Should_Not_Throw_Exception_When_PublicKeyHasNoPrivateKey()
{
    // Construct RSA from public key.
    var publicKey = _fixture.Create<RSACryptoServiceProvider>();

    // Pass public key to algorithm directly.
    var algorithm = new RS256Algorithm(publicKey);

    algorithm.Should().NotBeNull();
}
```

>> And/or submit a PR that won't throw exception when certificate doesn't contain private key. Continue constructing certificate.

And this is some new PR to allow a certificate to be passed in _which has no private key_.

So I did this with #240 

If the PR sucks, all good with closing it. etc.

Interested in your thoughts, etc.

**Comment by abatishchev** [comment]
Try [6.0.0-beta3](https://www.nuget.org/packages/JWT/6.0.0-beta3).

**Comment by abatishchev** [comment]
Let me know if I should rather reopen it.
