### ISSUE TITLE
From where should I start? Is there a tutorial?

### ISSUE THREAD

**Issue by anastina** [jwt-dotnet/jwt#241]
Hi,
Is there a tutorial explaining your library? I am really lost!

Thanks!

**Comment by abatishchev** [comment]
Hi!
Depends what you're looking for - encoding (writing) token or decoding (reading) one?
I would start with the readme and see whether it's enough or still missing something. I'm bad at writing good documentation (help welcome) but it should cover basic scenarios.

**Comment by anastina** [comment]
Hi Alexander,

Thanks for your reply!

I am depending on the following project to write my backend services using WCF.

https://github.com/dotnetjunkie/solidservices

Any help, please? Do you accept remote help (Online Session)? I really appreciate that!

**Comment by anastina** [comment]
The author of the SOLID services, Mr. Steven, reply to me with this,

![image](https://user-images.githubusercontent.com/32333489/71631023-0b10bf80-2c0f-11ea-8059-fcc9245daffe.png)

**Comment by abatishchev** [comment]
Sorry, I'm on a plane to 10-day vacation :)

I'd suggest to try to combine Step #9 from https://www.c-sharpcorner.com/article/wcf-service-with-jwt-token/ with the code in the readme for this library, this way you'll get proper JWT based auth.
