### ISSUE TITLE
How is SourceLinkEnabled set to true?

### ISSUE THREAD

**Issue by PureKrome** [jwt-dotnet/jwt#242]
I noticed in the JWT.csproj that source link is setup ONLY if `SourceLinkEnabled` is true.

```
  <ItemGroup Condition="'$(SourceLinkEnabled)' != 'false'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>
```

How is this `true`? 

Checking the [NuGet website for this package](https://www.nuget.org/packages/JWT/6.0.0-beta3), it only lists the package and no symbols. ([Here's a sample nuget library](https://www.nuget.org/packages/WorldDomination.HttpClient.Helpers/) with both packages and symbols)

**Comment by abatishchev** [comment]
It might be a bug or maybe not.
I see it's value is `''` (empty string) per https://github.com/jwt-dotnet/jwt/blob/04030c34ac33b700b0e9317730079be203f85eb0/src/Directory.Build.props#L9 what is `!= 'false'` so hypothetically it should work.

Can you help to get it fixed?

**Comment by abatishchev** [comment]
It's a bug introduced by myself. I'll fix it.
