### ISSUE TITLE
JwtBuilder.AddClaim using ClaimName produces invalid JSON for ClaimName.ExpirationTime

### ISSUE THREAD

**Issue by jasondown** [jwt-dotnet/jwt#248]
When using the JwtBuilder.AddClaim method and passing in ClaimName.ExpirationDate, you are forced to pass a string value in (there is no overload for passing in object like there is with passing in "exp" as the claim name via the AddClaim(string, object) method). This causes the expiration date to be enclosed in quotes in the payload which is invalid since the exp claim must be numeric.

```c#
var exp = new DateTimeOffset(DateTime.UtcNow.AddMinutes(JwtLifetime)).ToUnixTimeSeconds();

var validJwtToken = 
     new JwtBuilder()
             .WithAlogorithm(new HMACSHA256Algorithm())
             .WithSecret("mySecret12345678")
             .AddClaim("exp", exp)  //<-------- This works
             .AddClaim(ClaimName.Issuer, "jason")
             .AddCLaim(ClaimName.Audience, "jwt-dotnet")
             .Build();

var invalidJwtToken = 
     new JwtBuilder()
             .WithAlogorithm(new HMACSHA256Algorithm())
             .WithSecret("mySecret12345678")
             .AddClaim(ClaimName.ExpirationTime, exp.ToString())  //<-------- Must use string. Fails validation
             .AddClaim(ClaimName.Issuer, "jason")
             .AddCLaim(ClaimName.Audience, "jwt-dotnet")
             .Build();
```

Here is the valid jwt (going through https://jwt.io):
![image](https://user-images.githubusercontent.com/1128859/73098968-753c1d80-3eb8-11ea-834b-d4dd70fb4867.png)

Here is the invalid jwt (notice the quotes that are not present in the valid screenshot above):
![image](https://user-images.githubusercontent.com/1128859/73099098-be8c6d00-3eb8-11ea-91f6-b93f84b3e395.png)

**Comment by abatishchev** [comment]
Hi,
I'm not 100% sure what's the issue here. I mean why you _have_ to use ToString() when calling method `AddClaim(string, object)`.

However I've made a number of changes in #249, please take a look if that will address your issue.

**Comment by jasondown** [comment]
I'll have a look at #249 this weekend, thanks.

As for the issue, it's the overload of AddClaim that takes a ClaimName as the first parameter (not a string, but the enum value). The second parameter must be a string, rather than an object. I'd rather use the ClaimName overload rather than the (string, object) overload because it is compile time safe instead of relying on hard-coded strings (ex, using ClaimName.ExpirationTime vs "exp"). Ideally there would also be an overload like this: AddClaim(ClaimName, object) (or maybe even a generic version).

Thanks again Alexander (especially for the quick response 😃).

**Comment by abatishchev** [comment]
Thanks for reporting the issue and coming back to discuss it, I'm happy to fix it as soon as I can.

Correct me if I'm wrong but as I understand the value to be properly serialized (int as int as not as strong) the second parameter should be rather object. Before the code was calling `ToString()` and now it won't. What in my kind should resolve the issue.

As of a generic overload `AddClaim<T>(ClaimName, T)`, it sounds like a great idea but unfortunately won't make much of the difference over `object` as it'll be added to `Dictionary<string, object>` anyway.

**Comment by jasondown** [comment]
Yes, the value object (second parameter) needs to be serialized as an int, so having an object as the second parameter should work, in theory.

Good point about the generic overload. I didn't look too deeply into that part of the code yet.

**Comment by abatishchev** [comment]
I've made all changes, fixed the gated build. Added generic overloads too, just in case, for the future reference.

Please take a look, confirm that would work for you. You can download the new NuGet package from [here ](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=381&view=artifacts&type=publishedArtifacts)before it's pushed to NuGet.org.

**Comment by jasondown** [comment]
Awesome Alexander! I'll give a whirl Monday morning (EST) and let you know. Thanks!

**Comment by jasondown** [comment]
I tried it out this morning and it is working perfectly. Thanks again Alexander. Any idea when this will be officially pushed to nuget (btw, love that you're using Azure DevOps)?

**Comment by abatishchev** [comment]
Within 15 minutes
