### ISSUE TITLE
Is dotnet framework 4.8 supported

### ISSUE THREAD

**Issue by anastina** [jwt-dotnet/jwt#250]
Hi,

Is dotnet framework 4.8 supported?

**Comment by abatishchev** [comment]
Hi, as of #235 it is.

**Comment by abatishchev** [comment]
However, you would need to use at least version 6.x which currently in pre-release but still stable enough to be used.

**Comment by abatishchev** [comment]
Hope this helped. Please let me know if you have more questions or concerns.
