### ISSUE TITLE
ES256 support

### ISSUE THREAD

**Issue by nmg196** [jwt-dotnet/jwt#251]
Hi,
I need to generate a ES256 signed JWT but I can't see that algorithm available in this project.  Is it possible or do I need to use another library?

If it is supported, can I get the 'secret' from a .p12 private key? 

Thanks,
Nick

**Comment by abatishchev** [comment]
Hi!
Please see my response in #238. Let me know if it's true indeed and makes sense.
You should be able to construct an RSA object from your .p12 and pass it to the existing asymmetric algorithm.
