### ISSUE TITLE
'JwtDecoder' does not contain a constructor that takes 3 arguments 

### ISSUE THREAD

**Issue by TwitchBronBron** [jwt-dotnet/jwt#254]
I tried using the decoding example from the readme [here](https://github.com/jwt-dotnet/jwt/tree/f20a3e5b550f8c093ba67d2bfab74dc2dfe8da3d#parsing-decoding-and-verifying-token) but I'm getting the following error message: 

>'JwtDecoder' does not contain a constructor that takes 3 arguments [Business]

![image](https://user-images.githubusercontent.com/2544493/75189348-fb4bbe00-571b-11ea-8252-fe151b16ed36.png)

Here's the signature it's trying to match on:
![image](https://user-images.githubusercontent.com/2544493/75189461-39e17880-571c-11ea-84e4-e7a24af02b5e.png)

Here's my csproj file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Dapper" Version="2.0.30" />
    <PackageReference Include="JWT" Version="6.1.0" />
    <PackageReference Include="MySqlConnector" Version="0.61.0" />
    <PackageReference Include="System.Text.Json" Version="4.7.1" />
  </ItemGroup>

</Project>
```

Any ideas what's wrong? I'm assuming the docs are out of date?

**Comment by abatishchev** [comment]
Oops, sorry about this. Yes, the docs are outdated. The code used to use pass `HMACSHAAlgorithmFactory` by default but not it doesn't, you need to specify which algorithm to use.
Here's the change: https://github.com/jwt-dotnet/jwt/commit/c60690d2b125f08a42f2cc11d87315cd7167258a#diff-8c360b757f0e07617764f902795d127a

Can you try please and let me know if it worked? Then we can update the doc.

**Comment by TwitchBronBron** [comment]
Yep that did the trick!

![image](https://user-images.githubusercontent.com/2544493/75194356-f7249e00-5725-11ea-9de5-58434aae1050.png)

**Comment by abatishchev** [comment]
Cool! Could you please submit a quick update to the do?
