### ISSUE TITLE
Error signing with certificate

### ISSUE THREAD

**Issue by stefansolid** [jwt-dotnet/jwt#256]
When using

```c#
var cert = new X509Certificate2("c:\\temp\\client.pfx", "<pwd>");

.WithAlgorithm(new RS256Algorithm(cert));
```

I get this error:

>You can't provide more than one secret to use for encoding.   at JWT.Builder.JwtBuilder.EnsureCanEncode()

I cannot understand what the problem is. Wrong certificate?

It works perfect using a static password, with the following:

```c#
.WithAlgorithm(new HMACSHA256Algorithm())
.WithSecret(Program.Configuration.TokenSecret)
```

**Comment by abatishchev** [comment]
Hi!
Looks like a recently introduced bug, sorry about this.
To make sure, can you please post full code how construct intiial the `buider`?

**Comment by stefansolid** [comment]
Hi, 

Of course!

Here is all code that is not working:

            using var cert = new X509Certificate2("c:\\temp\\client.pfx", "<pwd>");

            // Create the token!
            var token = new JwtBuilder()
                  .WithAlgorithm( new RS256Algorithm(cert))
//                  .WithAlgorithm(new HMACSHA256Algorithm())
//                  .WithSecret(Program.Configuration.TokenSecret)
                  .AddClaim("exp", DateTimeOffset.UtcNow.AddMinutes(Program.Configuration.TokenLifetimeMinutes).ToUnixTimeSeconds())
                  .AddClaim("name", systemUser.Name)
                  .AddClaim("data", data ?? string.Empty)
                  .AddClaim("tid", tid)
                  .AddClaim("iss", Dns.GetHostName())
                  .Encode();

If i remove comments and remove  RS256-line it works fine

**Comment by abatishchev** [comment]
Sorry for the delay, I'm looking into this.

**Comment by abatishchev** [comment]
Let's continue in the PR.
