### ISSUE TITLE
JwtBase64UrlEncoder perf improvements

### ISSUE THREAD

**Issue by gfoidl** [jwt-dotnet/jwt#257]
In [gfoidl.Base64](https://www.nuget.org/packages/gfoidl.Base64/) I created a library with _base64Url_ support for direct encoding / decoding with usage of simd-instruction (and software-fallback).
It's quite a lot faster (with SIMD x2 ... x20 depeding on size, for .NET Standard x2 ... x6) with less allocations [[1]](https://github.com/gfoidl/Base64/blob/e0dbaddb9eb44462dabf2e29b3ab7899c613ef3e/perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.md), [[2]](https://github.com/gfoidl/Base64/blob/e0dbaddb9eb44462dabf2e29b3ab7899c613ef3e/perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.md).

Is there any interest in using this here?
The change here is rather trivial, as it's just a forwarding in https://github.com/jwt-dotnet/jwt/blob/1737f8929340f02bb10eee720f4fa72ce2477a46/src/JWT/JwtBase64UrlEncoder.cs#L8 to `Base64.Url`-methods.

I can submit a PR in case of interest.

**Comment by abatishchev** [comment]
Hi, and thanks for reaching out and proposing such an improvement!
I'd love to ship a satellite (extension) package out of this repo that would ship the interface implementation using your library.
Another option would be to ship your lib's source code as a NuGet package and embed it into this lon. So it'd be the build time dependency.
What I would not do is to add yours as a runtime, NuGet dependency of this one. Historically it had no external dependencies (except Json.Net) what I think is a good, valued by the consumers thing.

**Comment by abatishchev** [comment]
(sorry, pressed wrong button from the mobile)

**Comment by gfoidl** [comment]
> Another option would be to ship your lib's source code as a NuGet package and embed it into this lon

I know the option of source-packages, but I believe this can become clumsy with wiring up, managing more packages and so on.

An option inspired by this could be git-submodules. So the project could be referenced at build-time, and the (runtime-) dependency is shipped with this product.

> I'd love to ship a satellite (extension) package out of this repo that would ship the interface implementation using your library.

This seems the best and cleanest option for me. Should we go with this one?

> Historically it had no external dependencies (except Json.Net) 

👍

**Comment by abatishchev** [comment]
The Git submodule approach is also doable, if only it wasn't so complicated (in general). Let's do a satellite package and then if they're will be a positive feedback and/or demand - we'll reconsider embedding into the source code.

May I ask to start a PR and I'll pick it up and bring to completion.

**Comment by gfoidl** [comment]
Sounds good. I'll start a PR soon.

**Comment by abatishchev** [comment]
@gfoidl gentle ping on this

**Comment by gfoidl** [comment]
I did not forget this, but unfortunately didn't find time to do this so far 😢

**Comment by abatishchev** [comment]
@gfoidl ping on this great idea ;)

**Comment by gfoidl** [comment]
> What I would not do is to add yours as a runtime, NuGet dependency of this one

Does this still hold? It's the most straight forwarded solution, as the current implementation just needs to forward to the simd-based implementation.

> Let's do a satellite package

If you'd like to go this route, please outline this a bit more as I don't understand how this may look.

PS: sorry that I didn't make any progress here...

**Comment by abatishchev** [comment]
So there are two options:

1. Add a reference, hence a dependency on, to the main package Her
2. Create what I called a satellite package (not sure what's the right terminology), les say Jwt.Base64.gfoidl or gfoidl.Base64.Jwt, and advertise it on the main page.

I'd propose this: do no. 2 first, then if the resulting package will get traction (popularity and downloads) then to do no. 1.

What you think?

**Comment by gfoidl** [comment]
From a community point of view option 2 has the drawback that there are two packages doing the same, that will eventually get merged. So which one to pick? 
This option will / can cause confusion for potential users. We should make it as simple as possible for them, to be attractive with one superior package that can be used.

Implementation-wise for option 2 I see a layering problem. What to put where without re-creating you fabulous package?

From the ReadMe
```c#
IJwtAlgorithm algorithm = new HMACSHA256Algorithm(); // symmetric
IJsonSerializer serializer = new JsonNetSerializer();
IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);
```
could then look like
```c#
IJwtAlgorithm algorithm = new HMACSHA256Algorithm(); // symmetric
IJsonSerializer serializer = new JsonNetSerializer();
IBase64UrlEncoder urlEncoder = new JwtSimdBase64UrlEncoder();   // or any better name
IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);
```
This could be done with a separate package that contains the simd-based implementation for `IBase64UrlEncoder`, but then again from a community point of view I would ask myself

* Why do I have to install another package?
* Can't this be included if it's advertised to be faster?
* I don't like to read all of ReadMes, so just pick the first code-snippets that catches my eye and hope that it goes well...

I'm not really convinced that this option will provide a benefit for the community.

Going back to the option to embed the code. This has the effort to put the code + tests, etc. into your package.
Going with the package-reference one could use the already tested (incl. fuzzy tests) library by the price of having a dependency.

I'd go with option 1 from your last comment. A lot of projects are based on dependencies, and I don't see a problem here.

**Comment by abatishchev** [comment]
Let me close the issue due to lack of feedback or requests from other uses
