### ISSUE TITLE
JwtDecoder throws error if no Algorithm/Factory specified even though it's not needed

### ISSUE THREAD

**Issue by richardhauer** [jwt-dotnet/jwt#263]
I need to decode a token in order to get a keyid, so that I can go download the public key, so that I can specify an algorithm.  Bit of a chicken/egg problem.

Looking into the JwtDecoder I can see that the Algorithm is only actually needed when verifying/validating, so the builder needn't throw an error where the Alg/Factory is not specified, particularly if `DoNotVerifySignature()` has been called.

To make this work I have had to use a Mock `IJwtAlgorithm` :/

**Comment by abatishchev** [comment]
Hi!
I'm sorry, I got the whole thing messed up with the attempt to add to JwtBuilder the support of assymetric algorithm. It's so different and doesn't play out well with the rest of the codebase :(
Do you know how to fix it? Can you submit a PR, I'll polish and publish asap.
Meanwhile please downgrade to an earlier 6.0.x version and let me know if it works for you.

**Comment by abatishchev** [comment]
Wait, I see that [CanDecode()](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Builder/JwtBuilder.cs#L326) already accounts for `_verify` so if you call `DoNotVerifySignature()` it would be false and should ignore the absence of algorithm/algorithm factory.

Can you point me to the line (from the exception stack trace)? Looks like it'd be an easy fix.

**Comment by abatishchev** [comment]
I think I found where you're getting exception. [Here](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Builder/JwtBuilder.cs#L269]?

**Comment by richardhauer** [comment]
Yeah that’s it


Richard Hauer
CTO

PING Works
1-7 Albion Place, Sydney NSW 2000
p: +61 2 9321 1551<tel:+61%202%209321%201551> | www.ping-works.com.au<https://www.ping-works.com.au>
d: +61 2 9321 1556<tel:+61%202%209321%201556> | m: +61 414 189 170<tel:+61%20414%20189%20170>
Download a vCard<https://vcard.ping-works.com.au/api/GenerateVCF?name=richard.hauer>

________________________________

**Comment by richardhauer** [comment]
I created a NullAlgorithm with does the job for now, but a new problem is that Decode does not surface Header claims, so there’s no way to access the `kid` header claim.


Richard Hauer
CTO

PING Works
1-7 Albion Place, Sydney NSW 2000
p: +61 2 9321 1551<tel:+61%202%209321%201551> | www.ping-works.com.au<https://www.ping-works.com.au>
d: +61 2 9321 1556<tel:+61%202%209321%201556> | m: +61 414 189 170<tel:+61%20414%20189%20170>
Download a vCard<https://vcard.ping-works.com.au/api/GenerateVCF?name=richard.hauer>

________________________________

**Comment by abatishchev** [comment]
Tell me this - which overload of `Decode()` you're using? To make sure I have the right scenario in mind.

**Comment by abatishchev** [comment]
So you're using `Decode(string)` which indeed doesn't surface the header, correct?

**Comment by abatishchev** [comment]
To surface the header I need little more time, can for it tomorrow.

Meanwhile please test a package from the latest builds from the PR. Does if resolve any of the issues?

I can unseal `JwtDecoder` and make some of the private helpers `protected` so you could inherit and roll your own version? Then contribute back and I'll incorporate into the interface and publish ad `7.0.0`. Tell me if that'll work / which methods would it need?

**Comment by richardhauer** [comment]
Yes my process is to do:

    new JwtBuilder().WithAlgorithm( new NullAlgorithm() ).DoNotVerifySignature().Decode( token );

The idea is to get the claims and find the `kid` then go get the public key I need to validate the signature.

**Comment by richardhauer** [comment]
I am deep in some code at the moment so can't really divert to workaround this at the moment; I thought I could simply `Base64Decode()` the header from a `new JwtParts().Header` and then `JsonConvert` to a `dynamic`.  It's the direct path!  But having to do all this stuff by hand kinda obviates the need to use the Jwt library in the first place.  I think it's pretty close to what I need so happy to wait on a patch.

**Comment by abatishchev** [comment]
What would be a good name for method which decided the whole token and returns it? `DecodeToken()`?

**Comment by richardhauer** [comment]
Changing the method name is a breaking change - you can preserve the current behaviour and add the new feature with an optional method argument defaulted to off.

**Comment by abatishchev** [comment]
I was thinking to add a new method `DecodeToken()` or `DecodeFullToken()` which would decode and return the whole token, the payload and the header.

**Comment by richardhauer** [comment]
Either way; I think from a discoverability perspective you create confusion between `Decode()` and `DecodeToken()` because it's not obvious what the difference is.  If you have to add a new method I suggest `DecodeHeader()` to just return claims from the header.

**Comment by abatishchev** [comment]
Right, that's what I'll do, add `DecodeHeader`

**Comment by richardhauer** [comment]
wanna see ugly... don't judge me!

    return JsonConvert.DeserializeObject<IDictionary<string, object>>( builder.Decode( jwt ) )
    		.Concat(
                   JsonConvert.DeserializeObject<IDictionary<string, object>>(
                        Encoding.UTF8.GetString( 
                           new JwtBase64UrlEncoder().Decode( 
                                new JwtParts( jwt ).Header 
                           )
                        )
                    )
                 )
                .ToDictionary( kvp => kvp.Key, kvp => kvp.Value );

**Comment by abatishchev** [comment]
Let me move the discussion to the PR.
