### ISSUE TITLE
NRE when decoding in 7.0 Beta

### ISSUE THREAD

**Issue by richardhauer** [jwt-dotnet/jwt#266]
Trying out the new beta - thanks for the quick updates - but got a new bug.

So I have a public key exported to XML, that is being imported like this:

    var cert = new RSACryptoServiceProvider();
    cert.FromXmlString( xml );

Then I go to validate a token like this:

    new JwtBuilder()
        .WithAlgorithm( new RS256Algorithm( cert ) )
        .MustVerifySignature()
        .Decode<IDictionary<string,object>>( token );

In this case the `JwtBuilder::Decode<T>()` calls into the `_decoder.DecodeToObject<T>( token, _secrets, _verify )` but the `_secrets` value is null at this point.  This `null` is eventually passed into the `JwtDecoder::Validate( JwtParts, params byte[][] )` method, which has the following line near the end:

    string[] decodedSignatures = (from key in keys
        select alg.Sign(key, bytesToSign) into sd
        select Convert.ToBase64String(sd)).ToArray();

That would be OK if keys weren't null, but as we know, it is at this point.
I really need to get this code out tomorrow, so hoping you can whip up a quick fix here, or I'll need to fork.

**Comment by richardhauer** [comment]
The use-case here is that the Jwt is coming from a commercial IdP system (Azure AD B2C) and in order to validate the token I need to first get the JWK URL from the OIDC config, then get the public key from the published JWK, which only provides a modulus and exponent in B64 (let me know if you'd like an example).

I feel like this is a pretty common thing to need to do, right.

**Comment by abatishchev** [comment]
Let me explain.
Remember your another issue still open? To rewrite the validation subsystem in a way that supports asymmetric certificates? I tried but then rolled back and unlisted the package (6.1.3). I'll come back to it this weekend.
Meanwhile, when you do have to verify the signature, please add `WithSecret(bytes of public key)` and the old validation subsystem will lick off and the job. Would it be possible in your scenario?

**Comment by richardhauer** [comment]
Ah ok;

When you say "bytes of public key", which bytes are we talking about?
I have an `RSA` that was created from the n/e values provided in the JWK.
I can get `RSA::ExportRSAPublicKey()` which I think returns the bytes in PKCS#1 - is that going to work?

**Comment by abatishchev** [comment]
Let me explain.
Remember your another issue still open? To rewrite the validation subsystem in a way that supports asymmetric certificates? I tried but then rolled back and unlisted the package (6.1.3). I'll come back to it this weekend.

Meanwhile, when you do have to verify the signature, you need to call `WithSecret(bytes of private key)` so the old validation subsystem would kick off and do the job. Would it be possible in your scenario?

**Comment by richardhauer** [comment]
private key I don't have

**Comment by abatishchev** [comment]
Sorry, it's morning on the West Coast :) It's the private key, not the public. And that's the problem right now I must address asap.
You don't have it, correct?

**Comment by abatishchev** [comment]
Right, you don't have. I'll work on this this morning, let me grab a coffee first.

**Comment by richardhauer** [comment]
This currently works for me though:

    var enc = new JwtBase64UrlEncoder();

    var cert = RSA.Create(
                        new RSAParameters { Exponent = enc.Decode( e ), Modulus = enc.Decode( n ) }
                    );
    var jwt = new JwtParts( token );
    var algo = new RS256Algorithm( cert );
    
    var isMatch = algo.Verify(
        Encoding.UTF8.GetBytes( $"{jwt.Header}.{jwt.Payload}" ),
        enc.Decode( jwt.Signature )
    );

    Assert.AreEqual( true, isMatch );

**Comment by abatishchev** [comment]
Means you're verifying yourself and used builder without the verification, correct? It's good to hear at least you're not blocked. I apologize for the inconvenience and truly appreciate your continued support and use of this library!

**Comment by richardhauer** [comment]
Yeah I'm using the builder unverified (and getting the KeyId now too - thanks).
No worries at all - you got me 99% of the way!

**Comment by abatishchev** [comment]
@richardhauer please try [7.0.0-beta2](https://www.nuget.org/packages/JWT/7.0.0-beta2) and let me know if it works for you.

**Comment by richardhauer** [comment]
That's working now, thanks.

**Comment by abatishchev** [comment]
Awesome! I'll promote to a release / drop the beta suffix in a week, if there won't be any new issues reported. Hopefully! Thanks again for your help.

**Comment by richardhauer** [comment]
Thanks for the library!
I have run into a little problem related to my use-case that isn't an issue for the library, but might be worth consideration.

I need a delegate that can receive unverified claims during the call to the algorithm factory.  Something like `.WithAlgorithmFactory()` but an overload that includes unverified claims, specifically the issuer.

In my case I need to resolve JWTs generated by more than one system, so I don't know the RSAParameters in advance - I need the Issuer so I can get the WellKnownConfiguration, so I can get the JwkUrl, which I then cache.  I have an `IAlgorithmResolver::GetAlgothirm( string issuer, string keyId )` for this purpose but I can't wire that into the `JwtBuilder` as far as I can see.  The implementation then caches the RSAParams against the `$"{Issuer}/{KeyId}"` for 24hrs for performance.

So atm I still have to create 3 Builders (I think) to do the job, but it is working nonetheless.

Maybe an idea for v8

**Comment by abatishchev** [comment]
I think I understand what you're looking for. Right now headed dictates (via the algorithm factory) how to attempt to generate the signature. But you'd like to have another factory which would accept the payload (where from you'd get the necessary claims, such as the issue)?

**Comment by abatishchev** [comment]
Can you please open another issue for this idea and just copy/paste your last comment there?
