### ISSUE TITLE
Need an AlgorithmFactory delegate that receives some header/body claims as arguments

### ISSUE THREAD

**Issue by richardhauer** [jwt-dotnet/jwt#268]
I need a delegate that can receive unverified claims during the call to the algorithm factory. Something like .WithAlgorithmFactory() but an overload that includes unverified claims, specifically the `iss` from the body, and the `keyId` and the `typ` from the header.

In my case I need to resolve JWTs generated by more than one system, so I don't know the RSAParameters in advance - I need the `iss` so I can get the retieve the WellKnownConfiguration, so I can get the JwkUrl, which I then cache. The Jwk has RSAParameters (e/n) that are matched to the `keyId` so I can dynamically validate JWTs as long as I know where to go to get the WellKnownConfiguration, based on the Issuer.

For this I have an IRsaResolver::GetRsa( string issuer, string keyId ) but I can't wire that into the JwtBuilder as far as I can see. My implementation then caches the RSAParameters against the $"{Issuer}/{KeyId}" for 24hrs for performance.  

For me these are always RSA so the `typ` claim isn't needed, but a more generic implementation might have to account for non-RSA signatures and the JWT does advertise the correct method to use, so it might as well be included in the argument list.

Maybe an idea for v8

**Comment by abatishchev** [comment]
@richardhauer please try 7.0.0-beta3 from [this build](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=452&view=artifacts&type=publishedArtifacts).

I've changed `IAlgorithmFactory` so it now accepts `JwtDecoderContext` which holds raw JWT, deserialized header and decoded (from base64) payload. You can use the latter to deserialize into a dictionary or strongly-typed class and read whatever claim you'd like.

Please give me it a try.

**Comment by abatishchev** [comment]
Correction: from [this build](https://abatishchev.visualstudio.com/OpenSource/_build/results?buildId=453&view=artifacts&type=publishedArtifacts).
