### ISSUE TITLE
Add .NETFramework 4.5 dependencies for nuget package

### ISSUE THREAD

**Issue by antkon** [jwt-dotnet/jwt#272]
Can't install nuget package to project with target .NETFramework 4.5

**Comment by abatishchev** [comment]
Hi,
Which version are you using?
The support for .NET less than 4.6 was dropped starting version 3.0.2. back in 2017. It's not supported by Microsoft thus is insecure among other issues.
However, the support was reintroduced in 7.1.0-beta1.

**Comment by abatishchev** [comment]
@antkon ping.

**Comment by antkon** [comment]
> However, the support was reintroduced in 7.1.0-beta1.
thx
