### ISSUE TITLE
Fluent builder API decoding is missing initialization

### ISSUE THREAD

**Issue by Dehalion** [jwt-dotnet/jwt#273]
The README example for the fluent builder API fails since I updated to version 6.1.4 NuGet.

```csharp
var json = new JwtBuilder()
        .WithSecret(secret)
        .MustVerifySignature()
        .Decode(token); 
```
fails with the Exception message

> Can't decode a token. Check if you have call all of the following methods:
> -WithSerializer
> -WithValidator
> -WithUrlEncoder.

What's worse: none of these methods are actually the solution to the problem, because what's actually missing is the algorithm, which is not initialized to a default.

The actual solution would thus be adding the line:
```csharp
    .WithAlgorithm(new HMACSHA256Algorithm())
```

To resolve this issue one could update the examples in the README file. Or better yet, initialize the algorithm to a default to make the current examples work again.

**Comment by abatishchev** [comment]
Hi! Thanks for bringing this up.

I intentionally removed the default algorithm because it's hard to me to say what users actually need/use: whether it's the symmetric or asymmetric.

I'll update the readme to add `.WithAlgorithm(algorithm)`. Sounds good?

**Comment by pagefault** [comment]
Hi,
I just ran into this problem as well because I was missing the WithAlgorithm. The error that gets thrown still only says:

-WithSerializer
-WithValidator
-WithUrlEncoder.

I think you should add WithAlgorithm to that error message. Without this issue from google results I wouldn't have solved this so easily.

**Comment by abatishchev** [comment]
@pagefault can you please open a new issue and post there the initial version of your code that didn't work and then how you've fixed it? thanks!
