### ISSUE TITLE
Strange product version 

### ISSUE THREAD

**Issue by stefanstranger** [jwt-dotnet/jwt#279]
After downloading the latest jwt nuget package version (7.1.0) I noticed a strange product version.

After checking my previous version had the same strange product version.

>7.1.0+f76018c9f0e68e74220052c84f108656d7447372

    get-childitem -Path JWT.7.1.0\lib\net46\JWT.dll | ` 
    select-object -ExpandProperty VersionInfo | `
    fl *

Is this the correct way to display a productversion property?

**Comment by abatishchev** [comment]
Hi,
Can you explain little further what's strange there? Do you mean the string after the version itself? I think it's a strong name public key. It was reintroduced recently, in 7.0.0.

**Comment by abatishchev** [comment]
You can see more details here: https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JWT.csproj#L21
