### ISSUE TITLE
Secret type changed for Encode method

### ISSUE THREAD

**Issue by stefanstranger** [jwt-dotnet/jwt#280]
Did the type changed from string to byte for the Secret property for the Encode method?

![image](https://user-images.githubusercontent.com/2125385/81498106-4b6e0180-92c3-11ea-91c8-2685adc03797.png)

In the previous version I was able to use a string as input for the secret property of the Encode method.

Now I need to change the string to byte before I can encode.

```PowerShell
$Algorithm = [JWT.Algorithms.HMACSHA256Algorithm]::new()
$Serializer = [JWT.Serializers.JsonNetSerializer]::new()
$UrlEncoder = [JWT.JwtBase64UrlEncoder]::new()
$Encoder = [JWT.JwtEncoder]::new($Algorithm, $Serializer, $UrlEncoder)


$PayLoad = @{'FirstName' = 'Stefan'; 'LastName' = 'Stranger'; 'Demo' = 'Encode Access Token'; 'exp' = '1393286893'; 'iat' = '1393268893'}

$Headers = @{
    'foo' = 'bar'
}

$Secret = 'qwerty'
$extraHeaders = [Collections.Generic.Dictionary[string,object]]::new()
$Headers.GetEnumerator() |ForEach-Object {$extraHeaders.Add(([string]$_.Key),$_.Value)}
$Encoder.Encode($extraHeaders, $PayLoad, [system.Text.Encoding]::UTF8.GetBytes($Secret))
```

**Comment by abatishchev** [comment]
Oh, I think I know what happened. I cleaned up the interface and move some overloads to extension methods. C# compiler picks up that transparently but in PowerShell that might not be the case, sorry.

**Comment by abatishchev** [comment]
See here https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/IJwtEncoder.cs#L26

**Comment by abatishchev** [comment]
Hi, did it you figure out how to call the extension method from PowerShell?

**Comment by stefanstranger** [comment]
Sorry didn't have time yet to further investigate. Maybe I find some time next week.

I'll keep you posted.

Stefan

**Comment by stefanstranger** [comment]
I'll have a look here https://powershell.org/forums/topic/how-do-i-use-extension-methods-in-zipfileextensionsclass/

**Comment by stefanstranger** [comment]
Hi Alexander,

I figured out how to use Extension methods in Powershell.

You can close this issue.

Regards,
Stefan
