### ISSUE TITLE
Custom 'typ' header

### ISSUE THREAD

**Issue by Altafard** [jwt-dotnet/jwt#284]
Will it be helpful if
```c#
header.Add("typ", "JWT");
```
will be replaced with
```c#
if (!header.ContainsKey("typ"))
    header.Add("typ", "JWT");
```

Are there any reasons not to do that?

**Comment by abatishchev** [comment]
Do you mean in [this line](https://github.com/jwt-dotnet/jwt/blob/88cc93d81b9aa976e6cfcd6aec482039a06922e9/src/JWT/JwtEncoder.cs#L43)? I think it's a valid change. Please submit a PR! And bump the version slightly.
