### ISSUE TITLE
Exception in JwtAuthenticationHandler when I upgrade to tersion 7

### ISSUE THREAD

**Issue by fmpfmp** [jwt-dotnet/jwt#287]
when i upgrade to version 7:

```
<PackageReference Include="JWT" Version="7.2.1" />
<PackageReference Include="JWT.Extensions.AspNetCore" Version="7.1.0-beta1" />
```
Error:

> 'JWT.JwtAuthenticationHandler' threw an exception:
ArgumentException: The format string 'Successfully decoded JWT, returning success' does not have the expected number of named parameters. Expected 1 parameter(s) but found 0 parameter(s).
Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(string formatString, int expectedNamedParameterCount)

when i use version 6 app is run ok.

**Comment by abatishchev** [comment]
Fixed in 7.1.0-beta2
