### ISSUE TITLE
JWT .net core - Could not load file or assembly, specified file not found

### ISSUE THREAD

**Issue by rcastoro** [jwt-dotnet/jwt#289]
Our application is running .net core 2.2, I installed the following package from the nuget PM console, as instructed on your nuget page for .net core programs: Install-Package JWT.Extensions.AspNetCore -Version 7.1.0-beta2

At runtime, I attempt to do the following to generate a JWT:

```c#
var payload = new Dictionary<string, object>() {
                { "iat", timestamp },
                { "jti", System.Guid.NewGuid().ToString() },
                { "name", userName },
                { "email", userEmail }
};

IJwtAlgorithm algorithm = new HMACSHA256Algorithm(); // symmetric
IJsonSerializer serializer = new JsonNetSerializer();
IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);

var token = encoder.Encode(payload, _sharedSecret);

```
**However, when it gets to this method the following error is thrown:**
![image](https://user-images.githubusercontent.com/8540618/84204123-a2a8f280-aa78-11ea-9369-a71b63cebb42.png)

**Comment by abatishchev** [comment]
Hi!
How is your CSPROJ looks like? Is it old or SDK-based?
What version (if any) of Json.Net you have installed?

**Comment by rcastoro** [comment]
I do not have json.net installed. CSPROJ file looks like this:
![image](https://user-images.githubusercontent.com/8540618/84205802-e3eed180-aa7b-11ea-8422-9c18d78bc093.png)

**Comment by abatishchev** [comment]
It's odd that it wasn't automatically, as s transient dependency. Try to add it explicitly.

**Comment by rcastoro** [comment]
What do you mean?
________________________________

**Comment by abatishchev** [comment]
```
<PackageReference Include="JWT" Version="7.2.1" />
```

**Comment by abatishchev** [comment]
Hi, did you figure it out?

**Comment by rcastoro** [comment]
I accomplished this with the microsoft token utilities
