### ISSUE TITLE
Switch from VS UT Framework to xUnit?

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#29]
I didn't find what's new in VS 2015 for its Unit Testing Framework (aka MSTest) but in my opinion [xUnit](http://xunit.github.io/) is more flexible and dynamically developing framework.

Particularly, it supports parametrized tests of various kinds (called PropertyData in v1 and MemberData in v2).

What do you think about such switch?

**Comment by devinrader** [comment]
I'm cool with that.  That also makes it easier to build and run tests cross platform.

**Comment by abatishchev** [comment]
Merged into https://github.com/jwt-dotnet/jwt/issues/55
