### ISSUE TITLE
Secret seemingly does nothing

### ISSUE THREAD

**Issue by githubcatw** [jwt-dotnet/jwt#293]
Hello. I'm using this library in Unity to authenticate requests to a web service, and I kept getting an "access denied" error. I talked to the web service's support team and they said that error occurs due to me using an incorrectly generated token. Sure enough, when I tried it in a JWT debugger it seems to not require a secret to decode the token. Is there a way to make the secret actually encrypt the data and be required to decode?

**Comment by abatishchev** [comment]
Hi!
It's not tricky, as it depends on whether you encrypt or decrypt and what kind of algorithm you're using - symmetric or asymmetric. Certificate means asymmetric.
Please provide more details.

**Comment by githubcatw** [comment]
I'm using HS256, and encrypting.
Here is my code:
```c#
IJwtAlgorithm algorithm = new HMACSHA256Algorithm();
IJsonSerializer serializer = new JsonNetSerializer();
IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
IJwtEncoder encoder = new JwtEncoder(algorithm, serializer, urlEncoder);
var token = encoder.Encode(client.id, client.secret);
```

**Comment by abatishchev** [comment]
HMAC is symmetric so secret is used.  It (as string converted to byte array) is passed here: https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/Algorithms/HMACSHA256Algorithm.cs#L11

**Comment by githubcatw** [comment]
Then why does decrypting with the debugger not require me to enter a secret? And, when I enter the secret there, it gives me an entirely new token that does require the secret to decrypt.

**Comment by abatishchev** [comment]
`Decrypt()` does require a secret, see https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/IJwtDecoder.cs#L45

But it's used only to re-calculate and then validate the signature, see https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtDecoder.cs#L147

JWT by itself is just a base64-encoded string, basically. It's not encoded so doesn't require a secret to decode, see https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtDecoder.cs#L104

JWE is the fully encoded version of JWT, which requires a secret to see the JWT first, and then another secret to verify it, see https://tools.ietf.org/html/rfc7516

**Comment by abatishchev** [comment]
Did you figure this out?

**Comment by glenvollmer** [comment]
@abatishchev   https://www.rfc-editor.org/rfc/rfc7519#appendix-A.1

**Comment by glenvollmer** [comment]
@githubcatw https://www.rfc-editor.org/rfc/rfc7519#appendix-A.1
