### ISSUE TITLE
Signature is Calculated on UTF8 text with a BOM. This is does not comply with RFC 7519 

### ISSUE THREAD

**Issue by randy-armstrong** [jwt-dotnet/jwt#294]
EncodingHelper uses 

`Encoding.UTF8.GetBytes()
`

This includes a BOM:
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.utf8?view=netcore-3.1

> The UTF8Encoding object that is returned by this property might not have the appropriate behavior for your app.
> It returns a UTF8Encoding object that provides a Unicode byte order mark (BOM). To instantiate a UTF8 encoding that doesn't provide a BOM, call any overload of the UTF8Encoding constructor.

For multiplatform IOP you should use:

`new UTF8Encoding(false).GetBytes()`

**Comment by abatishchev** [comment]
Would you please submit a PR and I'll be happy to review and push the change asap?

**Comment by randy-armstrong** [comment]
Submitted pull request.
This is technically a bug - not an enhancement.
