### ISSUE TITLE
JwtHeader field X5c is defined wrong.

### ISSUE THREAD

**Issue by IvanILanekassen** [jwt-dotnet/jwt#297]
Hi, 

We are using code from another package (https://github.com/ks-no/fiks-maskinporten-client-dotnet) that is using the JWT package. We needed to do a hard fork of the code, since we are on .NET Framework and that is not supported by the package produced by that repository. We also needed strongly named assemblies, so therefore we upgraded the JWT package to the latest version (from version 5.0.1). This worked on the production code, but suddenly the unit tests started failing. The error was a JSON parse error. By closer inspection, the parsing of the signed JWTs failed with the following error message:
```
Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: [. Path 'x5c', line 1, position 8.
```

The JwtHeader class itself refers to the specification of the x5c field (https://tools.ietf.org/html/rfc7515#section-4.1.6), which clearly states that "The certificate or certificate chain is represented as a JSON array of certificate value strings". The x5c property is defined as a string today, but need to be defined as a list or array of strings.

Downgrading to version 6.1.4 was a workoaround for us, since then the assembly is still strongly named, and the bug has not been introduced yet.

**Comment by abatishchev** [comment]
Would you please submit a PR to fix this and I'll release update NuGet package asap?

**Comment by IvanILanekassen** [comment]
OK, please see https://github.com/jwt-dotnet/jwt/pull/298.

**Comment by abatishchev** [comment]
Released as 7.3.0, please update and let me know how it goes. Thanks for the contribution, appreciate it!

**Comment by IvanILanekassen** [comment]
You are welcome, and thanks for prompt response and action. The tests are now green with v7.3.0 of the package so it seems the bug is fixed.

**Comment by abatishchev** [comment]
May I ask to see if you can generalize your tests and contribute to the project? More tests is always better.

**Comment by IvanILanekassen** [comment]
The tests in question are in this file: https://github.com/ks-no/fiks-maskinporten-client-dotnet/blob/master/KS.Fiks.Maskinporten.Client.Tests/MaskinportenClientTests.cs. It is testing a client for the "Maskinporten" identity service used in Norway. The Maskinporten service demands the use of the x5c header, and this is what trigged the bug. But I do not think it is possible to generalize the tests. Basically, the unit test I already modified is doing the same as the client (in the CreateJwtHeader method in this file: https://github.com/ks-no/fiks-maskinporten-client-dotnet/blob/master/KS.Fiks.Maskinporten.Client/Jwt/JwtRequestTokenGenerator.cs).
