### ISSUE TITLE
.AddClaim/ .AddClaims throws an error when multiple claims of the same type are Added

### ISSUE THREAD

**Issue by duhowise** [jwt-dotnet/jwt#303]
A user can have multiple of certain claim types eg: Roles
This is currently not possible as the library requires that claims added are unique.
Is there a way to turn this off?

**Comment by abatishchev** [comment]
What are you trying to achieve? To add an array as the value of a claim?

**Comment by abatishchev** [comment]
You can try using `AddClaim(name, arr)` for that purpose. Underneath this method is `Dictionary<string, object>` so the key must be unique.

**Comment by abatishchev** [comment]
@duhowise, have you figured this out? Do you need any more help or any changes made to the lon? I'm happy to discuss.

**Comment by duhowise** [comment]
Oh yes I tried your suggested approach and it worked

**Comment by abatishchev** [comment]
Cool! Hope you'll continue using this library. Please feel free to post more questions or suggestions.

**Comment by duhowise** [comment]
I can close the issue now?

**Comment by abatishchev** [comment]
No worries, I've closed it.
