### ISSUE TITLE
Add support for ECDSA signing algorithms

### ISSUE THREAD

**Issue by mandrachek** [jwt-dotnet/jwt#304]
java-jwt has out of the box support for RSA384, RSA512, and ECDSA256, ECDSA384, and ECDA512.

**Comment by abatishchev** [comment]
Hi,
For RSAxyz please see my response at https://github.com/jwt-dotnet/jwt/issues/238, correct me if I'm wrong.

For ECDSAxyz some simple code would be needed, from what I can see at

**Comment by abatishchev** [comment]
Sorry, pressed wrong button, on mobile they're so close to each other.

If you'd like to see this new functionality then please start a PR and I'll be more than happy to get it reviewed, polished if necessary, and released asap.

**Comment by mandrachek** [comment]
Sorry, I'm not a .net developer - I'm a primarily a java dev, who happens to be working with some folks that will need to implement JWT as well, and was hoping I could refer them to this library. I found this to be a shortcoming when comparing the implementations.  Last C# code I wrote was about 10 years go. :/

#238 is actually incorrect. RSA256 uses a SHA-256 _hash_.  While it allows for any size RSA key, it doesn't allow for any size hashing algorithm (SHA-384, SHA-512).  It should be relatively straightforward to take the existing RS256 class, convert it into a an abstract base RSA class, and then RSA256, RSA384, and RSA512 concrete classes which just use a different HashAlgorithmName. Or something along those lines.

The EC based values are different in that they crank both the elliptic curve value, along with the hashing algorithm.

**Comment by simon-pearson** [comment]
@abatishchev I'd like to take a look at this.

Would you object to me introducing a `RSASSAAlgorithm` abstract base class and inheriting from this in `RS256Algorithm`/`RS384Algorithm`/RS512Algorithm`?  Most of the code currently in `RS256Algorithm` would be moved into this class, and we'd add an abstract property for the hashing algorithm which each subclass could implement.

**Comment by abatishchev** [comment]
@simon-pearson, sure. please! sounds like the way to go. i'd happy to participate, review the code, get it rolling.

**Comment by simon-pearson** [comment]
@abatishchev unfortunately I think implementing the ECDSA algorithms will be much harder.  The `ECDsaCertificateExtensions.GetECDsaPrivateKey(X509Certificate2)` method used in https://stackoverflow.com/a/38135590/41956 will do the trick, but it was only added in .NET Framework 4.6.1/.NET Standard 1.4.

It seems from a cursory Googling ([link](https://vcsjones.dev/ecdsa-certificates-and-keys-in-net/) and [link](https://www.sysadmins.lv/blog-en/sign-data-with-ecc-cng-certificate.aspx)) that our only option in .NET Standard <= 1.3 and .NET Framework <= 4.6 is to P/Invoke to the Win32 API `CryptAquireCertificatePrivateKey` function to obtain a CNG key handle, create a `CngKey` class from this, and then use this with `ECDsaCng`.  It sounds quite ugly.

What are your thoughts?  I don't want to set about taking the P/Invoke approach without your approval.

**Comment by abatishchev** [comment]
@simon-pearson I think it'd be fine to split the work into two parts: where it's easy to implement using the built-in API and where P/Invoke is required.
I'd implement the former and throw NotImplementedException from the latter and let that be for a while. Then based on the popular demand see whether we should fill the gap or not.

**Comment by simon-pearson-lmk** [comment]
I really like your suggestion of splitting up the work on the ECDSA algorithms.  I'll start work on implementing them for .NET Framework 4.6.1/.NET Standard 2.0 targets using the `ECDsaCertificateExtensions.GetECDsaPrivateKey(X509Certificate2)`/`ECDsaCertificateExtensions.GetECDsaPublicKey(X509Certificate2)` extension methods, and for now I'll throw a `NotImplementedException` in earlier targets.

**Comment by simon-pearson** [comment]
I really like your suggestion of splitting the work on the ECDSA algorithms; I'll start work on implementing them using the `GetECDsaPrivateKey`/`GetECDsaPublicKey` extension methods for .NET Framework 4.6.1/.NET Standard 2.0 targets, and as you say throwing a `NotImplementedException` in earlier targets.

**Comment by abatishchev** [comment]
Addressed by #309
