### ISSUE TITLE
Base64UrlDecode throws System.Exception instead of a custom typed exception

### ISSUE THREAD

**Issue by DaFluid** [jwt-dotnet/jwt#31]
While testing my authorization code with various forms of tokens that have been tampered with, I've noticed JsonWebToken.DecodeToObject<T> throws a System.Exception when given an invalid token string. I've tracked it down to JsonWebToken.Base64UrlDecode. Throwing (and catching) an exception of the base Exception type is generally bad practice and I'd prefer catching a more specific exception (like ArgumentException, or the already existing SignatureVerificationException).

I haven't noticed Exception being thrown anywhere else in the class, either, so I believe this was not intentional. I've only noticed a block of code trying to catch a base Exception during a Convert.ToInt32 call. That could be altered to catch the specific exceptions the method can throw, perhaps in a similar way as here: http://stackoverflow.com/questions/136035/catch-multiple-exceptions-at-once

**Comment by dstj** [comment]
My [pull request](https://github.com/jwt-dotnet/jwt/pull/33/) fixes some of these problems. Waiting for it to be merged though...

**Comment by abatishchev** [comment]
The pull request has been merged, closing the issue too
