### ISSUE TITLE
Safe Handle has been closed problem

### ISSUE THREAD

**Issue by koroce** [jwt-dotnet/jwt#322]
I have received this problem when the second and subsequent time calling Encode() or Decode() in my MVC programme. I guess I need to close a SerialPort before calling. Will it work? Or how I should deal with it.

Thank you very much

Here's the code throws Exception, the save Exception is also thrown in Decode()

```
string token = JwtBuilder.Create()
                         .WithAlgorithm(new RS256Algorithm(pub, pri))
                         .WithSecret(System.Web.Configuration.WebConfigurationManager.AppSettings["secret"])
                         .AddClaim("exp", (new UtcDateTimeProvider()).GetNow().AddMinutes(30).ToUnixTimeSeconds())
                         .AddClaim("ID", validUser.ID)
                         .AddClaim("usr", validUser.USERID)
                         .AddClaim("IP", ipAddr)
                         .AddClaim("MAC", mac)
                         .Encode();
```

Here's the stacktrace:

```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Safe Handle has been closed
  Source=mscorlib
  StackTrace:
   在 System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   在 System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   在 System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash, Int32 cbHash, ObjectHandleOnStack retSignature)
   在 System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   在 System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
   在 System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   在 System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   在 System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   在 JWT.Algorithms.RSAlgorithm.Sign(Byte[] bytesToSign)
   在 JWT.Algorithms.RSAlgorithm.Sign(Byte[] key, Byte[] bytesToSign)
   在 JWT.JwtEncoder.Encode(IDictionary`2 extraHeaders, Object payload, Byte[] key)
   在 JWT.Builder.JwtBuilder.Encode()
   在 Supplier_and_Customer_Rating_Sys.Controllers.AccountController.Login(SysUser loginUser) 在 D:\workplace\C#\Supplier and Customer Rating Sys\Supplier and Customer Rating Sys\Controllers\AccountController.cs 中: 第 147 行
   在 System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   在 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   在 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
```

**Comment by abatishchev** [comment]
hi! in this case it doesn't matter how you construct the jwt builder. please post the code form here:

```
Supplier_and_Customer_Rating_Sys.Controllers.AccountController.Login(SysUser loginUser) 在 D:\workplace\C#\Supplier and Customer Rating Sys\Supplier and Customer Rating Sys\Controllers\AccountController.cs 中: 第 147
```

**Comment by koroce** [comment]
Here:

`
string token = JwtBuilder.Create()   //Line 147
                                                    .WithAlgorithm(new RS256Algorithm(pub, pri))    //Line 148
                                                    .WithSecret(System.Web.Configuration.WebConfigurationManager.AppSettings["secret"])
                                                    .AddClaim("exp", (new UtcDateTimeProvider()).GetNow().AddMinutes(30).ToUnixTimeSeconds())
                                                    .AddClaim("ID", validUser.ID)
                                                    .AddClaim("usr", validUser.USERID)
                                                    .AddClaim("IP", ipAddr)
                                                    .AddClaim("MAC", mac)
                                                    .Encode();
`

Thanks

**Comment by abatishchev** [comment]
Where the `pub` and `pri` come from? The problem is in them, the server cannot use either of them to sign the binary data or validate it.

**Comment by koroce** [comment]
`pub` and `pri`  are a RSA key pair, they are instantiated from RSACryptoServiceProvider and loaded from a .xml file like this:
`
StreamReader priReader = null;

            priKeys = new Dictionary<string, RSA>();

            foreach(XmlNode node in priNodes)
            {
                priReader = new StreamReader(node.FirstChild.InnerText);      //a node includes a key path
                RSA priKey = new RSACryptoServiceProvider();
                priKey.FromXmlString(priReader.ReadToEnd());

                priKeys.Add(node.Attributes[0].Value, priKey);
            }
            priReader.Close();
`

I would like to load all the keys on my server, they are stored on server as files. In my opinion, I should sign the token with a primary key and validate it with its public key, so I choose a constructor requires primary key to build a token. 

Thank you very much

**Comment by abatishchev** [comment]
The issue in general is that the cryptographic object is disposed before the token is attempted to be signed/verified.

Are you reading the certificate on the hot path (means same time when you handle the request) or separately (during startup)?

Try to have the while code end-to-end in the same method first: you load the certificate, you construct the builder, you handle the token.

Another option would be to construct a X509Certificate2 object (not the private and public key individually) and pass it or the builder. Also check whether HasPrivateKey would say true.

And one more option is to copy & paste the code from the library to your method and try to manipulate the cryptographic objects manually. As see the outcome.

**Comment by abatishchev** [comment]
For the code, see here: https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/Algorithms/RSAlgorithm.cs#L69
