### ISSUE TITLE
The HMACSHA384Algorithm incorrectly uses the HMACSHA512 class instead of the HMACSHA384 class

### ISSUE THREAD

**Issue by markkinkade** [jwt-dotnet/jwt#323]

**Comment by abatishchev** [comment]
@markkinkade hi, thanks for reporting! sorry about this. will release a fix within 30 minutes.

**Comment by abatishchev** [comment]
Will be available on NuGet.org shortly: https://www.nuget.org/packages/JWT/8.1.4
