### ISSUE TITLE
JwtData.Payload does not support multiple items with the same keys

### ISSUE THREAD

**Issue by mansoor-omrani** [jwt-dotnet/jwt#327]
I ran into the issue when generating a token for a user who had multiple roles.

Here is part of my code:
```csharp
...
foreach (var role in user.Roles)
{
    jwt.AddClaim(ClaimTypes.Role, role);
}
...
```
This results in "An item with the same key already exists" exception, since jwt.Payload is a Dictionary.

In essence, jwt.Payload must be an ```IList<KeyValuePair<string, object>>``` instead of ```IDictionary<string, object>>```.

**Comment by abatishchev** [comment]
Hi,
Please try using this:

```c#
jwt.AddClaim(ClaimTypes.Role, user.Roles);
```

See also #303.

**Comment by mansoor-omrani** [comment]
Yes. It works. I personally used this trick to pass the issue. But, you need to split the roles and assign them individually yourself too when deserializing the token.

In essence, I humbly believe, its not a correct solution, since ```AddClaim()``` and ```ClaimTypes.Role``` denotes a single Claim and a single Role, not a comma-separated list of roles .

.NET itself uses a ```List<Claim>``` when you intend to create a ```ClaimsIdentity```. So, I think a ```List<KeyValuePair<string, object>>``` is a more correct implementation than ```IDictionary<string, object>```.

**Comment by mansoor-omrani** [comment]
In .NET, current user is an implementation of IPrincipal interface:

```csharp
public interface IPrincipal
{
	IIdentity? Identity { get; }
	bool IsInRole(string role);
}
```
One of the implementations of this interface is ```ClaimsPrincipal```.
```csharp
public class ClaimsPrincipal : IPrincipal
{
	...
	public virtual IEnumerable<Claim> Claims { get; }
	...
}
```
As you see, ClaimsPrincipal uses a ```List<Claim>``` to store user's claims.

IsInRole() method iterates through users claims to see if current user is in a given role.

```csharp
public virtual bool IsInRole(string role)
        {
            for (int i = 0; i < m_identities.Count; i++)
            {
                if (m_identities[i] != null)
                {
                    if (m_identities[i].HasClaim(m_identities[i].RoleClaimType, role))
                    {
                        return true;
                    }
                }
            }
 
            return false;
        }
```

[https://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsPrincipal.cs,527ea367527f9f90](https://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsPrincipal.cs,527ea367527f9f90)

That's why I say, a ```List<KeyValuePair<string, object>>``` might be a more correct approach.

**Comment by mansoor-omrani** [comment]
There's a difference though, when I reviewed the case more closely.

.NET's has used a ```string``` type for the value of a claim.

This can be seen in ```Claim``` class's constructor:
```csharp
public Claim(string type, string value);
```
Or in ```HasClaim()``` method:
```csharp
public virtual bool HasClaim(string type, string value);
```

In jwt-dotnet, you have used ```object``` for a claim value. This is the reason for taking a ```IDictionary<string, object>```.

In essence, an ```object``` seems to be a more correct approach altogether and Microsoft might have used an incorrect approach for taking a ```string``` type for claim values. They probably have their own reason for such policy. Anyhow, the inconsistency exists between the way Microsoft uses claims and the way jwt-dotnet approach to claims.

All in all, I personally opine, if you switch from ```IDictionary<string, object>``` to a ```IList<string, object>```, you will provide the use bests of the two worlds.

**Comment by mansoor-omrani** [comment]
Sorry, for the long discussion! :D

**Comment by abatishchev** [comment]
@mansoor-omrani hey, I'm sorry for not replying, I'm in vacation and have no computer with me. I'll come back to this issue once back home!

Meanwhile please feel free to pike on your ideas this the code can be improved.

Another thing to check if the JWT spec allows to have multiple (duplicate) keys. It might not.
