### ISSUE TITLE
Incorrectly targeting NET50 where it should be NET5_0

### ISSUE THREAD

**Issue by angusmillar** [jwt-dotnet/jwt#329]
I was trying to use JwtAlgorithmName.ES256 in a .net core 5.0 project and JWT (8.2.0) when I received this exception text "_ECDSA algorithms are only supported when targeting .NET Standard 2.0"_ which is found in the class JWT.Algorithms.ECDSAAlgorithmFactory. 
Yet in that class on line 48, you have the following if statement :

`#if NETSTANDARD2_0 || NET50`

Whereas it should be this:

`#if NETSTANDARD2_0 || NET5_0`

as per this documentation: 
https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries
See the section titled: How to multitarget

**Comment by abatishchev** [comment]
@angusmillar thanks for the reporting the issue! I fixed it in #330. Can you please take a look and confirm it looks good to you?

**Comment by angusmillar** [comment]
Hi Alex,
I think you have missed the following extra references 
JWT.Algorithms.ECDSAAlgorithmFactory on lines 48 & 72
JWT.Algorithms.ES256Algorithm on line 1
JWT.Algorithms.ES384Algorithm on line 1
JWT.Algorithms.ES512Algorithm on line 1
And I think you also need to update JWT.Tests.Net50.csproj line 4 from this <TargetFramework>net50</TargetFramework> to this <TargetFramework>net5.0</TargetFramework>

**Comment by abatishchev** [comment]
@angusmillar thanks for double checking! by looking at the latest changes at https://github.com/jwt-dotnet/jwt/pull/330/files I think it's all now.

**Comment by angusmillar** [comment]
Hey, Alex could I communicate with you via email, skype something not public. I work for a large global Pathology provider and Health informatics groups are working on the problem of getting the world flying again post the COVID pandemic. Standards are emerging to facilitate sharing of verifiable credentials as JWS tokens that consumers would present at passport controls to validate that they have had a recent COVID immunisation. However, from my investigations, I have not as yet found a JWT library that can create these  JWS tokens, not you, Microsoft or jose-jwt. All these libraries seem to have limitations that are not limitations of the base JWS standard: [https://datatracker.ietf.org/doc/html/rfc7515]. 
I'm not asking for a commitment but I would like to explain further for your considerations. If we could solve the issues while maintaining within the boundaries of the JWS standard, it could generate more use of your library as the community is still searching for a .net reference implementation for this problem.
