### ISSUE TITLE
JwtAuthenticationDefaults does not exist when trying to implement in Startup.cs in .NET 5.0

### ISSUE THREAD

**Issue by thesecuritycompany** [jwt-dotnet/jwt#334]

**Comment by abatishchev** [comment]
Hi, can you provide more details?

**Comment by thesecuritycompany** [comment]
> 
> 
> Hi, can you provide more details?

I managed to get the JWT working in the end. I ended up using the tutorial code for auth0.com backend API - 'ASP.NET Core Web API v2.1' (https://auth0.com/docs/quickstart/backend/aspnet-core-webapi-2) instead of 'ASP.NET Core Web API' (https://auth0.com/docs/quickstart/backend/aspnet-core-webapi) which I was using when make my original post.
