### ISSUE TITLE
ES256Algorithm absent for 8.2.2 version of nuget package.

### ISSUE THREAD

**Issue by iPilot** [jwt-dotnet/jwt#337]
Update from 8.1.6 lead to compilation error due to class ES256Algorithm not found and no information about deprecation.

Platform NET5.0

**Comment by abatishchev** [comment]
hi! does it work properly in a prior version?

The class is guarded by a directive:

```c#
#if NETSTANDARD2_0
```

What might not work properly.

**Comment by iPilot** [comment]
8.1.6 the last that works correctly.
