### ISSUE TITLE
Dependency on System.Web.Extensions

### ISSUE THREAD

**Issue by jvenema** [jwt-dotnet/jwt#34]
It would be great to replace the dependency on System.Web.Extensions (which is only used for Json serialization) with NewtonSoft - that way we can use this library in Xamarin projects (which Newtonsoft.Json supports, but Extensions doesn't).

**Comment by felipeleusin** [comment]
Honestly I think it might be even better to use SimpleJson and just embed it in the project.

**Comment by abatishchev** [comment]
Do you still care? Would you reopen the discussion? Submit a pull request? I'd made this pluggable, and personally prefer Json.Net as a standard de-facto.

**Comment by ststeiger** [comment]
You can use mine here:
https://github.com/ststeiger/Jwt_Net20
I removed it, made it work on .NET 2.0 and added RSA + ES methods (ES work in progress, will add dependency to bouncycastle in .NET 2.0, because .NET Framework 2.0 has no elliptic curve cryptographic class).

**Comment by abatishchev** [comment]
@ststeiger can we instead join the efforts and make all these changes to this repo?

**Comment by ststeiger** [comment]
@abatishchev: Yea we can, but until I'm done developing, I use my own repository. Don't think it's wise to pull work-in-progress into master.

**Comment by abatishchev** [comment]
Removed as part of v2, see https://github.com/jwt-dotnet/jwt/pull/67
