### ISSUE TITLE
JwtAuthenticationMiddleware.Invoke throwing a NotImplementedException

### ISSUE THREAD

**Issue by frankely** [jwt-dotnet/jwt#341]
JwtAuthenticationMiddleware.Invoke throwing a NotImplementedException

**Comment by abatishchev** [comment]
hi @frankely, thanks for giving it a try! I've made a small change at #342, please take a look. Namely:

- [JwtAuthenticationMiddleware](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT.Extensions.AspNetCore/JwtAuthenticationMiddleware.cs) is indeed doesn't do anything other than throwing an exception
- [JwtAuthenticationHandler](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs) is functional. Can you please try it out?

Also please feel free to contribute or just share ideas what the middleware should do. Register the handler? Something else?

**Comment by frankely** [comment]
Thank you for the clarification! Well from a DevEx perspective I was expecting that the middleware registered the handler for me. Maybe it's misleading to just have without doing anything since I didn't even know there was a handler available.

**Comment by frankely** [comment]
@abatishchev I tried the [JwtAuthenticationHandler](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT.Extensions.AspNetCore/JwtAuthenticationHandler.cs) and it works perfectly! The only considerations are adding a **IJwtDecoder** to your dependency container which I did by using some snippets from your README file

```csharp
services.AddTransient<IJwtDecoder>(_ =>
            {
                IJsonSerializer serializer = new JsonNetSerializer();
                var provider = new UtcDateTimeProvider();
                IJwtValidator validator = new JwtValidator(serializer, provider);
                IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
                IJwtAlgorithm algorithm = new HMACSHA256Algorithm(); // symmetric
                return new JwtDecoder(serializer, validator, urlEncoder, algorithm);
            });
```

and also adding a Scheme when adding the authorization

```csharp
services.Configure<JwtAuthenticationOptions>(
      configuration.GetSection("JwtAuthentication")); // The JwtAuthenticationHandler needs this Options

var tokenOptions = configuration.GetSection("JwtAuthentication").Get<JwtAuthenticationOptions>();
services
    .AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
    })
    .AddScheme<JwtAuthenticationOptions, JwtAuthenticationHandler>(
        JwtAuthenticationDefaults.AuthenticationScheme,
        options =>
        {
            // secrets
            options.Keys = tokenOptions.Keys;

            // force JwtDecoder to throw exception if JWT signature is invalid
            options.VerifySignature = tokenOptions.VerifySignature;
        });
```

```json
  "JwtAuthentication" : {
    "Keys" : ["SOME_SECRET_HERE"]
  }
```

**Comment by abatishchev** [comment]
@frankely I'm happy to hear it worked for you!

How so you think which of this code needs to go into the middlewear, if any? Of maybe the middlewear needs to be deleted altogether? This package / part of the library isn't too popular or known so not polished enough.

On other hand, if we introduce something like `UseJwtAuthorization()` (or `Add()`?) what should go into there?

**Comment by frankely** [comment]
@abatishchev I feel that something that should be done is to register at least a default IJwtDecoder when calling UseJwtAuthorizatio.

**Comment by abatishchev** [comment]
hey @frankely, my bad, it's already partially implemented. I just completely forgot about it. The registration should look like this:

```c#
services.AddAuthentication(options =>
    {
        // Prevents from System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultAuthenticateScheme found.
        options.DefaultAuthenticateScheme = JwtAuthenticationDefaults.AuthenticationScheme;

        // Prevents from System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
        options.DefaultChallengeScheme = JwtAuthenticationDefaults.AuthenticationScheme;
    })
.AddJwt(options =>
    {
        options.Keys = configureOptions.Keys;
        options.VerifySignature = configureOptions.VerifySignature;
    });
```

I've updated the readme via #345.

It registers all components other than `IAlgorithmFactory`.

I also added an overload `AddJwt<TFactory>() where TFactory :  IAlgorithmFactory` which will do register all components without exceptions (hopefully). Please check out version `7.3.0` and provide your feedback.

**Comment by frankely** [comment]
This is awesome! Thank you @abatishchev I will update my code as soon as I can and I will let you know! Thank you for having this repo available.
