### ISSUE TITLE
User.Identity.IsAuthenticated is always false when use JWT.Extensions.AspNetCore

### ISSUE THREAD

**Issue by LeTranAnhVu** [jwt-dotnet/jwt#356]
Follow the README.md in JWT.Extensions.AspNetCore to configure the JWT Authentication stuff. Then I figured out that `User.Identity.IsAuthenticated` is always false. That is because the default IdentityFactory does not provide the Authentication Theme.
I have to custom  the Identity instance in `options.IdentityFactory` like this:

```c#
 options.IdentityFactory = dictionary =>
  {
       var claims = dictionary.Select(p => new Claim(p.Key, p.Value));
       var identity = new ClaimsIdentity(claims, JwtAuthenticationDefaults.AuthenticationScheme);
       return identity;
   };
```
Does anyone has better idea? Or did I miss configuring something? If my solution is correct. Should the author provide more detail configuration in README.md?

**Comment by abatishchev** [comment]
What I can do is to pass it indeed? And make it configurable whether to do so or not.

**Comment by LeTranAnhVu** [comment]
Yes, the PR look good to me.
