### ISSUE TITLE
Anybody can decode without key if he knows token is encoded with JWT

### ISSUE THREAD

**Issue by naveedyousaf09** [jwt-dotnet/jwt#36]
Encoded token can be decoded without secret key 
pass **encoded token** in 1st parameter, **any key** in 2nd parameter and pass **false** is 3rd parameter in the following method
`JsonWebToken.Decode`

and you are done

**Comment by naveedyousaf09** [comment]
or can you please give an example to encrypt and avoid decryption without secret key

**Comment by johanbenschop** [comment]
The JWT token is base64 encoded, not encrypted. The third part of the token (denoted by the dots) is the verification part which you are disabling in your example. Just take any JWT token and decode it at https://jwt.io/. See https://jwt.io/introduction/ for an introduction on the JWT.

**Comment by naveedyousaf09** [comment]
I apologize for lack of knowledge, thanks for your response
