### ISSUE TITLE
How to get the TokenExpiredException on a token, without the signature verification

### ISSUE THREAD

**Issue by abrasat** [jwt-dotnet/jwt#369]
First of all thanks for the great library. I have an application which calls cyclically some web service api, secured with a JWT token. I would like to check if the token has expired before each call to the web service. For this I would like to catch the TokenExpiredException when decoding the jwt token. The problem is that the "secret" of the jwt token is not known on the application side, so that I am getting the SignatureVerificationException, even for the expired tokens.
Is there any workaround possible to get the TokenExpiredException without having the secret?

**Comment by abatishchev** [comment]
Thanks for kind words! You're welcome.

It might not be too elegant but still possible. See methods [Decode()](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtDecoder.cs#L143) and [Validate](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtDecoder.cs#L227). By default the former calls the latter only of `validate = true` but you can try call it manually.

Another option is to call call [JwtValidator.TryValidate()](https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtValidator.cs#L76) which is called by [JwtValidator.Validate()] and of the former returned not null `ex` - the latter will trow it. You can do something similar.

Makes sense?

**Comment by abrasat** [comment]
@abatishchev Thanks for pointing out the relevant code. I took a look, but dont really see how to avoid that the SignatureVerificationException is thrown before the method "private Exception GetValidationException(string payloadJson)" is called.

**Comment by abatishchev** [comment]
`JwtValidator.Validate()` calls `JwtValidator.TryValidate()` and it has returned non-empty ex - it will throw it. If you call `JwtValidator.TryValidate()` yourself then no exception would be thrown. Is what you're looking for, or something else?

Or maybe I see now what you're saying. Would it help if I make some/all methods of JwtValidator `public`?

**Comment by abrasat** [comment]
Yes, some methods could be made public. For example the above mentioned method "private Exception GetValidationException(string payloadJson)"

**Comment by abrasat** [comment]
@abatishchev : Can you please give me some hints about how to perform the token expiration check with the new library version? This was the code with the previous version, based on your code sample:

```
public bool CheckTokenValidation(string token, int timeMargin)
{
    var tokenIsValid = false;

    try
    {
        JwtValidator validator = new JwtValidator(_serializer, _provider, _urlEncoder, timeMargin);
        var jwtParts = new JwtParts(token);
        var ex = validator.GetValidationException(jwtParts);
        if (ex is object)
            throw ex;

        tokenIsValid = true;
    }
    catch (TokenExpiredException te)
    {
        //Console.WriteLine("Token has expired");
        throw;
    }
    catch (SignatureVerificationException sv)
    {
        //Console.WriteLine("Token has invalid signature");
        throw;
    }
    catch (Exception ex)
    {
        throw;
    }
    return tokenIsValid;
}
```

**Comment by abatishchev** [comment]
@abrasat hi, does this snippet work? can you please elaborate the question? happy to help!

**Comment by abrasat** [comment]
@abatishchev : Yes, I used the code above to verify if a token was expired, without checking the signature. The code does not compile with the new version 9.0. It seems that some changes were made in JwtValidator regarding the token validation checks, that is why I asked what would be the best way to check if a token was expired, using the actual version.

**Comment by abatishchev** [comment]
What's the compiler error you're getting? The only chance was made was in the ctor of JwtValidator. What's the value of `timeMargin` you're passing?

**Comment by abrasat** [comment]
@abatishchev  : There is no JwtValidator constructor where the value of timeMargin (was set to 10 seconds) can be passed. I found that there is a class ValidationParameters available now. Not sure about how my code has to be adapted with the new JwtValidator constructor parameters. Do I still have to use the JwtParts to get the validation exception?

**Comment by abatishchev** [comment]
Try to pass this:

```c#
ValidationParameters.Default
                    .With(p => p.TimeMargin = 10);
```

**Comment by abrasat** [comment]
@abatishchev : Thanks. Is the signature check disabled with the code above? And how do I get the result of the validation check, do I still have to call "GetValidationException" with the JwtParts object?

**Comment by abatishchev** [comment]
To have all checks disabled (what doesn't matter in your case, I think), use `ValidationParameters.None`. No changes in the underlying logic have been made.

**Comment by abrasat** [comment]
Ok, thanks. Do I have to activate also the ValidateExpirationTime, besides setting the TimeMargin ?

```
var valParams = ValidationParameters.None
       .With(p => p.ValidateExpirationTime = true)
       .With(p => p.TimeMargin = timeMargin);
```

Or is this the setting of ValidateExpirationTime to true not necessary, if the token expiration validation exception is manually checked (GetValidationException() call) ?

**Comment by abrasat** [comment]
@abatishchev : Thanks. Could you please change the code for ValidateNbfClaim() and throw the same exception for nbf as for exp, instead of the SignatureVerificationException for the nbf check? Or eventually even a new TokenNotYetValidException?


```
...
if (secondsSinceEpoch - _valParams.TimeMargin >= expValue)
{
        return new TokenExpiredException("Token has expired.")
        {
           Expiration = UnixEpoch.Value.AddSeconds(expValue),
           PayloadData = payloadData
         };
}
...
...

 if (secondsSinceEpoch + _valParams.TimeMargin < nbfValue)
 {
       return new SignatureVerificationException("Token is not yet valid.");
 }
...
```

**Comment by abrasat** [comment]
[https://github.com/jwt-dotnet/jwt/pull/397](https://github.com/jwt-dotnet/jwt/pull/397)
