### ISSUE TITLE
options.IdentityFactory is missing

### ISSUE THREAD

**Issue by doggy8088** [jwt-dotnet/jwt#373]
Does the `options.IdentityFactory` removed? I couldn't find it.

![image](https://user-images.githubusercontent.com/88981/153716097-9f06457c-8e5b-4a85-9827-d81dd7c37773.png)

**Comment by abatishchev** [comment]
Hi,
I must've missed to update the doc? Where did you find It? Or you were using it before?
I replaced `options.IdentityFactory` with `IIdentityFactory` that need to be injected into the Do container.

**Comment by doggy8088** [comment]
I found these on the README of the repo. 

![image](https://user-images.githubusercontent.com/88981/153724249-6d5f841c-3f83-4a5b-ac53-217b9a2ce63b.png)

https://github.com/jwt-dotnet/jwt/blob/20378ec58608119b08f7d199fb4064f2d1b0fab1/README.md?plain=1#L300-L310

**Comment by abatishchev** [comment]
Thanks! Updated the readme.

**Comment by doggy8088** [comment]
Nice, Thanks!

```cs
services.AddSingleton<IIdentityFactory, CustomIdentityFctory>();
services.AddSingleton<ITicketFactory, CustomTicketFactory>();
```

**Comment by doggy8088** [comment]
@abatishchev 
Also, the https://github.com/jwt-dotnet/jwt#register-middleware-to-validate-jwt also outdated. These are not **middleware**.

**Comment by abatishchev** [comment]
Sure, will update the wording with my next PR. Thanks!

**Comment by doggy8088** [comment]
@abatishchev I didn't see the PR. Just reminding. 😅

**Comment by abatishchev** [comment]
Ah, bummer. Forgot. Will do. Thanks!
