### ISSUE TITLE
Time margin / TokenExpiredException

### ISSUE THREAD

**Issue by aienabled** [jwt-dotnet/jwt#377]
Good day,
I've noticed that we have plenty of TokenExpiredException errors in the log. While reviewing the code I've noticed that the default time margin for validator is zero seconds:
https://github.com/jwt-dotnet/jwt/blob/cff76cd8ce8f943850410c51f51ee76180f39694/src/JWT/JwtValidator.cs#L38
         
Is this correct?

Regards!

**Comment by abatishchev** [comment]
Hi! Yes, it is. The time margin functionality was introduced later so to keep backward compatibility it was set to 0.

**Comment by aienabled** [comment]
Ah, it makes sense. I will investigate why we're getting these exceptions, perhaps it's on the client side.
Thank you for the quick reply!

**Comment by abatishchev** [comment]
Sure thing, happy to help. Feel free to post my questions/issues.
Please also give a try to a recently published beta.
Are you using the extensions package for ASP.NET Core?

**Comment by aienabled** [comment]
I'm working on a custom webservice to validate tokens issued by Epic Online Services (game ownership verification). Due to legacy code it's still running on .NET Framework 4.7.1.
I'm not sure about trying the beta as this webservice is operating in production environment.
I guess the expired tokens were cached on the client side for some time.

Regards!
