### ISSUE TITLE
Null Reference Exception when generating a token

### ISSUE THREAD

**Issue by drusellers** [jwt-dotnet/jwt#378]
While trying to use the JwtEncoder to build out a JWT I ran into a `NullReferenceException`. I was able to track it down to the following code.

So in the JwtEncoder (registered via `services.AddJwtEncoder<HMACSHAAlgorithmFactory>();`)

When I call 

```csharp
encoder.Encode(new Dictionary<string, object>(), "claim-value", "claim-name");
```

This leads to a `NullReferenceException` at 

https://github.com/jwt-dotnet/jwt/blob/5d59adf102144499e3ed762a6c65fa006e622c99/src/JWT/Algorithms/JwtAlgorithmFactory.cs#L11

because context is `null` as set here.

https://github.com/jwt-dotnet/jwt/blob/5d59adf102144499e3ed762a6c65fa006e622c99/src/JWT/JwtEncoder.cs#L49

Any help would be greatly appreciated.

**Comment by abatishchev** [comment]
hi! thanks for reaching out and reporting the issue. I'll fix it asap.

**Comment by abatishchev** [comment]
Can you please first list the versions of the NuGet packages you're using? Jwt, Extensions.DI, Extensions.AspNetCore.

**Comment by drusellers** [comment]
```
JWT.Extensions.AspNetCore/8.2.0
    JWT/8.8.0
    JWT.Extensions.DependencyInjection/1.1.0
    Microsoft.AspNetCore.Authentication/2.2.0
    Newtonsoft.Json/12.0.1
```

<img width="391" alt="image" src="https://user-images.githubusercontent.com/63355/157118913-9decce52-8c1d-473e-aefe-b194f0572a68.png">

**Comment by abatishchev** [comment]
From the code I see that the intend that `JwtEncoder` would hold an instance of `DelegateAlgorithmFactory` that will return the algorithm. Somehow it never occurred before that it would be `JwtAlgorithmFactory`. They're basically incompatible since Encoder has no information about the context and the algorithm at this point. At least that's the current implementation.

Can you show your setup in `Startup.cs`?

**Comment by drusellers** [comment]
**`Program.cs`**

```csharp
using JWT;
using JWT.Algorithms;
using JWT.Extensions.AspNetCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication(JwtAuthenticationDefaults.AuthenticationScheme)
    .AddJwt<HMACSHAAlgorithmFactory>(options =>
    {
        options.Keys = new[] { "deadbeef" };
        options.VerifySignature = true;
    });
builder.Services.AddJwtEncoder<HMACSHAAlgorithmFactory>();

var app = builder.Build();


var encoder = app.Services.GetRequiredService<IJwtEncoder>();

// Throws here
var token = encoder.Encode(new Dictionary<string, object>(), "", "");
Console.WriteLine(token);
```

**Comment by abatishchev** [comment]
@drusellers hi! Sorry for the delay, didn't know what to do. But now I've got an idea but currently the build is busted so I can't try it out, see #380. Will come back to this issue as soon that one is resolved.

**Comment by drusellers** [comment]
No worries @abatishchev - thank you for even looking at it. :) Hopefully, the build will be fixed soon.

**Comment by abatishchev** [comment]
@drusellers are you using both `Decode()` and `Encode()`, or only  the latter?

**Comment by drusellers** [comment]
I'm using the `Encode()` to generate a JWT manually and then the dotnet `.AddAuthorization().AddJwt()` does the decoding.

**Comment by abatishchev** [comment]
The problem is in the algorithm factory being registered. All but DelegateFactory are for decoding since the algorithm is read from the JWT header.
And to encode you specify certain algorithm by passing to DelegateFactory.
Would that work for you?

```csharp
builder.Services.AddJwtEncoder<HMACSHAAlgorithmFactory>()
```

On other hand I think it needs be to this:

```csharp
builder.Services.AddJwtEncoder<HMACSHAAlgorithmll>()
```

Which will pass and register it for you.

**Comment by abatishchev** [comment]
@drusellers please update to:

- JWT 9.0.0-beta5
- JWT.Extensions.DI 2.0.0-beta1
- JWT.Extensions.AspNetCore 9.0.0-beta2
