### ISSUE TITLE
JwtBuilder doesn't respect System.Text.Json.Serialization.JsonPropertyName attribute when deserializing into a record

### ISSUE THREAD

**Issue by Iapetus-11** [jwt-dotnet/jwt#379]
```cs
public record UserJwtTokenPayload
{
    [JsonPropertyName("uid")]
    public uint UserId { get; set; }
    
    ...
}
```
I have this record and this code
```cs
var data = JwtBuilder.Create()
    .WithAlgorithm(new HMACSHA256Algorithm())
    .WithSecret(_jwtSecret)
    .MustVerifySignature()
    .Decode<UserJwtTokenPayload>(authHeader);

return data?.UserId;
```
In this case, data is an instance of `UserJwtTokenPayload` with default values because `.Decode<...>(...)` does not respect the `[JsonPropertyName(...)]` attribute. 

If I were to rewrite this to use `System.Text.Json`, this works just fine. Example:
```cs
var data = JwtBuilder.Create()
    .WithAlgorithm(new HMACSHA256Algorithm())
    .WithSecret(_jwtSecret)
    .MustVerifySignature()
    .Decode(authHeader);

return JsonDocument.Parse(data).Deserialize<UserJwtTokenPayload>()?.UserId;
```

It seems that it should be respecting `JsonPropertyName` attributes when decoding as the library does when actually encoding.

**Comment by abatishchev** [comment]
Hi,
`[JsonPropertyName]` looks like a `System.Text.Json` attribute. Yeah, I think [it is](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=net-6.0).
Jwt.Net uses Json.Net which will ignore it. You need to use [its attribute](https://www.newtonsoft.com/json/help/html/jsonpropertyname.htm) `[JsonProperty]` to achieve the same.
Makes sense?
Or you can specify custom json serializer 

https://github.com/jwt-dotnet/jwt/blob/5d59adf102144499e3ed762a6c65fa006e622c99/src/JWT/Builder/JwtBuilder.cs#L80-L84

Then ideally I'd ask you to contribute to the library and ship the implementation as an extension, see:

- https://github.com/jwt-dotnet/jwt/issues/76
- https://github.com/jwt-dotnet/jwt/issues/364

**Comment by Iapetus-11** [comment]
Alright thank you, though it's still weird that it does respect the attribute when serializing.

> Then ideally I'd ask you to contribute to the library and ship the implementation as an extension
Maybe, I'm still new to C#, I'll think about it.

**Comment by abatishchev** [comment]
To explain little more: those are 2 different JSON serializing libraries with their own set of attributes, what means one is unaware of the another.

**Comment by Iapetus-11** [comment]
Oh I understand that, which is why it's so weird that one library is partially respecting the attributes of another.

**Comment by abatishchev** [comment]
Sorry, it might be confusing indeed. `System.Text.Json` reuses some methods and attributes names from `Json.Net`. When the name is same it would look like one respects another.
