### ISSUE TITLE
Dedicated Verify() method

### ISSUE THREAD

**Issue by bbsimonbb** [jwt-dotnet/jwt#38]
Feature request ! : Would it be useful to add a public method Verify(object Token, string Key). I want to process tokens from multiple sources. I need to decode them to recover the issuer so I know which key to use for verification. A Verify() method would save me calling Decode() twice.

**Comment by abatishchev** [comment]
Please submit a pull request!

**Comment by abatishchev** [comment]
btw there is [Verify()](https://github.com/jwt-dotnet/jwt/blob/master/JWT/JWT.cs#L148) method now but it's private. We can make it public, if you're still interested.

**Comment by abatishchev** [comment]
See https://github.com/jwt-dotnet/jwt/pull/52
