### ISSUE TITLE
Throw custom exceptions when decoding a token

### ISSUE THREAD

**Issue by merildev** [jwt-dotnet/jwt#40]
When I use the Decode() method, a "_SignatureVerificationException_" exception is thrown no matter if the signature is invalid (**1**), the expiracy date is invalid (**2**) or the token has expired (**3**):

**1.** 
```csharp
if (decodedCrypto != decodedSignature)
{
    throw new SignatureVerificationException(string.Format("Invalid signature. Expected {0} got {1}", decodedCrypto, decodedSignature));
}
```

**2.**
```csharp
try
{
   exp = Convert.ToInt32(payloadData["exp"]);
}
catch (Exception)
{
   throw new SignatureVerificationException("Claim 'exp' must be an integer.");
}
```

**3.**
```csharp
if (secondsSinceEpoch >= exp)
{
   throw new SignatureVerificationException("Token has expired.");
}
```

cf. https://github.com/jwt-dotnet/jwt/blob/cfad0ab08a8ef20b2781850939ed50c97498768a/JWT/JWT.cs#L152

Would it be possible to have a specific custom exception for each scenario? Then it would be easier and more robust to handle errors when decoding a token.

Thank you

**Comment by abatishchev** [comment]
Resolved as part of https://github.com/jwt-dotnet/jwt/pull/33, also see https://github.com/jwt-dotnet/jwt/issues/31
