### ISSUE TITLE
How to convert from Java code?

### ISSUE THREAD

**Issue by wuzhenda** [jwt-dotnet/jwt#404]
I got a piece of java code which implemented the jwt, how to convert to use dotnet implement?

```jaba
    static final String JWT_SECERT = "aaa...bbb";
    public String createJwt(String keyId, Date expiredTimeAt) {
         byte[] encodeKey = Base64.getDecoder().decode(JWT_SECERT);
        SecretKey secretKey= new SecretKeySpec(encodeKey, 0, encodeKey.length, "AES");
        SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;

        JwtBuilder builder = Jwts.builder()
                .claim("fdMoKey",keyId)
                .setExpiration(expiredTimeAt)
                .signWith(signatureAlgorithm, secretKey);
        return builder.compact();
    }
```

**Comment by abatishchev** [comment]
See if this section helps: https://github.com/jwt-dotnet/jwt#or-using-the-fluent-builder-api

**Comment by abatishchev** [comment]
Please keep in mind that while the API look similar, these are two different libraries, unrelated to each other, not a port of one to another.

**Comment by wuzhenda** [comment]
Yes.My problem is the  "SignatureAlgorithm" part. I'm not familiar with RS256Algorithm method.

```
           var encodeKey = Convert.FromBase64String(JWT_SECERT);
           
            **how to get certificate here ，seems need AES method?**

            var token = JwtBuilder.Create()
                      .WithAlgorithm(new RS256Algorithm(certificate))
                      .AddClaim("exp", DateTimeOffset.UtcNow.AddHours(1).ToUnixTimeSeconds())
                      .AddClaim("fdMoKey", "test")
                      .Encode();
```

**Comment by abatishchev** [comment]
> HS256 (HMAC with SHA-256) is a symmetric keyed hashing algorithm that uses one secret key.

Looks it's what you were using before. The corresponding algorithm now would be HMACSHA256Algorithm,. It doesn't require a certificate, nor does seemingly your old code.

I might be wrong and it's important as this would be a symmetric algorithm, basically just a hash. It encodes the token but doesn't encrypt, hence doesn't provide real security.

Do you have an example of the resulting token? Especially

**Comment by wuzhenda** [comment]
this is a token generated by the Java guys.

```
eyJhbGciOiJIUzI1NiJ9.eyJmZE1vS2V5IjoidGVzdCIsImV4cCI6NjU0OTQ0Mjc5OTl9.25-6OpHBr0yjWMtBku5Mlam0d5T_CHmJu3vHBlK4Hqs
```

I tried to use the jwt-dotnet to decode ,but it throwed exceptions.

**Comment by wuzhenda** [comment]
the JWT_SECERT in my first comment below, it based on the project [okta-java-jwt]( https://github.com/oktadeveloper/okta-java-jwt-example.git)
```
private static final String JWT_SECERT = "5860382b80424abdb9b7b9154fd95mo0";
```

**Comment by wuzhenda** [comment]
tks.this really helps me.
