### ISSUE TITLE
How to create a HMACSHA256Algorithm using custom Secret

### ISSUE THREAD

**Issue by mattabb** [jwt-dotnet/jwt#406]
I know this is not ideal nor safe, however I am currently updating legacy code and need backwards compatibility.  The HMACSHA256Algorithm constructor doesn't have a constructor for the secret however.  Is this something that is possible?

Thanks

**Comment by abatishchev** [comment]
Please see #404, it has some samples how to do that. Basically you pass the secret as a byte array to `Decode(token, byte[], bool)`.
