### ISSUE TITLE
 JWT.Extensions.AspNetCore refers JWT prerelease version

### ISSUE THREAD

**Issue by hartmark** [jwt-dotnet/jwt#412]
Hello,

It seems the  JWT.Extensions.AspNetCore nuget version 9.1.0 refers pre-release version of JWT.

https://www.nuget.org/packages/JWT.Extensions.AspNetCore

**Comment by abatishchev** [comment]
Ah, indeed. Bummer, my bad. Because all packages are pushed from the same repo off the main branch. And then the main lib got bumped to a beta version and then I pushed a non-beta version of the extension.
How much troubles does that cause?

**Comment by abatishchev** [comment]
Fixed as [9.1.1](https://www.nuget.org/packages/JWT.Extensions.AspNetCore/9.1.1), unlisted 9.1.0. Thanks for bringing this up!
