### ISSUE TITLE
Library should include both Json.Net and System.Text.Json serialziers

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#420]
After the recent changes, it includes one or another.

@hartmark we've made it too opinionated: either one or another. How about somehow allow both options on the platform whether that's possible?

**Comment by hartmark** [comment]
System.Text.Json is supported for .net fw 4.6.2 up to .net 6

So you mean for those versions there should be an option to use either that or Json.net?

**Comment by abatishchev** [comment]
Yes, I'm thinking if we should include both serialziers into the assembly and the user would have a choice. Tests must be updated to test everything against both serialziers too, that might be the most tedious change of all

**Comment by hartmark** [comment]
Alright, the tests can use some kind of parameterized test where the input is which serializer to use so we get everything tested twice.

Question is what should be used per default, one idea could be to use System.Text.Json where it is supported and Json.Net where it's not supported.

**Comment by abatishchev** [comment]
Yes, I was also thinking about a parameterized tests. However it might not work for those which are already parameterized, and iirc there are already few of them.

Another option might be a base class. But again iirc MSTest doesn't like them and ignore the attributes when they aren't declared at a leaf of the inheritance tree.

I think the new serialzier must the default option but the other option should still be available. In next version we can move it to a separate project, effectively decreasing the number of dependencies.

**Comment by hartmark** [comment]
Yeah, having subclasses with MSTest is a pain I have experienced it myself firsthand :)

Perhaps we can migrate to Xunit for the tests so we easier can have subclasses for the tests.

We can use  Microsoft.Extensions.DependencyInjection and just have the DI resolve the injection of the correct serializer the user have choosen.

 Microsoft.Extensions.DependencyInjection  supports .net 4.6.2 the same as system.text.json so if we are on lower .net we just use JSON.net.

**Comment by abatishchev** [comment]
> Yeah, having subclasses with MSTest is a pain I have experienced it myself firsthand :)

Yes :(

> Perhaps we can migrate to Xunit for the tests so we easier can have subclasses for the tests.

Let's don't. I don't think it's worth the effort, plus I've already migrated to it and then from it. Don't want to go through this exercise all over again.

> We can use Microsoft.Extensions.DependencyInjection and just have the DI resolve the injection of the correct serializer the user have chosen.

Yes, I like this idea!

**Comment by abatishchev** [comment]
Ping on this idea.

**Comment by hartmark** [comment]
I got back from vacation this week so I'll take a look in a few days.

What made you abandon xunit btw?

**Comment by abatishchev** [comment]
tbh, I don't remember what was the exact trigger.

I always liked MSTest but back then it didn't support dynamic test data, xUnit did so I've switched. But then MSTest added the support and I've switched back. Plus a better VS and ADO integration and native support, if you will.

Also I work for Microsoft so don't mind using Microsoft own tools whenever possible :)
