### ISSUE TITLE
Security vulnerable in the decode method

### ISSUE THREAD

**Issue by bennybechdk** [jwt-dotnet/jwt#43]
The code is partly subject to the security attack described her:
https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
It is vulnerable to “If a server is expecting a token signed with RSA, but actually receives a token signed with HMAC, it will think the public key is actually an HMAC secret key.”

**Comment by abatishchev** [comment]
The problem is that this looks like a breaking but needed change. What should we do?

**Comment by bennybechdk** [comment]
I think Breaking change is OK, since it is a security problem.

Alternativly make methods with the old signature an mark them deprecated.

**Comment by abatishchev** [comment]
I see 2 options:

- make this change in the 1.x branch and bump the minor version to 1.4
- wait for the 2.x branch (I'm planning it) and make this change only there (to do the breaking changes properly).

Or a compromise:

- deprecate existing methods in 1.4, add new
- remove deprecated methods in 2.0

**Comment by abatishchev** [comment]
If the later sounds good to you too, can you rebase your fork and make the necessary changes, please?

**Comment by bennybechdk** [comment]
Sorry for the late answer.
I think vincentparrett can do the rebase (it is his changes you ar reffering to)

**Comment by abatishchev** [comment]
Oh, right, it's @vincentparrett's changes. Can you please come back on this and help to resolve this issue?

**Comment by alexfoxgill** [comment]
I didn't think this library supported RSA? It's not listed in the JwtHashAlgorithm enumeration. So any server using this library won't be expecting RSA and therefore is not exposed to the bug

**Comment by abatishchev** [comment]
Indeed it doesn't (yet).
