### ISSUE TITLE
Decode symetric key without secret throws unhelpful error since v9.0.0

### ISSUE THREAD

**Issue by spricesoft-samuel** [jwt-dotnet/jwt#434]
The exception is 'Specified argument was out of the range of valid values. Arg_ParamName_Name'

I tracked it down to the ValidSymmetricAlgorithm method which is expecting a non-null value for the keys argument.

**Comment by abatishchev** [comment]
Hi! Thanks for reporting this issue. Can you please try the latest beta version? Let me know if the exception message doesn't improve.
