### ISSUE TITLE
Using a 32-bit key as certificate

### ISSUE THREAD

**Issue by luigisirito** [jwt-dotnet/jwt#440]
Is there any way to use a 32-bit key generated by http://jwtbuilder.jamiekurtz.com/ or other online generator?
i.e.    ` uqQMAr17zI1VTrRXn35J6dcxzhx1KemM`
Should we save it as RSA Key or other type?

Thank you

**Comment by abatishchev** [comment]
hi!
The length of they private key which is 256, 385, 512 bits, etc.
32 on that UI seems to correspond to the length of the secret in characters, not bits :)

Here's what you'd need to use:

https://github.com/jwt-dotnet/jwt/blob/e59150f9e203182f9957d1697b11ff09384166df/src/JWT/Algorithms/HMACSHAAlgorithmFactory.cs#L7

But but but. I strongly discourage from using HM aka HMAC SHA. Those are rather "encoding" than "encryption". Means your secret isn't such, is trivial to be forged.
