### ISSUE TITLE
There is no way to destroy jwt token

### ISSUE THREAD

**Issue by Monica093A** [jwt-dotnet/jwt#444]

**Comment by abatishchev** [comment]
Can you please elaborate? A jwt is just a string.

**Comment by Monica093A** [comment]
Dear Jwt-Dotnet/Jwt,
Thanks for your email
i need to deactivate jwt token on logout, there is no methods/ functions
available to destroy/ deactivate generated jwt token before expiration time

**Comment by abatishchev** [comment]
The standard doesn't have such functionality. And it's a known issue: once the token is issued - there is no way to control or retract or revoke it.

Perhaps what you can do is to set short expiration date and store the token in local or distributed cache until it expires, check against it whenever needed.
