### ISSUE TITLE
JWT works with unity? and how could I implement it?

### ISSUE THREAD

**Issue by BabyWhite69** [jwt-dotnet/jwt#446]
Hello everyone, I would like to know if Jwt works with unity, specifically I ask this question because I tried to implement it in unity to create a jwt with a private key using openssl from a server in Unity and send it to an api with node.js to do the verification of the jwt with the public key, but I encountered some problems, the main problem was with Newtonsoft.Json and System.Text.Json, unity found inconsistencies which did not allow me to compile.

> _Note: I checked the questions for this issue in Github but I could not find a solution, if anyone has any guide to do it I would appreciate it very much, thanks!_

**Comment by BabyWhite69** [comment]
Hello @abatishchev thank you very much for answering my question.
I am using the version released in Nuget 9.0.3 and Unity version 2021 LTS.
I will try again with the beta version and report as soon as possible the results, greetings!

**Comment by BabyWhite69** [comment]
I made a new project in Unity using version `2021.3.11f1 LTS`, I downloaded the latest beta version from nuget and extracted the `JWT.dll` file from `lib/netstandard2.0` and introduced it to unity, when I did that I got this error (note that I tried with the last 3 beta versions and with all the dll inside the `/lib` folder just in case).

![image](https://user-images.githubusercontent.com/80644505/198158740-c6271aab-52ca-4e33-9a83-caaea1132141.png)

I also used [NugetForUnity](https://github.com/GlitchEnzo/NuGetForUnity) to install packages directly to Unity without extracting them and when I do this I get these errors for multiple dlls with the same name

![image](https://user-images.githubusercontent.com/80644505/198158788-ab920aed-e88f-42dd-9287-52b3bc5e42b3.png)
![image](https://user-images.githubusercontent.com/80644505/198158804-fe8b17ba-28d5-4215-bb3d-4eccd066a104.png)

Also when deleting all the folders and leaving only the JWT folder in its beta version, I get the same error as the first one.

![image](https://user-images.githubusercontent.com/80644505/198158869-eed27d22-59f9-4ac3-9aef-9c0d1805847d.png)

**Comment by abatishchev** [comment]
To be honest, I'm not very familiar with Unity. Even less with Unity Editor and how it handles NuGet packages. Back in the day, .NET 3.5 (see https://github.com/jwt-dotnet/jwt/pull/270) was re-added for Unity specifically, since I haven't heard of any problems (or anything at all) from Unity users.

What's the target framework of your project? I see one of the errors says System.Text.Json is unsupported. Per the [official dependencies list](https://www.nuget.org/packages/System.Text.Json#dependencies-body-tab), it's supported on:

- .NET Framework 4.6.2
- .NET Standard 2.0
- .NET Core 3.1/6

You cns see the exactly same list here:

https://github.com/jwt-dotnet/jwt/blob/96e61e12cdd0921792325e23d82f175551854d63/src/Directory.Build.targets#L5

(except .NET Core 3.1 which though shouldn't matter in your case)

Do you know what's the version of Json.Net Unity includes by default or your projects includes? Because the another error complains about two versions added same time.

Here's the version references by the latest version of JWT:

https://github.com/jwt-dotnet/jwt/blob/96e61e12cdd0921792325e23d82f175551854d63/src/JWT/JWT.csproj#L42

Usually a .NET project allows you to downgraded the version of a dependency by referencing a lower version explicitly. Do you reference any? I don't know how Unity works in this case. But at the end of the day, it should be a regular .NET DLL that follows .NET rules.

**Comment by BabyWhite69** [comment]
Well, I found [this guide in the Unity forum](https://forum.unity.com/threads/systen-text-json-net-standard-2-0.1224903/#post-7811574), simply download and add the dll's listed in the link below to solve those errors, now I have another problem, I try to use `Fluent Builder API` to create a token and send it to an api with nodejs which will validate the token with the public key of a certificate with openssl in pem format using rs256.

The first error I got was `cannot convert from 'string' to 'System.Security.Cryptography.RSA'` and to solve this [I used a question already posted](https://github.com/jwt-dotnet/jwt/issues/443) before, now when I do this I get the following error `CryptographicException: Unable to decode certificate` (Problems generating the certificate).

I will attach the code I currently have for testing purposes

```c#
using JWT.Algorithms;
using JWT.Builder;
using System;
using UnityEngine;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;

public class JWT_Test : MonoBehaviour
{
    public const string ServerRsaPublicKey2 = "MIIDfDCCAmSgAwIBAgIQQDCxkdjCQqmQsnSLtcHj3TANBgkqhkiG9w0BAQsFADA7MQswCQYDVQQGEwJ1czELMAkGA1UECBMCVVMxETAPBgNVBAoTCENlcnR0ZXN0MQwwCgYDVQQDEwNqd3QwHhcNMjAwMzIzMDI1NDAzWhcNMjMwMzIzMDMwNDAzWjA7MQswCQYDVQQGEwJ1czELMAkGA1UECBMCVVMxETAPBgNVBAoTCENlcnR0ZXN0MQwwCgYDVQQDEwNqd3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5hM+0cIjO0oLcxQPGdnSS0ZVJDSNVsPmtiXimSLhEIPczbZ35OSWa9PI+PRIztr/yjtwjTlCES4EjyEoJ8LYIQmGVLdYV5ULS/CyXVpgWpDdiSv6QOwB2qMv3mKiPcmaKxy+oo4zfihBqGkCC6QnspyvUFPZiWTx86Apw3u3WqBRE3HQ+PjMnjDSnWdPaAsb75ti61RU+9qYj3BwxDJR6xnAaYz1RSkxHOw4+Ty+/tNtObrZmTH7msVRpV7kMU1QgyD3Y2/JTTf3YUU0LCm1J+WJ0cMbVrILAvVlOQnRn3IlcI1LOL/e6XEyET5tVymv8S5EoJjGf2o8VnTsF3vttAgMBAAGjfDB6MA4GA1UdDwEB/wQEAwIFoDAJBgNVHRMEAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBTTMvXgytSFWwQk58CpxCpZAr5G1jAdBgNVHQ4EFgQU0zL14MrUhVsEJOfAqcQqWQK+RtYwDQYJKoZIhvcNAQELBQADggEBAK5vSwzh0x0pJm6njJX29rsd53ktyph+L90Enh0xzLFN0Ku9p+tM8E9TmKR+9ppdPqIEe4G/AuR1fHvmWenEw44M85Y/pBIPZDM2QVQngjg6iRQ42yD5hb/P4+UnvP9a5uI4Xc3f4NlJi3n54qBmdD5Hg52tNYgr8FKRoNzAoUCHelLk5PW0llF8Nc6cjJf0JfrSA1lVua488Dd34sPt798xM3IoISof1dqKslTypHP4BCyZ55SSfQJ+GrY7T9J3ct23BTrPnhhq0sPDogN4j258RmDriBGZmRcnrlmuBD5v+lvjYk0fISYNMfkrCQg5zae4d6BJIZVLY3gITGbaNoA=";
    private const string ServerRsaPrivateKey2 = "<RSAKeyValue><Modulus>uYTPtHCIztKC3MUDxnZ0ktGVSQ0jVbD5rYl4pki4RCD3M22d+TklmvTyPj0SM7a/8o7cI05QhEuBI8hKCfC2CEJhlS3WFeVC0vwsl1aYFqQ3Ykr+kDsAdqjL95ioj3JmiscvqKOM34oQahpAgukJ7Kcr1BT2Ylk8fOgKcN7t1qgURNx0Pj4zJ4w0p1nT2gLG++bYutUVPvamI9wcMQyUesZwGmM9UUpMRzsOPk8vv7TbTm62Zkx+5rFUaVe5DFNUIMg92NvyU0392FFNCwptSflidHDG1ayCwL1ZTkJ0Z9yJXCNSzi/3ulxMhE+bVcpr/EuRKCYxn9qPFZ07Bd77bQ==</Modulus><Exponent>AQAB</Exponent><P>2Mrzzbb8Gh7aoW0YXdtdO7WEZ7+pOvbxdp4Qw8sp8dF5cF5vss3I2FoJ9kssy/DsUsreBUhD0HKrADBus7BHKXp7Q/9hhu1nAJxpng255cUfngVD9k1xQdfWEHCeWrr7XJHcplTkh4ysH4nWK+8S+RoCpiuphkJJqVxPzDaY1+M=</P><Q>2xHwflmaMbNs9dXi3wx10SyG5KQJeRIXlKkhlUYlAU+7598AdmTiUPHfhj4WDRCmcJGHjSWqdiuQuwmRYsBXRhtk7XjGAjcefloSpXSR9G+tpVFuIthBU337g2pK1o8z/29LKiWZvcytgxQLEWwGIyduj2I9BoDw1jgFmVd/IG8=</Q><DP>b9n+ghO37G4g1QqpeLtWVhkoEDNFyANiv5V8BtjKclZmdoBy1ujviBikbSuKGErcUzcR593KB0EyUu2qIBGCFbd447NeiTPxYdJRd9eTIyZaUrhawThhh9wpOOAyA5PXXoJvOm4wXnNI1xjRpGc7/cPavAto8rk+sh/LmAxPPYs=</DP><DQ>b2l2N6v2IWSw+22lje5WVOUiTVGnh61N1MsXS0V7OGmGlOvy3kN8XdJE7Y7RxB89pm480+neAW8ykgzRpblQKVVxRNxxR1sk5PmGFiNsvzW0yCjbrFjzEDU4HqOGIAyAU14UigDJaZ+YdttQrbGUhXheYAmEI7SbxzaCknPPMX0=</DQ><InverseQ>SpRpqI+Z4g3jMbb0iE0oD+FAUaBXGp00DjKVbeYH8WQl2rVGFkspFYeN69u3ZFUL3JJd4rCF6zbuLq6iyDJq/F+Jo4zSzXChepr/dSEH1TszaA6imdqFyj3pjOT/ZXNK4YPCRijRM3fy8GdNybZDQljL1djY8D1YK3CWEtKuogs=</InverseQ><D>ADJKztC1SseTfRmPgnZ+DLXAgbflpK6WS3+/9/UcKAsc5LOmA8bytwvkjpPqYNGkH5g7iKU8yP16rbrSXgy6NJ7VYAVENJIhYWKdxxJzAMfvVkeCc4A/sa1GFThwXUG5KBND7EExrsu3oe67LyhOBJXv7vHCvQhSwkZNbiDEtOh7y6bKOOb0aluzPir3eY3HyN7TP2uS5mEeokMvwk9yGOUvCeKoz8t9WJf8HoP2OsDqFsbs5qA66qC6DWaU9OZ0VrO3zgmceIDP2ZXFkWmz2cVJ/Yvfi5zCvc0+g670twnuG8P00Syr/3xNCVuhwwuZbDcILjNvc9uOu9iDbY5xZQ==</D></RSAKeyValue>";
    public static readonly X509Certificate2 CertificateWithPrivateKey = CreateCertificate();

    private void Start()
    {
        Test();
    }

    void Test()
    {
        var token = JwtBuilder.Create()
                        .WithAlgorithm(new RS256Algorithm(CertificateWithPrivateKey))
                        .AddClaim("exp", DateTimeOffset.UtcNow.AddHours(1).ToUnixTimeSeconds())
                        .Encode(); 

        Debug.Log(token);
    }

    private static X509Certificate2 CreateCertificate()
    {
        var rsa = RSA.Create();
        rsa.FromXmlString(ServerRsaPrivateKey2);

        var certPub = new X509Certificate2(Convert.FromBase64String(ServerRsaPublicKey2));
        var certPriv = new X509Certificate2(certPub.CopyWithPrivateKey(rsa).Export(X509ContentType.Pfx));

        return certPriv;
    }
}
```

**Comment by abatishchev** [comment]
@BabyWhite69 can you please post the second half of your latest comment as a separate issue? Or you got it working?

**Comment by BabyWhite69** [comment]
✅**Solution**

If you want to implement JWT to Unity and you get the same error posted mainly in this question, here is the solution:

> To use System.text.json you need to download all it dependencies into too:
> - Microsoft.Bcl.AsyncInterfaces (NET Standard 2.1 version if you on Unity 2021.2)
> - System.Buffers (not required if you on Unity 2021.2)
> - System.Memory (not required if you on Unity 2021.2)
> - System.Numerics.Vectors (not required if you on Unity 2021.2)
> - System.Runtime.CompilerServices.Unsafe
> - System.Text.Encodings.Web
> - System.Threading.Tasks.Extensions (not required if you on Unity 2021.2)
> 
> with all this libraries you should be able to use System.Text.Json.

This solution was taken from a Unity forum, if you want to see the whole discussion [click here.](https://forum.unity.com/threads/systen-text-json-net-standard-2-0.1224903/)

**Comment by abatishchev** [comment]
Awesome, thanks a lot! I'll use your posting as a reference next time someone asks about Unity.

Since you've got it working, please don't hesitate to ask more questions about the library itself.
