### ISSUE TITLE
Support for .NET 7.0

### ISSUE THREAD

**Issue by PMendesWebDev** [jwt-dotnet/jwt#451]
Will there be a release for .NET 7.0?

**Comment by abatishchev** [comment]
Hi and thanks for checking on.
While I'd agree that the new major version release could've been the best time to add a new target framework, my question and argument against doing that would be this: would it be really necessary and beneficial? In other words, what would be the difference for an application targeting 7.0 when the library targets 6.0 or 7.0? To my knowledge, it'll work the same way. No?

**Comment by PMendesWebDev** [comment]
Hey there! 

Thanks for the fast reply.

I could be being a complete noob on this, but I'm not able to install JWT on my project because it doesn't target .NET 7.0 (at least it won't show in nuget library)

**Comment by PMendesWebDev** [comment]
I used vs' nuget package console and it did let me install it.

I'll try to work with it and see if it's all good :)

Thanks for the reply!

**Comment by abatishchev** [comment]
Happy to help, let me know if you run into any other issues.
