### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by cmeeren** [jwt-dotnet/jwt#452]
Just noticed that 9.0.3 was outdated because 10.0.0 is released. Came here to find out what the changes were (in particular, what the breaking changes were, since the major version is bumped). But the only information I can find is auto-generated changes in the [GitHub releases](https://github.com/jwt-dotnet/jwt/releases), which 1) is time-stamped and do not refer to any version, so I have no idea which releases I should compare, and 2) is auto-generated, so it contains a lot of unnecessary noise ("drop beta prefix", "add table of contents to readme", etc.), so I don't really know what the actual relevant public changes are.

What are the changes (in particular, the breaking changes) in v10, and would it be possible to keep a proper changelog (preferably curated, but at the very least one that references actual version numbers) going forward?

([Here are tips for keeping a changelog](https://keepachangelog.com/en/1.0.0/), but that's just one suggestion.)

**Comment by abatishchev** [comment]
Hi Christer,
I think it's a fair ask and would be a good sign of the maturity of the project. It's a one-man show so please don't judge :)
I'll try to keep the record of the changes going forward.

Here's the [Azure DevOps VSRM pipeline](https://dev.azure.com/abatishchev/OpenSource/_releaseDefinition?definitionId=2&_a=definition-tasks&environmentId=2] I'm using to generate a GitHub release before publishing any of the NuGet packages. Any suggestions or improvements are very welcome? Overall, it needs to be replaced with a YAML-based pipeline (see #426k), so any contractions are very welcome too!

**Comment by cmeeren** [comment]
Thanks a lot! Would be great if the changelog contains the (user-relevant) changes from 9.0.3 to 10.0.0, too. 🙂

Personally I just keep a manual changelog for all my projects. I have found that to be both simple and adequate.

**Comment by abatishchev** [comment]
Yes, I'll fill it out for the most recent release too.

**Comment by cmeeren** [comment]
Would it be possible to just get a quick-and-dirty list of the important changes here, until the changelog is published with this information? At least the breaking changes? I've got alerts nagging me to update the outdated JWT 9.0.3 package... 🙂

**Comment by cmeeren** [comment]
Thanks. I see that the .NET 6 target in the NuGet package also has a dependency on System.Text.Json. That's actually not necessary; .NET 6 has it bundled, so the NuGet dependency on STJ can be removed from that target. (This may also be the case on `netstandard2.0`; not sure).

**Comment by abatishchev** [comment]
Would you please contribute and make the necessary changes? I'd join and release it asap.

**Comment by cmeeren** [comment]
I'll try to do that. Currently setting up a new PC, so may not be able to get to it today.

**Comment by cmeeren** [comment]
> Would you please contribute and make the necessary changes? I'd join and release it asap.

I see that the project already uses conditions with custom constants (e.g. `MODERN_DOTNET`) to include/exclude System.Text.Json (among other thing). Since this is non-stndard, I will therefore leave it to you to choose how to best adjust the conditions.

Note that `netstandard2.0` does not contain STJ. Of the current targets, only net6.0 does.
