### ISSUE TITLE
Discussion - what the relation to 'System.IdentityModel.Tokens.Jwt'

### ISSUE THREAD

**Issue by ronaldhoek** [jwt-dotnet/jwt#455]
MS currently has it's own JWT library 'System.IdentityModel.Tokens.Jwt'.

How should I compare this library to the one from MS: aka advantages vs disadvantages?

**Comment by abatishchev** [comment]
Hi,
This library predates System.IdentityModel.Tokens.Jwt. But then didn't have support for asymmetric algorithms for a while (then I took over the maintenance and added it).
It's a fully open source project, maintained by 1 volunteer (me).
So I'd recommend using Microsoft's package, untill you feel special about supporting (and expanding) an OSS project, what's always very welcome.

**Comment by ronaldhoek** [comment]
Thanks for the clarification @abatishchev 

I'll be sticking with the MS lib then ;)
