### ISSUE TITLE
Base64UrlEncode - Should consider trailing = character

### ISSUE THREAD

**Issue by anilat007** [jwt-dotnet/jwt#46]
When trying to decode segments of JWT token (first two segments) using other libraries, an exception is thrown saying invalid input or illegal base64 string. It happens since we are not considering trailing equals (=) character while encoding (in method public static string Base64UrlEncode(byte[] input)).
Please look into this and if possible then try to provide an overload so that we don't break existing clients.

**Comment by abatishchev** [comment]
The comment in code says this was done intentionally to follow the Jwt spec. Do you know whether this is correct?

**Comment by EdSF** [comment]
@anilat007 The segments of `JWT` are `base64url` encoded. If you need `base64` see [JWT.Base64UrlDecode](https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JWT.cs#L214).

Hth.
