### ISSUE TITLE
Transfer project's ownership to the community

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#47]
Hi @mikelehen,
It seems you've abandoned this project. It's great, and I'm sorry to see it stalled!
What do you think if the community would pick it up? To few maintainers such as myself. We could review the pull requests, answer the questions, etc.

**Comment by abatishchev** [comment]
@johnsheehan, apparently you were the initial author. Do you have any ideas here? Can you help?

**Comment by johnsheehan** [comment]
I've added you. Don't break backwards compatibility :) I have no idea what needs to be done to send updates to Nuget anymore.

**Comment by abatishchev** [comment]
Awesome! Thanks for the trust.

Can you please also add me to [the nuget package](https://www.nuget.org/packages/JWT/)? Same username, [abatishchev](https://www.nuget.org/profiles/abatishchev).

**Comment by abatishchev** [comment]
@johnsheehan can you please check that the Maintainers group has the write permissions? I still don't have it, can't merge PRs.

**Comment by johnsheehan** [comment]
Fixed

**Comment by abatishchev** [comment]
@johnsheehan hi, can you please add also @nbarbettini, he'll help to setup CI/CD? Or grant me the permissions to do so?
