### ISSUE TITLE
Why has the HMAC SHA algorithm become obsolete?

### ISSUE THREAD

**Issue by s-shin** [jwt-dotnet/jwt#470]
In the current implementation, all HMAC SHA-based algorithms are considered unsafe and obsolete.

https://github.com/jwt-dotnet/jwt/blob/9cd3ed81f345fc9e5fc653c8f7fdd570ada23eaa/src/JWT/Algorithms/HMACSHAAlgorithm.cs#L9

https://github.com/jwt-dotnet/jwt/blob/9cd3ed81f345fc9e5fc653c8f7fdd570ada23eaa/src/JWT/Algorithms/HMACSHA256Algorithm.cs#L9-L10

However, in my research, I could not find information that HMAC SHA-based algorithms except HMAC SHA1  are considered unsafe.

Will these obsolete codes be removed in the near future?

**Comment by abatishchev** [comment]
Hi,
Please see my response to a similar question here: https://github.com/jwt-dotnet/jwt/pull/384#issuecomment-1325905125
Let's continue the discussion there.

And to answer your another question: no, they won't be removed any time soon.

**Comment by s-shin** [comment]
Alright, and I commented there :D
