### ISSUE TITLE
InvalidOperationException occurs in Decode() after DecodeHeader().

### ISSUE THREAD

**Issue by s-shin** [jwt-dotnet/jwt#471]
In version 20230131.15,  `InvalidOperationException` occurs by `JwtBuilder.Decode` if `JwtBuilder.DecodeHeader` was called before it.

It is caused by the flow:

```
DecodeHeader
  -> EnsureCanDecodeHeader
    -> TryCreateDecoderForHeader (in first call of Decode or DecodeHeader)
      -> _decoder is initialized.

then,

Decode
  -> EnsureCanDecode is skipped because _decoder is initialized.
  -> CanDecode
    -> returns false because _validator is null.
  -> InvalidOperationException
```

It can be fixed by replacing `EnsureCanDecodeHeader` in `DecodeHeader` to `EnsureCanDecode` though I don't know yet it is the best implementation in this library.

**Comment by abatishchev** [comment]
Hi,
Thanks for using the library and reporting back the issues you're seeing.
I would say this behavior is _by design_. Let me explain.
The number of dependencies needed to decide just a header is much small than to decide a payload. What means that the user would need to specify those dependencies anyway, even if was going to decide a header only.
In other words, an instance of the builder that was created for decoding only a header can't be reused.
However, I see an option for improvement: the order of the methods being called should not matter.
Would you please submit a PR that would check for the presence of the necessary dependencies and initialize the decoder accusingly?

**Comment by s-shin** [comment]
Sorry, but for various reasons, I will not be using this library.
Therefore, my motivation to contribute becomes low.
However, I am putting a patch here as a possible fix (not a PR, as it is not of mergeable quality) to help anyone who wants to work on this issue in the future.

https://github.com/jwt-dotnet/jwt/compare/main...s-shin:dotnet-jwt:make_decode_callable_after_decode_header
