### ISSUE TITLE
How to enable MODERN_DOTNET?

### ISSUE THREAD

**Issue by andreijw** [jwt-dotnet/jwt#474]
I was looking through the code, and I saw that the work to add the System.Text.Json package has already been completed. However, it seems that it's all wrapped behind a precompiled directive "MODERN_DOTNET". I'm wondering how can that MODERN_DOTNET directive be defined in the nuget so that when I import the nuget from my dotnet 8.0 project, I get all the features I need. I was thinking of forking the repo, adding the dotnet 8.0 target, and defining that constant in the csproj file. Is there a better way? Thanks a lot.

**Comment by abatishchev** [comment]
hi @andreijw,
here's the code:

**Comment by abatishchev** [comment]
If your project targets `net8.0` and references JWT, it'll automatically references the `net6.0` version which includes all the latestr features.

**Comment by abatishchev** [comment]
See also the discussion for .NET 7.0: https://github.com/jwt-dotnet/jwt/issues/451

**Comment by andreijw** [comment]
Thanks a lot @abatishchev, this was very helpful.
My next question now, is using the dotnet 8.0 AOT features I have come into a lot of serialization issues. I found a way around it, but it requires adding a Parameterless constructor annotated as a JsonConstructor using System.Text.Json

An example would be in the JWT/Builder/JwtHeader.cs :

`#if MODERN_DOTNET
        [System.Text.Json.Serialization.JsonConstructor]
#endif
        public JwtHeader() { }`
        
 I propose making a PR to add this in order to accommodate anyone using AOT.

**Comment by abatishchev** [comment]
Sure thing, a contribution is very welcome!

Can you please close this issue (as it was mostly about .NET 8), open a new one (for the AOT/serialization issues), and then submit a PR which would reference/resolve the new issue.
