### ISSUE TITLE
Strong named assembly

### ISSUE THREAD

**Issue by niksedk** [jwt-dotnet/jwt#48]
Hi,

Is (or could there be) a strong named version?

I'm getting this error:
Could not load file or assembly 'JWT, Version=1.3.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by johnsheehan** [comment]
If you want a strong-named version, pull the source and build it with the key you'd like to use.
