### ISSUE TITLE
Having trouble with first example Encode()

### ISSUE THREAD

**Issue by derekantrican** [jwt-dotnet/jwt#481]
This is the first example in the README:

https://github.com/jwt-dotnet/jwt/blob/bc9d9d205762d134aab82aacd36fedb0877dbfd3/README.md?plain=1#L100-L108

But (other than `certificate` not being defined) it looks like this has a problem because from what I can see, `encoder.Encode` takes 3 arguments, not 1: https://github.com/jwt-dotnet/jwt/blob/main/src/JWT/JwtEncoder.cs#L44 . Maybe I am missing some reference?

**Comment by abatishchev** [comment]
hey @derekantrican, thanks for reporting the issue! Can you please try the updated version from #482?

**Comment by derekantrican** [comment]
@abatishchev Yep - thanks!
