### ISSUE TITLE
System.Text.Json should only be a dependency for .NET standard

### ISSUE THREAD

**Issue by thompson-tomo** [jwt-dotnet/jwt#496]
**Describe the problem you are trying to solve.**
I do not want STJ listed as a dependency for net 6

**Available workarounds**
Accept un-necessary dependency

**Additional context**
N/a

**Comment by abatishchev** [comment]
Hi!
Can you describe the issue more? What's wrong with a dependency to a standard library such as STJ?
Originally and till today, the library depends on NS.J. It was a community's request to add STJ. So now we have 2.
Neither is a part of the .NET Standard, which is dead anyway, the recommendation by the .NET team to target the full framework directly, this is what the library does nowadays.

**Comment by abatishchev** [comment]
I'd you feel super strong about this, please consider implementing #76.

**Comment by thompson-tomo** [comment]
@abatishchev we don't need to go too those lengths, simply adjusting the conditions on the package is sufficent as proposed in #497
