### ISSUE TITLE
RFC: Ideas for v. 2.0

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#55]
- ~~Go away from static API in favor of instance-based API with a number of separate classes~~:
  - `JwtEncoder : IJwtEncoder`
  - `JwtDecoder : IJwtDecoder`
  - `JwtValidator : IJwtValidator`
- ~~Mark static API `[Obsolete]`~~
- ~~Make static API a wrapper on top of instance-based API~~
- Remove static API in the future versions (such as 2.1 or 3.0)

**Comment by abatishchev** [comment]
* Replace MSTest with xUnit

**Comment by abatishchev** [comment]
* Make v2 portable or .NET Core compatible or both
 - Community contribution would be needed, I have no experience here (yet)

**Comment by abatishchev** [comment]
* Rebrand *Jwt implementation for .NET* as *Jwt.Net*
 - This repo always belongs to the jwt-dotnet organization but now do this officially, i.e. everywhere including readme and nuget package's name and description
 - Other options: Jwt.NET, JWT.NET, JWT.Net

**Comment by abatishchev** [comment]
* Inject `IJsonSerializer` into ctors of `JwtEncoder` and `JwtDecoder`
 - Or split it into two: `IJsonSerializer` and `IJsonDeserializer`
* Rename it to `IJwtSerializer` to have consistent naming?

**Comment by abatishchev** [comment]
* Set `[AssemblyVersion]` to 2.0.0.0 and never change

**Comment by abatishchev** [comment]
* Replace `JavascriptSerializer` with Json.Net

**Comment by alexfoxgill** [comment]
A suggestion:

* Remove the direct dependency on DateTime.UtcNow

**Comment by abatishchev** [comment]
Can you please explain why, what is the intend? Currently it calculates the difference between UcNow and the start of UNIX epoch fot token expiration.

**Comment by alexfoxgill** [comment]
Mainly for the ability to mock while testing:

* http://stackoverflow.com/questions/2425721/unit-testing-datetime-now/2425739#2425739
* https://blogs.msdn.microsoft.com/ploeh/2007/05/12/testing-against-the-current-time/

There may be other uses but in general it's a good idea to use dependency injection for things that can't be mocked, or at least to provide some method for doing this if it's not the default

**Comment by abatishchev** [comment]
Oh, right, Of course. I thought maybe you just have some other thoughts/needs. I usually do this:

```csharp
public interface IDateTimeProvider
{
	DateTime GetNow();
}
public sealed class UtcDateTimeProvider : IDateTimeProvider
{
public sealed class UtcDateTimeProvider : IDateTimeProvider
{
	public DateTime GetNow()
	{
		return DateTime.UtcNow;
	}
}
```

**Comment by alexfoxgill** [comment]
Another suggestion:

* `TryDecode` method which does not need to be wrapped in a try-catch to handle invalid tokens

**Comment by xori** [comment]
JWT doesn't encrypt any data, it just signs it. So Decode/Encode is correct according to your given definitions.

**Comment by abatishchev** [comment]
I created a branch https://github.com/jwt-dotnet/jwt/tree/v2 to start making the changes

**Comment by abatishchev** [comment]
Pushed 2.0.0-beta to NuGet https://www.nuget.org/packages/JWT/2.0.0-beta

**Comment by nbarbettini** [comment]
FWIW, I like **JWT.NET** as the name for v2, as I think it's the most consistent with the conventions for both JWT and .NET.

**Comment by abatishchev** [comment]
Do you mean that you like JWT.NET more than Jwt.Net?

**Comment by nbarbettini** [comment]
Yep! JWT.NET would be my vote. :)


On Mon, Mar 6, 2017 at 16:55 Alexander Batishchev <notifications@github.com>
wrote:

Do you mean that you like JWT.NET more than Jwt.Net?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jwt-dotnet/jwt/issues/55#issuecomment-284585405>, or mute
the thread

**Comment by abatishchev** [comment]
Cool, thanks for the input. It's in beta now so still counting the votes. Would love to have more inputs. I basically don't mind either.

**Comment by nbarbettini** [comment]
Awesome! I'm excited to see this project rev to v2. Looking forward to
contributing some code.

**Comment by abatishchev** [comment]
Сontributions of all sorts are welcome! If you're interested, there are few stalled prs which have to be rebased.
