### ISSUE TITLE
1.3.5-beta nupkg has no DLL

### ISSUE THREAD

**Issue by claytondus** [jwt-dotnet/jwt#56]
Installing the 1.3.5-beta nupkg via VS 2015 NuGet does not extract a DLL into the lib directory.  1.3.4 of course works correctly.

**Comment by abatishchev** [comment]
Thanks for reporting! Will take a look what's wrong shortly.

**Comment by abatishchev** [comment]
This has been addressed in https://github.com/jwt-dotnet/jwt/pull/57. I pushed new package version 1.3.5-beta2 and unlisted the previous version. Please check and let me know!

**Comment by claytondus** [comment]
Thanks for a very quick resolution!
