### ISSUE TITLE
I can't find FluentAssertions.Core,FluentAssertions and ServiceStack.Text libs; 

### ISSUE THREAD

**Issue by 243001806** [jwt-dotnet/jwt#58]
![image](https://cloud.githubusercontent.com/assets/15725713/18657261/07d86fb4-7f2b-11e6-88d1-da8510ebea2c.png)

**Comment by abatishchev** [comment]
Do you try to build from the source? You need to restore nuget packages first, VS should do it automatically on first build attempt.

**Comment by 243001806** [comment]
What is your vs version?my is vs 2013,you mean 
 or 
![image](https://cloud.githubusercontent.com/assets/15725713/18660286/354fe848-7f42-11e6-8df1-2c2dc1fa203a.png)

**Comment by abatishchev** [comment]
Please explain what you're trying to achieve

**Comment by 243001806** [comment]
![image](https://cloud.githubusercontent.com/assets/15725713/18660473/369706ae-7f43-11e6-9a7f-f6dd41ad8dba.png)

**Comment by 243001806** [comment]
my English is just so-so!hope you know what i say!

**Comment by abatishchev** [comment]
I don't understand, please type. Also see http://stackoverflow.com/a/13248550/41956

**Comment by 243001806** [comment]
thanks for your help!

**Comment by abatishchev** [comment]
You're welcome!
