### ISSUE TITLE
Bug or question: Altering last meaningful character in base64 string doesn't change decoded outcome

### ISSUE THREAD

**Issue by Lamando** [jwt-dotnet/jwt#65]
after i used the function `Encode()` i got the token:

>eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7IlVzZXJfTmFtZSI6ImV0YWciLCJVc2VyX0lkIjoxMDMsIlVzZXJfQWNjZXNzIjowfSwiZXhwIjoxNDgyMjA4NjM5fQ.I_aeBp9A2O2tl7VsrN0aTnHSu4Frygp25IIf6_lcixw

if i change the last char of token, e.g.:

>eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7IlVzZXJfTmFtZSI6ImV0YWciLCJVc2VyX0lkIjoxMDMsIlVzZXJfQWNjZXNzIjowfSwiZXhwIjoxNDgyMjA4NjM5fQ.I_aeBp9A2O2tl7VsrN0aTnHSu4Frygp25IIf6_lcixx

you see i replaced last char 'w' to “x‘,  then i use the funciton `DecodeToObject()`, now i still get the correct object, maybe i used a wrong method, but how did it happened?

**Comment by abatishchev** [comment]
Hi, what's the value of parameter `verify`?

**Comment by Lamando** [comment]
here is my code:

`            UserModel u = new UserModel()
            {
                 User_Name = username,
                 User_Id = userid,
                 User_Access = useraccess
            };
            var unixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            var expirs = Math.Round((DateTime.UtcNow - unixEpoch).TotalSeconds + 7200);

            var dataload = new Dictionary<string, Object>() 
            {
                {"user", u},
                {"exp", expirs}
            };

            string secretKey = "krBVvVDwiFu0TX1JebM5gYOXuOPjHN0xsKctsDQG";
            string token = JWT.JsonWebToken.Encode(dataload, secretKey, JWT.JwtHashAlgorithm.HS512)`

and then  here is the verification code:
`
                var data = JWT.JsonWebToken.DecodeToObject(token, sercretKey) as IDictionary<string, object>;
                var  u = data["user"] as IDictionary<string, object>;
                
                if (u != null)
                {
                    string name = u["User_Name"].ToString();
                    int userId = Convert.ToInt32(u["User_Id"]);
                    string type = u["User_Access"].ToString();
               }`
so if i change the token  as  my above , the name,userid, type  all will not be changed! verification is still successfull。

**Comment by abatishchev** [comment]
Hi, I'm sorry, it took some time to me to find some free time to look at this.

I turns out that changing the last meaningful character (i.e. `A==` to `B==`) in a base64-encoded string doesn't change the encoded outcome:

    Enumerable.SequenceEqual(
      Convert.FromBase64String(
        "bOKkXWNBH/luDAwLkQcMmOuKWGC4Wz3mOnQNwng4gIfC2WxgRMi//kITA7yuJkmovgTvPNjdocftlwvwtW8anA==),
      Convert.FromBase64String(
         "bOKkXWNBH/luDAwLkQcMmOuKWGC4Wz3mOnQNwng4gIfC2WxgRMi//kITA7yuJkmovgTvPNjdocftlwvwtW8anB==")); // true

    Enumerable.SequenceEqual(
      Convert.FromBase64String(
        "bOKkXWNBH/luDAwLkQcMmOuKWGC4Wz3mOnQNwng4gIfC2WxgRMi//kITA7yuJkmovgTvPNjdocftlwvwtW8anA==),
      Convert.FromBase64String(
         "bOKkXWNBH/luDAwLkQcMmOuKWGC4Wz3mOnQNwng4gIfC2WxgRMi//kITA7yuJkmovgTvPNjdocftlwvwtW8anC==")); // true
