### ISSUE TITLE
Any plans to support .NET Core?

### ISSUE THREAD

**Issue by lskrajny** [jwt-dotnet/jwt#66]
as per title

**Comment by abatishchev** [comment]
Contributions are welcome! Eager to review and have it merged in. (I don't use Core in my day to day work so don't have any motivation to do it myself.)

**Comment by KANekT** [comment]
This is simple, but u must replace  System.Web.Script.Serialization to Newtonsoft.Json :(

**Comment by abatishchev** [comment]
Yes, in this is planned as part of v2, see https://github.com/jwt-dotnet/jwt/issues/55 I'll start making the necessary changes. Please feel free to for that branch and help me to convert the solution/project to Core.

**Comment by abatishchev** [comment]
Also see https://github.com/jwt-dotnet/jwt/pull/60
