### ISSUE TITLE
.Net 3.5 support?

### ISSUE THREAD

**Issue by Arkatufus** [jwt-dotnet/jwt#70]
Is there a way to download old versions that supports .net 3.5?

**Comment by Arkatufus** [comment]
Well, I'm trying to make an OpenID Connect plugin Unity3D, and Unity3D only supports 3.5

**Comment by abatishchev** [comment]
Since​ you're not using Jwt.Net from within Unity itself, rather with Unity, you still should be able to use the 2.x. Can't you? The apps that use your lib should target 4.6 as well but is it an issue? If yes, can you please explain further?

**Comment by Arkatufus** [comment]
What I ment by Unity3D was Unity3D the game engine, not the .Net DI container.

**Comment by abatishchev** [comment]
Yes, sure, I understand :) You can reference a lib targeted 3.5 and a lib targeted 4.6 in the same time if target 4.6 yourself. Right?

**Comment by Arkatufus** [comment]
Unity only supports mono .net 3.5, I can't target anything above that version. The unity engine actually comes with a modified fork of the mono compiler and compiles the C# source code when you build the game.
I don't think I can use a 4.6 lib with Unity at all, I was taught that to make a lib for Unity, you have to target for 3.5 or it wouldn't work.

**Comment by abatishchev** [comment]
See https://github.com/jwt-dotnet/jwt/pull/71

**Comment by Arkatufus** [comment]
Works perfectly, thank you :)
