### ISSUE TITLE
Enable CI/CD

### ISSUE THREAD

**Issue by nbarbettini** [jwt-dotnet/jwt#74]
It should be pretty easy to use travis-ci or AppVeyor to build this repo when code is checked in. Additionally, the CI script could produce the nupkg file automatically and push it somewhere like MyGet.

I've set this up before, so I'm happy to assist if you want to do this.

**Comment by abatishchev** [comment]
Would greatly​appreciate your help here. I'm familiar with TFS/VSO/TeamCity but never actually touched modern popular web-based systems such as those two.
Please configure them. I'll give the necessary permissions if needed, here or/and on NuGet.

**Comment by nbarbettini** [comment]
👍 I can work on this. Can you add me as a collaborator on the project?

**Comment by abatishchev** [comment]
I'm not the owner too, don't have the permission but asked to add your in #47

**Comment by abatishchev** [comment]
Hey Nate, did you have a chance to get any progress, or at least thoughts, on this?

**Comment by nbarbettini** [comment]
Sorry, I got busy over the weekend and didn't have a chance to look at it. I can work on it this week.

Here's what I've done in the past, let me know if this workflow sounds good:

* Write a build script using [cake](http://cakebuild.net/) that can build and test the project, and produce a nuget package. (This isn't 100% necessary, but it's nice to be able to have your CI tool call a single script)

* Enable the project in AppVeyor, and configure the AppVeyor build settings to run the cake script.

* Depending on whether you want to, AppVeyor can also be configured to automatically push packages to MyGet or NuGet. This way it's really easy to publish prerelease (or even stable) packages once you know all the tests pass.

**Comment by nbarbettini** [comment]
Also, we should merge #72 first because the build scripts will be different after that PR.

**Comment by abatishchev** [comment]
Sure, no problem at all, glad you're still here/ interested :)

I don't have any preferences for the framework to write  the build script for, whether it's cake, fake, or paket. Up to you and your experience.
I think perfect start would be to have a gated build that runs​ tests for every pull request. And then as a phase two, one click publish to NuGet.
Makes sense? What do you think?

**Comment by nbarbettini** [comment]
> I think perfect start would be to have a gated build that runs​ tests for every pull request. And then as a phase two, one click publish to NuGet.
> Makes sense? What do you think?

Sounds good! 👍

**Comment by nbarbettini** [comment]
Sorry for the long delay, it's been a busy week.

I made some progress on this, but I am going to wait until after #72 is merged as it requires a lot of changes to the cake build script. Easier to do it all at once.
