### ISSUE TITLE
Update to JSON.NET 10

### ISSUE THREAD

**Issue by nbarbettini** [jwt-dotnet/jwt#75]
There's a new major version of JSON.NET: https://www.nuget.org/packages/Newtonsoft.Json/10.0.1

Should this JWT >2.x depend on this? I tested it briefly and there aren't any problematic API changes.

**Comment by abatishchev** [comment]
I would build against the latest but do not limit dependency version in nuget since Json.Net is usually backward-compatible down to 6.x or even 4.x.

**Comment by nbarbettini** [comment]
I will do some testing and figure out how to widen the dependency version in the package 👍

**Comment by abatishchev** [comment]
Done in #83.
