### ISSUE TITLE
HMAC Algorithms

### ISSUE THREAD

**Issue by yoda** [jwt-dotnet/jwt#77]
Hi,

Was fiddling and noticed:

https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/HMACSHA384Algorithm.cs#L9
https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/Algorithms/HMACSHA512Algorithm.cs#L9

Where the HMACs should surely reflect the algorithm they are representing? Or am I missing something.

Regards,
Sam

**Comment by abatishchev** [comment]
Oh, yes, indeed! Seems to be my bad, just a copy/paste. Will fix shortly. Thanks!

**Comment by abatishchev** [comment]
Feel free to submit a pull request if you'd like.

**Comment by abatishchev** [comment]
Fixed by https://github.com/jwt-dotnet/jwt/pull/79

**Comment by abatishchev** [comment]
Published to NuGet as ver. [2.1.1](https://www.nuget.org/packages/JWT/2.1.1-beta)
