### ISSUE TITLE
Create a NuGet package for version 2.0.0

### ISSUE THREAD

**Issue by claudiobernasconi** [jwt-dotnet/jwt#80]
Hello. I am interested in working with Jwt.Net. On NuGet there is only v.1.3.4 in the stable channel, but v.2.1.1-beta in the pre-release channel. I am wondering if the 2.0.0 version is missing in the stable channel? From my perspective the version numer 2.1.1-beta tells me that 2.0.0 should be a stable release and could be added as a package to the stable channel.

Am I wrong?

**Comment by abatishchev** [comment]
Hi, I'm just little scared to push it to the stable channel. If you could give a try to the latest version and let me know if you face any issues. If none then it'll be a good sign to remove the beta suffix.

**Comment by claudiobernasconi** [comment]
Hi, it seems like I cannot work with your library because my project requires met to still work with the C# 5 compiler and your library seems to require at least C# 6. Therefore, I cannot give you any feedback whether you should remove the beta suffix. I honestly hope that I can use your library in the future for another project because it precisely solves what I was looking for.

**Comment by abatishchev** [comment]
Can you please describe further the issue(s) you're facing? Language version shouldn't matter. What might matter is target .NET Framework version. Are you limited to any prior to 4.6?

**Comment by claudiobernasconi** [comment]
I was on .NET Framework 4.5.2 and upgraded to 4.6.2. After that I received an error stating that language version property 6 was found but only up to 5 is supported. I am limited to work with Visual Studio 2013 for this project. So the use case is to have Visual Studio 2013 with .NET Framework 4.6.2 on a Windows 7 computer. I am aware of the fact that this is a legacy setup but I cannot change that fact. Maybe you want to look into it but I am not sure if it is even worth the work. Although it could be helpful to have a README entry which says if Visual Studio 2013 is supported or not.

**Comment by nbarbettini** [comment]
That is odd. I agree with @abatishchev that once the library is compiled, language version shouldn't matter.

Maybe it is a setting in your project, not the library? (see http://stackoverflow.com/a/39111514/3191599)

**Comment by abatishchev** [comment]
Spite it shouldn't be an issue with Jwt.Net, try [2.2.0-beta](https://www.nuget.org/packages/JWT/2.2.0-beta) which targets .NET 3.5 rather then 4.6.

**Comment by abatishchev** [comment]
Please let us know how it goes for you. Or I'll close the issue.

**Comment by claudiobernasconi** [comment]
As I stated above, I wrote a simple library for my use case. Nonetheless, I will try to test the behavior in Visual Studio 2013 during the next week. You can close the issue if I do not answer during the next week. Ok?

**Comment by claudiobernasconi** [comment]
I finally can confirm that with the newest version 2.3.0-beta it worked on my machine using Windows 7, .NET Framework 4.5.2 and Visual Studio 2013. It might be that something else was the reason why it did not work in the first place.

You can close this issue, but remember that is still no NuGet package for a 2+ version on the stable channel.

**Comment by abatishchev** [comment]
I'll publish one soon

**Comment by abatishchev** [comment]
[2.3.0](https://www.nuget.org/packages/JWT/2.3.1) (not beta) is out. Yay!
