### ISSUE TITLE
Readme/Docs don't match NuGet package

### ISSUE THREAD

**Issue by shawty** [jwt-dotnet/jwt#85]
Trying to use the library, looking at the samples in readme.md, quite impressed at how simple lib is to use.

Great, so I install NuGet package (1.3.4) according to my nuget, but when writing code, none of the interfaces in the samples are found.

Looked in the object explorer in VS15 and all i see is this:

![image](https://cloud.githubusercontent.com/assets/1876454/25048926/03d29954-2137-11e7-930f-b6fa102ccbf5.png)

Going into each of the classes etc I don't see any of the interfaces in the sample code anywhere:

![image](https://cloud.githubusercontent.com/assets/1876454/25049093/e600c4ae-2137-11e7-835e-c8c7767589a1.png)

Please advise, do I need a different version, or is their an issue here?

Cheers
Shawty

**Comment by abatishchev** [comment]
Hi Shawty,
Thanks for trying our lib out!

You installed ver. 1.3.4, the old version. The docs explains how to use the new version, 2.x.
before today it was only available from the pre-release channel. But I publish [2.3.1](https://www.nuget.org/packages/JWT/2.3.1) (not beta) just few minutes ago.

Please try again and let me know how it goes.

**Comment by shawty** [comment]
Hi Alexander,

Thanks for the prompt reply.

Just about to leave the office for the day now (It's bank holiday weekend here in the UK) so I'll try the new version once I get back, and let you know how it goes.

Regards
Shawty

**Comment by shawty** [comment]
Hi Alexander,

I can confirm that the version you've released now matches the documentation, and it all works very well. :-)

However, your NuGet config is screwing something up in NuGet somewhere.

If we browse, and search for JWT, it all shows up great

![image](https://cloud.githubusercontent.com/assets/1876454/25124185/ea121208-2422-11e7-90eb-a56edbace1e7.png)

(As you can see I have it installed)

However, IF you look at the installed version to the right, it tells me I have 2.3.1 installed, but the update version is 1.3.4.

That's not the main problem though.  After installing the latest version, if I now go to my installed packages, I get this:

![image](https://cloud.githubusercontent.com/assets/1876454/25124321/4397464a-2423-11e7-987e-c1d846a78d0c.png)

and it sits there forever, unless I remove JWT from my search, in which case I get this:

![image](https://cloud.githubusercontent.com/assets/1876454/25124365/677cc1d4-2423-11e7-8456-4f5171aacb9c.png)

If I close the solution, and remove JWT from my packages.config file:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="JWT" version="2.3.1" targetFramework="net461" />
      <package id="Nancy" version="1.4.3" targetFramework="net461" />
      <package id="Nancy.Authentication.Token" version="1.4.1" targetFramework="net461" />
      <package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net461" />
      <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />
    </packages>

so it reads:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Nancy" version="1.4.3" targetFramework="net461" />
      <package id="Nancy.Authentication.Token" version="1.4.1" targetFramework="net461" />
      <package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net461" />
      <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />
    </packages>

Then save it and reload my project, then my installed packages works as expected:

![image](https://cloud.githubusercontent.com/assets/1876454/25124627/3117190e-2424-11e7-8d91-194ba3ab7a07.png)

As soon as I do a search and re-install however:

![image](https://cloud.githubusercontent.com/assets/1876454/25124672/5a432764-2424-11e7-968d-e28457c72da8.png)

![image](https://cloud.githubusercontent.com/assets/1876454/25124710/77111afe-2424-11e7-8d85-84f9c231eada.png)

![image](https://cloud.githubusercontent.com/assets/1876454/25124759/92f8af52-2424-11e7-8afc-e6af635985c6.png)

Visual studio version Info should you need it:

![image](https://cloud.githubusercontent.com/assets/1876454/25124805/b2638768-2424-11e7-9ba4-0637a7bc9621.png)

I also have Resharper installed, in case that has any bearing (I know R# has caused NuGet probs in the past)

![image](https://cloud.githubusercontent.com/assets/1876454/25124875/f48d4282-2424-11e7-95cb-548097086e1a.png)

For the record, The JWT lib works fine once it's installed, just NuGet can't be used, to manage existing NuGet libs.

Shawty

**Comment by shawty** [comment]
Small update....

So I carried on working, and went to install another package tot he App I'm working on, this is what I got:

![image](https://cloud.githubusercontent.com/assets/1876454/25125803/059cb74e-2428-11e7-88ee-8f1ad73d97ba.png)

So whatever the issue is, it's preventing me from installing further packages to my project.

**Comment by shawty** [comment]
One last update, and here's how to fix it :-)

The problem is in your nuspec file.

where you have an asterisk to show you'll accept any version of newtonsoft JSON:

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
      <metadata>
        <id>JWT</id>
        <version>2.3.1</version>
        <authors>John Sheehan, Michael Lehenbauer, Alexander Batishchev</authors>
        <owners>johnsheehan, devinrader, abatishchev</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <licenseUrl>https://creativecommons.org/publicdomain/zero/1.0/</licenseUrl>
        <projectUrl>https://github.com/jwt-dotnet/jwt</projectUrl>
        <description>Jwt.Net, a JWT (JSON Web Token) implementation for .NET</description>
        <copyright>Public Domain</copyright>
        <language>en-US</language>
        <tags>jwt json</tags>
        <dependencies>
          <dependency id="Newtonsoft.Json" version="*" />  <<---- THIS LINE HERE
        </dependencies>
      </metadata>
    </package>

For some reason the * is not liked by my setup (Maybe others too), changing it to the last stable JSON.Net version:

    <?xml version="1.0" encoding="utf-8"?>
    <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
      <metadata>
        <id>JWT</id>
        <version>2.3.1</version>
        <authors>John Sheehan, Michael Lehenbauer, Alexander Batishchev</authors>
        <owners>johnsheehan, devinrader, abatishchev</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <licenseUrl>https://creativecommons.org/publicdomain/zero/1.0/</licenseUrl>
        <projectUrl>https://github.com/jwt-dotnet/jwt</projectUrl>
        <description>Jwt.Net, a JWT (JSON Web Token) implementation for .NET</description>
        <copyright>Public Domain</copyright>
        <language>en-US</language>
        <tags>jwt json</tags>
        <dependencies>
          <dependency id="Newtonsoft.Json" version="9.0.1" />  <<---- THIS LINE HERE
        </dependencies>
      </metadata>
    </package>

Then manually adding the altered Nuspec back into the nuget package file, already present in the packages directory, fixed the package.

I then manually removed the line from packages.config, then used NuGet to re-add it making sure it picked up the version in the packages directory (Which it did) and everything was/is them ok.

Shawty

**Comment by abatishchev** [comment]
Thanks a lot for so detailed problem report!
I had to add * because NuGet.org was refusing to accept the package without it. Something what wasn't there before. I don't know whether it's related to removing the beta prefix but maybe not. Don't remember any issues with not having any version specified.
Can I ask to cross-post/open an issue in NuGet own repository? Let's see what they'll us. I'm ready to make any necessary changes and republish as soon as there will be any.

**Comment by shawty** [comment]
Hi Alexander, yea sure....
What would probably be a good idea is if you create the issue on NuGet, then I'll chime in and reference this.

The reason I say this, is because if I use this as a basis to open an issue it will likely be closed as needing investigation from you guys on your package, where as if you open the issue, you have a legitimate concern that a bug in your package could effect millions of devs in VS worldwide.

That then has to be addressed by the NuGet team as a priority, rather than as a third party error.

Since we know already what the effects of the issue are, and since you have the details as to why, then you basically need to word your bug report along the lines of "Can't set min version on my package..."

I can then reference this as "an issue cause by you not being able to set your version", make sense?

Shawty

**Comment by nrhills** [comment]
Did you make any progress on this? We are seeing the same issue on our Team City server and will be rolling back to 1.3.4 until this is fixed

**Comment by abatishchev** [comment]
Sorry, no update yet. I'll try to reproduce this on an empty package.

**Comment by abatishchev** [comment]
I tried to upload package with nuspec without dependency version but still wasn't allowed to.

**Comment by abatishchev** [comment]
Folks, what version of Jon.Net you're using? I can specify something and upload a fixed version. Something like least common denominator. WebApi .X requires 6.0.x or greater. I plan to require it too then.

**Comment by abatishchev** [comment]
Please try [2.3.2](https://www.nuget.org/packages/JWT/2.3.2).

**Comment by shawty** [comment]
Works perfectly fine for me.  My min JON requirements are what ever the lowest version that NancyFX will use are, as I'm using it to hook into Nancy's Json Serializer.

Apart from that, 6.0.x or greater works for me, I always attempt to go for the latest anyway.

V2.3.2 - All good problem solved.
