### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by PureKrome** [jwt-dotnet/jwt#86]
Hi folks,

For every Request that arrives, we attempt to decode the `string token` using your `DecodeToObject<T>` method. Great! Works fine :smile:

Now, _for every Request_ I noticed the code does the following (taken from your documentation):

```
var token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGFpbTEiOjAsImNsYWltMiI6ImNsYWltMi12YWx1ZSJ9.8pwBI_HtXqI3UgQHQ_rDRnSQRxFL1SR8fbQoS-5kM5s";
var secret = "GQDstcKsx0NHjPOuXOYg5MbeJ1XT0uFiwDVvVBrk";
try
{
    IJsonSerializer serializer = new JsonNetSerializer();
    IDateTimeProvider provider = new UtcDateTimeProvider();
    IJwtValidator validator = new JwtValidator(serializer, provider);
    IBase64UrlEncoder urlEncoder = new JwtBase64UrlEncoder();
    IJwtDecoder decoder = new JwtDecoder(serializer, validator, urlEncoder);
    
    var json = decoder.Decode(token, secret, verify: true);
    Console.WriteLine(json);
}
...
```

- Create a serializer.
- Now, create a TimeProvider.
- ... etc..

Basically, each request keeps creating the _same_ objects again and again.

So - why can't these be `static` ?

- Create them all once.
- `_decoder.Decode(..);`

e.g.
```
private static IJwtAlgorithm _algorithm = new HMACSHA256Algorithm();
private static IJsonSerializer _serializer = new JsonNetSerializer();
private static IDateTimeProvider _provider = new UtcDateTimeProvider();
private static IJwtValidator _validator = new JwtValidator(_serializer, _provider);
private static IBase64UrlEncoder _urlEncoder = new JwtBase64UrlEncoder();
private static IJwtEncoder _encoder = new JwtEncoder(_algorithm, _serializer, _urlEncoder);
private static IJwtDecoder _decoder = new JwtDecoder(_serializer, _validator, _urlEncoder);

<in some method>
_decoder.Decode(..);
...
```

So - is this possible? OK? These things thread safe?

**Comment by abatishchev** [comment]
Hey!
There were legacy API where everything were static indeed. But then there were several requests to inject different implementations of JSON (de)serializer, etc. And things went ugly.
So since version 2.0, interfaces and instances are used instead. And static API is just a wrapper that instantiate everything for you. By the way, just once.
Interfaces fo different implementations, instances to be wired-up using a dependency injection container.
Documentation doesn't say one should do all this every time on every request. And they really should not. Hope nobody does :)

Also hope this answers your question.

**Comment by abatishchev** [comment]
How static API does things see https://github.com/jwt-dotnet/jwt/blob/master/src/JWT/JsonWebToken.cs#L20

**Comment by nbarbettini** [comment]
To add to what @abatishchev said - if you are using a DI container (the service container in ASP.NET Core for example), you should be able to add the `IJwtDecoder` interface to the container with a singleton lifetime. 👍

**Comment by PureKrome** [comment]
Ok - thanks all.

So to answer the initial question - the library is thread safe .. meaning ... I could reuse a SINGLE `JwtDecoder` (and therefore a single `IBase64UrlEncoder, IJwtValidator`, etc) at the same time as multiple requests pop in? Case-in-point:
- >add the IJwtDecoder interface to the container with a singleton lifetime.
- `public static class JsonWebToken` wrapper class

---

>Documentation doesn't say one should do all this every time on every request. And they really should not. Hope nobody does :)

Yep, agreed. Looking at the docs, that was what my first, initial understanding of the usage was. Also, I found this library because it's used in other applications ... and as you can guess, it's a new instance per request :(

> you should be able to add the IJwtDecoder interface to the container with a singleton lifetime. 

Oh kewl! I totally grok DI/IoC etc so this is nice and I'll definitely do this.

---

Side Note: Unless I skim read or suck at reading (note: I do suck at reading) there should be some info about creating the `IJwtEncoder/IJwtDecoder` once (aka singleton) and reusing that, IMO.

**Comment by nbarbettini** [comment]
> I could reuse a SINGLE JwtDecoder (and therefore a single IBase64UrlEncoder, IJwtValidator, etc) at the same time as multiple requests pop in?

Yep, should be fine. 👍  This library doesn't really incur or hold onto any state, so it should be inherently thread-safe.

FWIW, it's inefficient but probably not a huge performance hit to create instances on every request.

> there should be some info about creating the IJwtEncoder/IJwtDecoder once (aka singleton) and reusing that, IMO.

Good idea 👍

**Comment by abatishchev** [comment]
Answering your initial question, both old and new APIs should be thread-safe. We don't have a test to make sure. But from the code perspective - it should be.

You're welcome to contribute to the docs to cover this topic more thoughtfully ;) I'm not a native English speaker so writing docs is not my strong side.

Can I close the issue?

**Comment by PureKrome** [comment]
@abatishchev thanks for all the help! Closing now. 👍
