### ISSUE TITLE
exp validation should parse to double, not int

### ISSUE THREAD

**Issue by zemien** [jwt-dotnet/jwt#88]
JwtValidator.cs: Validate(...) converts the exp claim into an integer:
`expInt = Convert.ToInt32(expObj);`

However this fails if I attempt to set an expiry past 19 January 2038, [the Year 2038 problem](https://en.wikipedia.org/wiki/Unix_time).

The definition of [seconds since the epoch](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_15) does not enforce that the result is an integer, merely that the "tm_sec, tm_min, tm_hour, tm_yday, and tm_year" components that are in the expression "are all integer types".

Hence I think all epoch date conversions should be parsed to double, which will support dates beyond DateTime.MaxValue.

**Comment by abatishchev** [comment]
Sure, let's get this fixed! Can you please submit a pr, preferably with few tests?
