### ISSUE TITLE
Deploy to NuGet automatically

### ISSUE THREAD

**Issue by nbarbettini** [jwt-dotnet/jwt#93]
- [x] CI using AppVeyor
- [ ] Link AppVeyor to MyGet?
- [x] Publish to NuGet

**Comment by nbarbettini** [comment]
@abatishchev This is actually already done. 😄  The only step remaining is to hook up AppVeyor to wherever you want to push packages. Do you want to push them to MyGet first, and then to NuGet? Or straight to NuGet?

**Comment by nbarbettini** [comment]
Basically, you will define a push target (Environment tab in AppVeyor), and connect it to either MyGet or NuGet (or both!). Then, from the Artifacts tab on a specific build, just click Deploy. 👍

**Comment by abatishchev** [comment]
Hm, I don't see anything related under the Environment tab.
I added *.nupkg to Artifacts and NuGet to Deployment. But still when I select Deployments it asks to select the envrioment and the list is empty.
Doc mention it can (should?) be configured via the manifest https://www.appveyor.com/docs/deployment/nuget/

**Comment by abatishchev** [comment]
Ok, I created an environment at https://ci.appveyor.com/environments but it doesn't seem what I need.

**Comment by abatishchev** [comment]
Here we go https://ci.appveyor.com/project/abatishchev/jwt/deployment/720226

**Comment by abatishchev** [comment]
Done! https://www.nuget.org/packages/JWT/3.0.0-beta1

Marked "Publish to NuGet" as done :)

**Comment by nbarbettini** [comment]
Awesome!
