### ISSUE TITLE
Integrate with CodeCov

### ISSUE THREAD

**Issue by abatishchev** [jwt-dotnet/jwt#96]
Instruction that includes AppVeyor: https://github.com/codecov/example-csharp/blob/master/readme.md

**Comment by abatishchev** [comment]
@nbarbettini what do you think? Have you tried it before?

**Comment by nbarbettini** [comment]
I haven't tried it myself. I looked into it a while back, but I think it didn't have support for .NET Core. Not sure if that's changed.

**Comment by abatishchev** [comment]
Now they do but require an extra step to generate coverage results in some open format and then upload them. Not worth it from my perspective
